uxlfoundation/oneDAL

- include/data_management/data/aos_numeric_table.h
Checks that offset and index in setFeature and setOffset is in valid range
> aos_numeric_table.h check offset and index values

- README.md
This PR contain following changes in README.md
- replace tabs with 4 spaces
- replace quote symbols in README
You can take a look on new version of  document here - https://github.com/napetrov/daal/tree/fix_63
> Fix quote symbols used in README.md

- README.md
#Description
Adding CI status badge to README.md page  - [![Build Status](https://dev.azure.com/daal/DAAL/_apis/build/status/intel.daal?branchName=master)](https://dev.azure.com/daal/DAAL/_build/latest?definitionId=3&branchName=master) 
Changes:
- CI status badge added
> adding CI badge to README.md

- .github/ISSUE_TEMPLATE/bug_report.md
#Description 
This change introduce first version of issues template for bugs
Changes:
- First version of issues template
> Initial version of issue templates

- algorithms/kernel/dtrees/gbt/classification/gbt_classification_train_dense_default_impl.i
- algorithms/kernel/dtrees/gbt/classification/gbt_classification_training_result.cpp
- algorithms/kernel/dtrees/gbt/classification/gbt_classification_training_result_fpt.cpp
- algorithms/kernel/dtrees/gbt/gbt_model.cpp
- algorithms/kernel/dtrees/gbt/gbt_model_impl.h
- algorithms/kernel/dtrees/gbt/gbt_train_dense_default_impl.i
- algorithms/kernel/dtrees/gbt/gbt_train_tree_builder.i
- algorithms/kernel/dtrees/gbt/gbt_training_parameter.cpp
- algorithms/kernel/dtrees/gbt/regression/gbt_regression_train_dense_default_impl.i
- algorithms/kernel/dtrees/gbt/regression/gbt_regression_training_result.cpp
- algorithms/kernel/dtrees/gbt/regression/gbt_regression_training_result_fpt.cpp
- include/algorithms/gradient_boosted_trees/gbt_classification_training_types.h
- include/algorithms/gradient_boosted_trees/gbt_regression_training_types.h
- include/algorithms/gradient_boosted_trees/gbt_training_parameter.h
Feature importance computing for gradient boosting have been added
> GBT Feature Importance

- build/cmplr.clang.mk
- build/cmplr.gnu.mk
- build/cmplr.icc.mk
- build/common.mk
Enabling compiler security options as SDL requirement
> Enabling compiler options 

- build/cmplr.gnu.mk
- build/common.mk
- makefile
It updates the makefile to support cross compilation for other Linux distro
such as yocto.
> build: Updates vars as per GNU guidelines

- algorithms/kernel/assocrules/assoc_rules_apriori_impl.i
- algorithms/kernel/implicit_als/implicit_als_train_csr_default_distr_impl.i
- algorithms/kernel/implicit_als/implicit_als_train_distributed.cpp
- algorithms/kernel/implicit_als/implicit_als_train_init_csr_default_distr_impl.i
- algorithms/kernel/kmeans/kmeans_lloyd_impl.i
- algorithms/kernel/logitboost/logitboost_train_friedman_aux.i
- algorithms/kernel/optimization_solver/sgd/inner/sgd_types_v1.cpp
- algorithms/kernel/optimization_solver/sgd/inner/sgd_types_v1_fpt.cpp
- algorithms/kernel/optimization_solver/sgd/sgd_types.cpp
- algorithms/kernel/optimization_solver/sgd/sgd_types_fpt.cpp
- algorithms/kernel/svm/inner/svm_train_boser_avx512_impl_v1.i
- algorithms/kernel/svm/svm_train_boser_avx512_impl.i
> Fix error in debug mode

- algorithms/kernel/svm/svm_train_boser_impl.i
Fix the bug that was found from accuaracy test
> Fix the bug in svm_train

- .ci/pipeline/ci.yml
This change switch CI build process from all CPUs to single CPU
> Enable one cpu build for CI

- .ci/pipeline/ci.yml
ap-get update added to the public CI
> apt-get update added to the public CI

- samples/scala/spark/sources/KMeans.scala
optimized spark sample KMeans for case, when data doesn't fit in memory
> optimized spark sample KMean

- scripts/mklfpk.sh
- scripts/tbb.sh
handler added in case of download is unsuccessful.
> helper scripts fixed

- .github/pull_request_template.md
This change introduce first version of generic pull requests template that will be applied for new PRs in this repo
- first version of pull_request_template.md
> Enabling pull request template

- .ci/pipeline/ci.yml
This change switching linux systems in public CI from Ubuntu 16.04 to 18.04
> Switching public pipeline to Ubuntu 18.04

- algorithms/kernel/kmeans/oneapi/kmeans_dense_lloyd_batch_kernel_ucapi_impl.i
-
-Added reasonable block size for KMeans
-
> Added reasonable blocks for KMeans

- algorithms/kernel/dtrees/dtrees_model_impl.h
- algorithms/kernel/dtrees/forest/classification/df_classification_model.cpp
- algorithms/kernel/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
- algorithms/kernel/dtrees/forest/classification/df_classification_train_dense_default_impl.i
- algorithms/kernel/dtrees/forest/df_train_dense_default_impl.i
Changes from this pull request will improve performance of training stage of Decision forest.
- Remove new memory allocations, which appears when probabilities calculation has been implemented.
- Vectorize all cycles, which can be vectorized.
> Improve performance of training stage of Decision Forest

- include/oneapi/internal/execution_context.h
> Removed trailing space

- algorithms/kernel/k_nearest_neighbors/oneapi/bf_knn_classification_predict_kernel_ucapi_impl.i
- service/kernel/oneapi/cl_kernels/select_indexed.cl
> Fixed rng buffer transferring for KNN

- scripts/mklfpk.sh
Fixing typo in script that have been preventing mklfpkgpu download
> Fix typo in script that prevents mklfpkgpu download

- examples/cpp_sycl/DAALExamples_sycl.sln
- examples/cpp_sycl/vcproj/bf_knn_dense_batch/bf_knn_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/bf_knn_dense_batch/bf_knn_dense_batch.vcxproj.filters
- examples/cpp_sycl/vcproj/bf_knn_dense_batch/bf_knn_dense_batch.vcxproj.user
> Added KNN example to VS solution

- doxygen_conf_cpp.txt
- doxygen_conf_cpp_examples.txt
- doxygen_conf_cpp_web.txt
- doxygen_conf_java.txt
- doxygen_conf_java_examples.txt
- doxygen_conf_java_web.txt
- makefile.ver
- service/kernel/dll.rc
From `oneDAL 2021.1 - beta02` to `oneDAL 2021.1 - beta03`
> Update oneDAL version

- examples/cpp_sycl/source/k_nearest_neighbors/bf_knn_dense_batch.cpp
- include/algorithms/k_nearest_neighbors/bf_knn_classification_predict.h
- include/algorithms/k_nearest_neighbors/bf_knn_classification_training_batch.h
> Added public input field to BF KNN batches

- .github/CODEOWNERS
Initial version of codeowners file.
Make @outoftardis owner of documentation
> Initial version of codeowners

- algorithms/kernel/classifier/multiclass_confusion_matrix_types.cpp
- algorithms/kernel/decision_tree/decision_tree_classification_split_criterion.i
- algorithms/kernel/decision_tree/decision_tree_regression_split_criterion.i
- algorithms/kernel/dtrees/forest/classification/df_classification_train_dense_default_impl.i
- algorithms/kernel/implicit_als/implicit_als_predict_ratings_result_fpt.cpp
- algorithms/kernel/kmeans/kmeans_init_container.h
- algorithms/kernel/kmeans/kmeans_lloyd_distr_step2_impl.i
- examples/cpp/source/kmeans/kmeans_init_csr_distr.cpp
- examples/cpp/source/kmeans/kmeans_init_dense_distr.cpp
- examples/cpp/source/optimization_solvers/custom_obj_func.h
- examples/cpp/source/outlier_detection/out_detect_uni_dense_batch.cpp
- include/algorithms/decision_forest/decision_forest_classification_model_builder.h
- include/algorithms/gradient_boosted_trees/gbt_classification_model_builder.h
- include/algorithms/gradient_boosted_trees/gbt_regression_model_builder.h
- include/data_management/compression/compression.h
- include/data_management/data/arrow_numeric_table.h
- include/data_management/data/csr_numeric_table.h
- include/data_management/data/numeric_table_sycl_soa.h
- include/data_management/data/row_merged_numeric_table.h
- include/oneapi/internal/execution_context_sycl.h
- lang_service/java/com/intel/daal/data_management/data/csr_numeric_table_impl.cpp
- lang_service/java/com/intel/daal/data_management/data/homogen_numeric_table_byte_buffer_impl.cpp
- lang_service/java/com/intel/daal/data_management/data/merged_numeric_table_impl.cpp
- lang_service/java/com/intel/daal/data_management/data/packed_symmetric_matrix_byte_buffer_impl.cpp
- lang_service/java/com/intel/daal/data_management/data/packed_triangular_matrix_byte_buffer_impl.cpp
- lang_service/java/com/intel/daal/data_management/data/row_merged_numeric_table_impl.cpp
- service/kernel/data_management/daal_factory_impl.cpp
- service/kernel/service_topo.cpp
make static analyzer more happier
> code cleanup

- samples/scala/spark/sources/ALS.scala
- samples/scala/spark/sources/SVD.scala
- samples/scala/spark/sources/SampleKMeans.scala
- samples/scala/spark/sources/SampleSVD.scala
Сhanged storage levels in kmeans and svd.
Modified SVD for performance improvement in case when data does not fit into memory.
Updated comparison function in sorting for ALS, to speed up conversion.
> change storage levels and modified SVD

- docs/source/dev_guide/algorithms/kmeans/k-means-clustering.rst
- docs/source/dev_guide/algorithms/logistic_regression/logistic-regression.rst
- Fix description of logistic regression's result
- Fix typo in KMeans
> Documentation has been fixed

- doxygen_conf_cpp.txt
- doxygen_conf_cpp_examples.txt
- doxygen_conf_cpp_web.txt
- doxygen_conf_java.txt
- doxygen_conf_java_examples.txt
- doxygen_conf_java_web.txt
- makefile.ver
- service/kernel/dll.rc
From `oneDAL 2021.1 - beta03` to `oneDAL 2021.1 - beta04`
> Update oneDAL version from beta03 to beta04

- algorithms/kernel/objective_function/logistic_loss/logistic_loss_dense_default_batch_impl.i
Fix was applied to clear/rewrite buffer allocated for gradient before compute.
> Fix gradient computation

- docs/source/topics/generic-workflow.rst
- A more detailed explanation of the things happened in the generic workflow topic in the docs
> Generic workflow explained

- docs/source/topics/generic-workflow.rst
The clone of #236 for the releases branch
> [Releases] Generic workflow explained

- include/data_management/data/arrow_numeric_table.h
- samples/cpp/arrow/README.md
- samples/cpp/arrow/daal.lst.bat
- samples/cpp/arrow/daal_lnx.lst
- samples/cpp/arrow/daal_mac.lst
- samples/cpp/arrow/launcher.bat
- samples/cpp/arrow/license.txt
- samples/cpp/arrow/makefile_lnx
- samples/cpp/arrow/makefile_mac
- samples/cpp/arrow/readme.html
- samples/cpp/arrow/sources/datastructures_arrow.cpp
- samples/cpp/arrow/sources/error_handling.h
- samples/cpp/arrow/sources/service.h
- Fix for supporting newer version of Apache Arrow 
- Apache Arrow sample has been updated. Support for Win and Mac has been added.
> Fix Apache Arrow support.

- examples/cpp_sycl/makefile_lnx
- examples/cpp_sycl/makefile_win
- examples/cpp_sycl/vcproj/bf_knn_dense_batch/bf_knn_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/cor_dense_batch/cor_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/cor_dense_online/cor_dense_online.vcxproj
- examples/cpp_sycl/vcproj/datastructures_soa/datastructures_soa.vcxproj
- examples/cpp_sycl/vcproj/datastructures_usm/datastructures_usm.vcxproj
- examples/cpp_sycl/vcproj/gbt_reg_dense_batch/gbt_reg_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/kmeans_dense_batch/kmeans_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/kmeans_init_dense_batch/kmeans_init_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/lin_reg_norm_eq_dense_batch/lin_reg_norm_eq_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/log_reg_binary_dense_batch/log_reg_binary_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/log_reg_dense_batch/log_reg_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/low_order_moms_dense_batch/low_order_moms_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/low_order_moms_dense_online/low_order_moms_dense_online.vcxproj
- examples/cpp_sycl/vcproj/pca_cor_dense_batch/pca_cor_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/sgd_mini_log_loss_dense_batch/sgd_mini_log_loss_dense_batch.vcxproj
- include/oneapi/internal/math/blas_executor.h
- include/oneapi/internal/math/lapack_executor.h
MKL functions are enabled by default and gbt vsproj fixed
> MKL functions are enabled by default (#258)

- CONTRIBUTING.md
- README.md
The clone of #268 pull request.
> [releases]Update README.md and create CONTRIBUTING.md

- algorithms/kernel/pca/oneapi/pca_dense_correlation_batch_kernel_ucapi_impl.i
- algorithms/kernel/pca/transform/oneapi/cl_kernels/pca_transform_cl_kernels.cl
- algorithms/kernel/pca/transform/oneapi/pca_transform_dense_default_batch_oneapi.h
- algorithms/kernel/pca/transform/oneapi/pca_transform_dense_default_batch_oneapi_impl.i
- algorithms/kernel/pca/transform/pca_transform_batch_fpt.cpp
- algorithms/kernel/pca/transform/pca_transform_container.h
- algorithms/kernel/pca/transform/pca_transform_dense_default_batch_oneapi_fpt.cpp
- examples/cpp_sycl/DAALExamples_sycl.sln
- examples/cpp_sycl/daal_lnx.lst
- examples/cpp_sycl/makefile_lnx
- examples/cpp_sycl/source/pca_transform/pca_transform_dense_batch.cpp
- examples/cpp_sycl/vcproj/pca_transform_dense_batch/pca_transform_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/pca_transform_dense_batch/pca_transform_dense_batch.vcxproj.filters
- examples/cpp_sycl/vcproj/pca_transform_dense_batch/pca_transform_dense_batch.vcxproj.user
- service/kernel/oneapi/blas_gpu.cpp
The clone of #250 for releases branch
CI: http://intel-ci.intel.com/ea3922b5-574c-f1dc-aee4-8cdcd4b723a1
> [Releases] Enabling PCA transform algorithm support for GPU 

- LICENSE
- bzip2
- zlib
- Intel® Integrated Performance Primitives (Intel® IPP) Library
- Intel® Math Kernel Library (Intel® MKL)
- Intel® Threading Building Blocks (Intel® TBB)
- prism
- Python Sphinx
> third-party components were added to licence file

- lang_interface/java/com/intel/daal/algorithms/linear_regression/prediction/Input.java
- lang_interface/java/com/intel/daal/algorithms/ridge_regression/prediction/Input.java
- lang_interface/java/com/intel/daal/data_management/data/HomogenNumericTable.java
- lang_interface/java/com/intel/daal/data_management/data/PackedSymmetricMatrix.java
- lang_interface/java/com/intel/daal/data_management/data/PackedTriangularMatrix.java
> Redundand cast removed

- algorithms/kernel/covariance/oneapi/cl_kernels/covariance_kernels.cl
- algorithms/kernel/covariance/oneapi/covariance_oneapi_impl.i
- include/oneapi/internal/execution_context.h
- include/oneapi/internal/execution_context_sycl.h
- include/oneapi/internal/math/blas_executor.h
- include/oneapi/internal/math/mkl_blas.h
- include/oneapi/internal/math/reference_axpy.h
- service/kernel/oneapi/blas_gpu.cpp
- service/kernel/oneapi/blas_gpu.h
- service/kernel/oneapi/cl_kernels/kernel_blas.cl
> online covariance improvements

- algorithms/kernel/covariance/covariance_partialresult.h
- algorithms/kernel/covariance/covariance_result.h
clone of https://github.com/intel/daal/pull/237
> changed results tables in online covariance to sycl for gpu

- CONTRIBUTING.md
> [releases] Update CONTRIBUTING.md

- algorithms/kernel/covariance/covariance_partialresult.h
- algorithms/kernel/covariance/covariance_result.h
- algorithms/kernel/covariance/oneapi/cl_kernels/covariance_kernels.cl
- algorithms/kernel/covariance/oneapi/covariance_oneapi_impl.i
- include/oneapi/internal/execution_context.h
- include/oneapi/internal/execution_context_sycl.h
- include/oneapi/internal/math/blas_executor.h
- include/oneapi/internal/math/mkl_blas.h
- include/oneapi/internal/math/reference_axpy.h
- service/kernel/oneapi/blas_gpu.cpp
- service/kernel/oneapi/blas_gpu.h
- service/kernel/oneapi/cl_kernels/kernel_blas.cl
cherry-pick 
https://github.com/intel/daal/pull/195
https://github.com/intel/daal/pull/262
> [releases] Covariance improvements 

- include/oneapi/internal/math/blas_executor.h
- service/kernel/oneapi/blas_gpu.cpp
cherry-pick 
https://github.com/intel/daal/pull/304
> [releases] raise one level up the axpy input check

- algorithms/kernel/export_win32e.def
- algorithms/threading/export.def
- algorithms/threading/export_lnx32e.def
- algorithms/threading/export_mac.def
- build/common.mk
- examples/cpp_sycl/makefile_win
- examples/cpp_sycl/vcproj/bf_knn_dense_batch/bf_knn_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/cor_dense_batch/cor_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/cor_dense_online/cor_dense_online.vcxproj
- examples/cpp_sycl/vcproj/datastructures_soa/datastructures_soa.vcxproj
- examples/cpp_sycl/vcproj/datastructures_usm/datastructures_usm.vcxproj
- examples/cpp_sycl/vcproj/gbt_reg_dense_batch/gbt_reg_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/kmeans_dense_batch/kmeans_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/kmeans_init_dense_batch/kmeans_init_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/lin_reg_norm_eq_dense_batch/lin_reg_norm_eq_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/log_reg_binary_dense_batch/log_reg_binary_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/log_reg_dense_batch/log_reg_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/low_order_moms_dense_batch/low_order_moms_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/low_order_moms_dense_online/low_order_moms_dense_online.vcxproj
- examples/cpp_sycl/vcproj/pca_cor_dense_batch/pca_cor_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/pca_transform_dense_batch/pca_transform_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/sgd_mini_log_loss_dense_batch/sgd_mini_log_loss_dense_batch.vcxproj
- externals/core_threading_win_dll.cpp
- makefile
cherry-pick of https://github.com/intel/daal/pull/309 to releases
> Fix gap in WindowsDLL libs structure

- algorithms/kernel/dtrees/dtrees_feature_type_helper.h
- algorithms/kernel/dtrees/forest/classification/df_classification_predict_dense_default_batch.h
- algorithms/kernel/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
Optimization for one row inference in DF classification
> Optimization for one row inference in DF

- doxygen_conf_cpp.txt
- doxygen_conf_cpp_examples.txt
- doxygen_conf_cpp_web.txt
- doxygen_conf_java.txt
- doxygen_conf_java_examples.txt
- doxygen_conf_java_web.txt
- makefile.ver
- service/kernel/_daal_version.h
- service/kernel/dll.rc
> update version to beta05

- include/data_management/data/internal/conversion.h
- include/data_management/data/soa_numeric_table.h
- include/data_management/features/compatibility.h
- service/kernel/data_management/data_conversion.cpp
- service/kernel/data_management/data_conversion_cpu.cpp
- service/kernel/data_management/data_conversion_cpu.h
SOA optimization. Fix for nightly test. Fix code style.
> fix for nightly test. soa optimization.

- algorithms/kernel/linear_model/linear_model_predict_batch_fpt.cpp
- algorithms/kernel/linear_model/oneapi/cl_kernel/reduce_results.cl
- algorithms/kernel/linear_model/oneapi/linear_model_train_normeq_kernel_oneapi.h
- algorithms/kernel/linear_model/oneapi/linear_model_train_normeq_update_oneapi_impl.i
- algorithms/kernel/linear_regression/linear_regression_train_container.h
- algorithms/kernel/linear_regression/linear_regression_train_dense_normeq_online_oneapi_fpt.cpp
- algorithms/kernel/linear_regression/oneapi/linear_regression_train_dense_normeq_oneapi_impl.i
- algorithms/kernel/linear_regression/oneapi/linear_regression_train_kernel_oneapi.h
- examples/cpp_sycl/DAALExamples_sycl.sln
- examples/cpp_sycl/daal_lnx.lst
- examples/cpp_sycl/source/linear_regression/lin_reg_norm_eq_dense_online.cpp
- examples/cpp_sycl/vcproj/lin_reg_norm_eq_dense_online/lin_reg_norm_eq_dense_online.vcxproj
- examples/cpp_sycl/vcproj/lin_reg_norm_eq_dense_online/lin_reg_norm_eq_dense_online.vcxproj.filters
- examples/cpp_sycl/vcproj/lin_reg_norm_eq_dense_online/lin_reg_norm_eq_dense_online.vcxproj.user
- include/oneapi/internal/execution_context_sycl.h
- include/oneapi/internal/math/blas_executor.h
- include/oneapi/internal/math/mkl_blas.h
- include/oneapi/internal/math/reference_axpy.h
- service/kernel/oneapi/blas_gpu.cpp
- service/kernel/oneapi/blas_gpu.h
Included:
- algorithm
- examples
- fix of allocation Result for predict kernel
> [releases] Linear Regression in online mode was added (#295)

- algorithms/kernel/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
Fix CEV build after optimizations
> Fix CEV build after optimizations

- algorithms/kernel/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
Fix CEV build after optimizations in DF
> Fix CEV build after optimizations in DF

- include/data_management/data/internal/conversion.h
- include/data_management/data/soa_numeric_table.h
- include/data_management/features/compatibility.h
- service/kernel/data_management/data_conversion.cpp
- service/kernel/data_management/data_conversion_cpu.cpp
- service/kernel/data_management/data_conversion_cpu.h
- service/kernel/data_management/soa_numeric_table.cpp
SOA optimization for releases branch.
AVX512 architecture.
> soa optimizaion for release branch

- include/oneapi/internal/execution_context_sycl.h
cherry-pick
https://github.com/intel/daal/pull/315
> [releases] hash collision in execution_context_sycl was fixed.

- algorithms/kernel/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
Fix alignment for vector store
> Fix alignment for vector store

- algorithms/kernel/dtrees/forest/classification/df_classification_model.cpp
- algorithms/kernel/dtrees/forest/regression/df_regression_model.cpp
df_classification_model.cpp
df_regression_model.cpp
> fix for potential memory leak

- include/algorithms/dbscan/dbscan_distributed.h
- include/algorithms/implicit_als/implicit_als_predict_ratings_distributed.h
- include/algorithms/implicit_als/implicit_als_training_distributed.h
- include/algorithms/implicit_als/implicit_als_training_init_distributed.h
- include/algorithms/kmeans/kmeans_distributed.h
- include/algorithms/kmeans/kmeans_init_distributed.h
- include/algorithms/linear_regression/linear_regression_training_distributed.h
- include/algorithms/moments/low_order_moments_distributed.h
- include/algorithms/naive_bayes/multinomial_naive_bayes_training_distributed.h
- include/algorithms/pca/pca_distributed.h
- include/algorithms/qr/qr_distributed.h
- include/algorithms/ridge_regression/ridge_regression_training_distributed.h
- include/algorithms/svd/svd_distributed.h
This classes has some pointer manipulation and clone() method;
> disable operator= for Distributed classes

- docs/source/conf.py
Changed the year in copyright in Sphinx' configs.
> Change year from 2019 to 2020 in rst docs

- docs/source/conf.py
> [releases] Change year from 2019 to 2020 in rst docs

- algorithms/kernel/dtrees/forest/classification/df_classification_predict_dense_default_batch.h
- include/algorithms/algorithm_base_mode_impl.h
- include/algorithms/algorithm_container_base_batch.h
- include/algorithms/classifier/classifier_training_online.h
- include/algorithms/linear_regression/linear_regression_training_online.h
- include/algorithms/moments/low_order_moments_online.h
- include/algorithms/naive_bayes/multinomial_naive_bayes_training_online.h
- include/algorithms/pca/pca_online.h
- include/algorithms/qr/qr_online.h
- include/algorithms/ridge_regression/ridge_regression_training_online.h
- include/algorithms/svd/svd_online.h
- include/data_management/data/data_archive.h
This classes has ptr field, or has clone method, or non-trivial copy-ctor
> Disable operator= in Online and other classes

- algorithms/kernel/k_nearest_neighbors/kdtree_knn_classification_model_impl.h
Fix SDL gaps in KNN algorithm. Added some instructions according to SDL T204 requirements.
> Fix SDL gaps in knn

- algorithms/kernel/dtrees/dtrees_model_impl.h
- algorithms/kernel/dtrees/dtrees_model_impl_common.h
- algorithms/kernel/dtrees/forest/classification/df_classification_model.cpp
- algorithms/kernel/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
- algorithms/kernel/dtrees/forest/classification/df_classification_train_dense_default_impl.i
- algorithms/kernel/dtrees/forest/df_train_dense_default_impl.i
- algorithms/kernel/dtrees/regression/dtrees_regression_model.cpp
- Merge redundant memory allocations into existing allocations (and repair memory leaks)
- Fill undefined values "featureValueOrResponse" and "leftIndexOrClass" in leaves for classification and regression
> Fix for DF training

- LICENSE
- bzip2
- zlib
- Intel® Integrated Performance Primitives (Intel® IPP) Library
- Intel® Math Kernel Library (Intel® MKL)
- Intel® Threading Building Blocks (Intel® TBB)
- prism
> [2020 rls] third-party components were added to licence file

- algorithms/kernel/k_nearest_neighbors/kdtree_knn_classification_model_impl.h
> Fix SDL gaps in KNN in releases

- algorithms/kernel/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
Fix for 32bit system: without aligned memory support
> Fix for 32bit ssystem: without aligned memory support

- algorithms/kernel/dtrees/forest/classification/df_classification_model.cpp
Fix serialization and deserializattion in DF classification
> Fix serialization and deserializattion in DF classification

- algorithms/kernel/decision_tree/decision_tree_classification_model_impl.cpp
- algorithms/kernel/decision_tree/decision_tree_classification_model_impl.h
- algorithms/kernel/dtrees/forest/classification/df_classification_model.cpp
- algorithms/kernel/dtrees/forest/classification/df_classification_model_impl.h
- include/algorithms/decision_forest/decision_forest_classification_model.h
- include/algorithms/decision_tree/decision_tree_classification_model.h
> Fix BC for trees

- .ci/pipeline/ci.yml
Update macOS version in public CI to 10.15
> Update macOS to 10.15 in public CI build

- makefile
> Fix for DAAL build if tbb installed to "program files"

- CONTRIBUTING.md
- docs/source/_static/style.css
- docs/source/conf.py
- docs/source/contribution/coding_guide.rst
- docs/source/index.rst
- Added coding guidelines to documentation
- Updated CONTRIBUTING.md
> Added Coding Guidelines

- CONTRIBUTING.md
- docs/source/_static/style.css
- docs/source/conf.py
- docs/source/contribution/coding_guide.rst
- docs/source/index.rst
Same as #396 (with one old commit from #305 that was not merged into releases for some reason)
> [releases] Added Coding Guidelines

- .ci/pipeline/ci.yml
switching to macOS 10.15 in public CI
> switching to macOS 10.15 in public CI

- include/data_management/data_source/data_source_dictionary.h
> fix DAAL build by newest msvs2019

- include/algorithms/neural_networks/layers/loss/logistic_cross_layer_backward_types.h
- include/algorithms/neural_networks/layers/pooling3d/pooling3d_layer_forward_types.h
- include/data_management/data/internal/conversion.h
- include/data_management/data/soa_numeric_table.h
- include/data_management/features/compatibility.h
- service/kernel/data_management/data_conversion.cpp
Fix problems with build for VS
> Fix build for VS in mnt

- include/algorithms/neural_networks/layers/loss/logistic_cross_layer_backward_types.h
- include/algorithms/neural_networks/layers/pooling3d/pooling3d_layer_forward_types.h
- include/data_management/data/internal/conversion.h
- include/data_management/data/soa_numeric_table.h
- include/data_management/features/compatibility.h
- service/kernel/data_management/data_conversion.cpp
> [cherry pick] Fix of building with vs

- include/data_management/data/internal/conversion.h
- include/data_management/data/soa_numeric_table.h
- include/data_management/features/compatibility.h
- service/kernel/data_management/data_conversion.cpp
Fix Test System build in VS.
-
-
> Fix build TS in VS

- include/data_management/data/internal/conversion.h
- include/data_management/data/soa_numeric_table.h
- include/data_management/features/compatibility.h
- service/kernel/data_management/data_conversion.cpp
Fix build TS in VS in release branch
> Fix build TS in VS for release branch

- service/kernel/data_management/finiteness_checker.cpp
> [master] Fix for finiteness checker

- docs/source/dev_guide/algorithms/decision_forest/decision-forest-classification.rst
- docs/source/dev_guide/algorithms/decision_forest/decision-forest.rst
- Added votingMethod for decision forest classification
- Fixed a typo in a parameter name
> Updated docs for decision forest

- algorithms/kernel/elastic_net/elastic_net_train_dense_default_impl.i
- algorithms/kernel/elastic_net/elastic_net_training_types.cpp
- examples/cpp/source/elastic_net/elastic_net_dense_batch.cpp
- examples/java/com/intel/daal/examples/elastic_net/ElasticNetDenseBatch.java
- include/algorithms/elastic_net/elastic_net_training_types.h
- lang_interface/java/com/intel/daal/algorithms/elastic_net/TrainParameter.java
- lang_service/java/com/intel/daal/algorithms/elastic_net/train_parameter.cpp
- service/kernel/daal_strings.h
Finalize naming of Elastic Net parameters, new names are penaltyL1 and penaltyL2
> Finalize naming of Elastic Net parameters

- INSTALL.md
- README.md
* Added to README the links to System Requirements for oneDAL/DAAL
* Changed the link to System Requirements in INSTALL.md
> Updated INSTALL.md and README.md with links to SysReq

- docs/source/dev_guide/algorithms/decision_forest/decision-forest-classification.rst
- docs/source/dev_guide/algorithms/decision_forest/decision-forest.rst
> [releases] Updated docs for decision forest

- INSTALL.md
- README.md
> [releases] Updated INSTALL.md and README.md with links to SysReq

- .ci/pipeline/ci.yml
- .ci/scripts/build.sh
- .ci/scripts/test.sh
moving code from pipeline to scripts
- moving code from pipeline to scripts
- enable example run
> move code from pipline to script

- .ci/pipeline/ci.yml
- .ci/scripts/build.sh
- .ci/scripts/test.sh
moving code from pipeline to scripts
- moving code from pipeline to scripts
- enable example run
> [releases] move code from pipline to script

- include/data_management/data/internal/finiteness_checker.h
- service/kernel/data_management/finiteness_checker.cpp
> [2020-u1-rls] Finiteness checker fix

- service/kernel/data_management/finiteness_checker.cpp
Cherry-pick of [#412](https://github.com/intel/daal/pull/412)
> [daal-2020-mnt] Finiteness checker fix

- service/kernel/data_management/finiteness_checker.cpp
Cherry-pick of [#406](https://github.com/intel/daal/pull/406)
> [onedal-beta05-rls] Finiteness checker fix

- service/kernel/data_management/finiteness_checker.cpp
Cherry-pick of [#406](https://github.com/intel/daal/pull/406)
> [releases] Finiteness checker fix

- algorithms/kernel/pca/oneapi/pca_dense_correlation_batch_kernel_ucapi_impl.i
- algorithms/kernel/pca/transform/oneapi/cl_kernels/pca_transform_cl_kernels.cl
- algorithms/kernel/pca/transform/oneapi/pca_transform_dense_default_batch_oneapi.h
- algorithms/kernel/pca/transform/oneapi/pca_transform_dense_default_batch_oneapi_impl.i
Added itt notify tasks for pca transform
> Add itt notify tasks for pca transform

- algorithms/kernel/pca/transform/oneapi/cl_kernels/pca_transform_cl_kernels.cl
- algorithms/kernel/pca/transform/oneapi/pca_transform_dense_default_batch_oneapi.h
- algorithms/kernel/pca/transform/oneapi/pca_transform_dense_default_batch_oneapi_impl.i
> [cherry-pick] Add itt notify tasks for pca transform (#416)

- algorithms/kernel/elastic_net/elastic_net_train_dense_default_impl.i
- algorithms/kernel/elastic_net/elastic_net_training_types.cpp
- examples/cpp/source/elastic_net/elastic_net_dense_batch.cpp
- examples/java/com/intel/daal/examples/elastic_net/ElasticNetDenseBatch.java
- include/algorithms/elastic_net/elastic_net_training_types.h
- lang_interface/java/com/intel/daal/algorithms/elastic_net/TrainParameter.java
- lang_service/java/com/intel/daal/algorithms/elastic_net/train_parameter.cpp
- service/kernel/daal_strings.h
Finalize naming of Elastic Net parameters, it's cherry-pick
> Finalize naming of Elastic Net parameters (#418)

- include/data_management/data/internal/conversion.h
- include/data_management/data/soa_numeric_table.h
- include/data_management/features/defines.h
- service/kernel/data_management/data_conversion.cpp
- service/kernel/data_management/data_conversion_cpu.cpp
- service/kernel/data_management/data_conversion_cpu.h
- service/kernel/data_management/soa_numeric_table.cpp
Fix some comments from the library architect. The main goal is removing raw pointer from SOANT class and using instead it safe wrapped up pointer.
> Fix comments in SOA optimization commit. Remove raw pointer.

- docs/source/dev_guide/algorithms/lasso_elastic_net/elastic-net.rst
> Fixed copyright year

- algorithms/kernel/covariance/covariance_dense_batch_impl.i
- algorithms/kernel/covariance/covariance_dense_online_impl.i
- algorithms/kernel/covariance/covariance_impl.i
Some optimizations for PCA have been done in Correlation
> PCA Optimization for Column-Major Tables

- algorithms/kernel/k_nearest_neighbors/oneapi/bf_knn_classification_predict_kernel_ucapi.h
- algorithms/kernel/k_nearest_neighbors/oneapi/bf_knn_classification_predict_kernel_ucapi_impl.i
- algorithms/kernel/k_nearest_neighbors/oneapi/cl_kernels/bf_knn_cl_kernels.cl
- service/kernel/oneapi/cl_kernels/select_indexed.cl
- service/kernel/oneapi/select_indexed.h
- service/kernel/select_indexed.cpp
-Added KNN dispatching by K
-Added new selection for K <= 32
-Fixed implicit buffer conversion which caused problem for ComputeCpp
> Added knn improvements to releases

- docs/doxygen/doxygen_conf_cpp.txt
- docs/doxygen/doxygen_conf_cpp_examples.txt
- docs/doxygen/doxygen_conf_cpp_web.txt
- docs/doxygen/doxygen_conf_java.txt
- docs/doxygen/doxygen_conf_java_examples.txt
- docs/doxygen/doxygen_conf_java_web.txt
- makefile.ver
Update version in doxygen and makefile to Beta 06
> Update version to Beta 06

- docs/doxygen/doxygen_conf_cpp.txt
- docs/doxygen/doxygen_conf_cpp_examples.txt
- docs/doxygen/doxygen_conf_cpp_web.txt
- docs/doxygen/doxygen_conf_java.txt
- docs/doxygen/doxygen_conf_java_examples.txt
- docs/doxygen/doxygen_conf_java_web.txt
- makefile.ver
Update version in doxygen and makefile to Beta 06
> Update version to Beta 06 at releases

- docs/source/bibliography.rst
- docs/source/conf.py
- docs/source/dev_guide/algorithms/dbscan/computation-batch.rst
- docs/source/dev_guide/algorithms/dbscan/computation-distributed.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/includes/default_result_data_collection.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/includes/default_result_numeric_table.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/includes/input_data_collection.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/includes/input_data_collection_with_exceptions.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/includes/input_numeric_table.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/includes/parameters.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/includes/parameters_blocks.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/includes/parameters_blocks_left_right.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-1.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-10.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-11.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-12.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-13.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-2.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-3.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-4.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-5.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-6.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-7.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-8.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-9.rst
- docs/source/dev_guide/algorithms/dbscan/index.rst
> [releases] DBSCAN docs

- CONTRIBUTING.md
- INSTALL.md
- README.md
- docs/README.md
updating links to repo and gh-pages after migration to new org
> updating links to repo and gh-pages

- CONTRIBUTING.md
- INSTALL.md
- README.md
- docs/README.md
updating links to repo and gh-pages after migration to new org
> updating links to repo and gh-pages (#478)

- docs/source/conf.py
- docs/source/contribution/coding_guide.rst
- docs/source/index.rst
- docs/source/topics/installation.rst
Changed links to oneDAL's GitHub repository in doc sources.
> Update links to github in docs

- docs/source/conf.py
- docs/source/contribution/coding_guide.rst
- docs/source/index.rst
- docs/source/topics/installation.rst
> [releases] Update links to github in docs (#482)

- algorithms/kernel/covariance/covariance_dense_batch_impl.i
- algorithms/kernel/covariance/covariance_dense_online_impl.i
- algorithms/kernel/covariance/covariance_impl.i
Some optimizations for PCA have been done in Correlation
> [releases] PCA Optimization for Column-Major Tables

- algorithms/kernel/covariance/covariance_dense_batch_impl.i
- algorithms/kernel/covariance/covariance_dense_online_impl.i
- algorithms/kernel/covariance/covariance_impl.i
Some optimizations for PCA have been done in Correlation
> [daal-2020-mnt] PCA Optimization for Column-Major Tables

- bin/dal
- bin/dal32
- makefile
> [releases] Added modulefiles support (#480)

- docs/source/topics/build-examples.rst
Check the output [here](https://outoftardis.github.io/daal/getstarted.html#build-and-run-examples).
- added instructions for modulefiles (I've rephrased the content provided, so please check if everything's ok)
- added tabs for Linux/Windows
Targeted for beta06
> Added modulefiles instructions

- docs/source/topics/build-examples.rst
> [releases] Added modulefiles instructions (#485)

- examples/cpp_sycl/makefile_lnx
In this change we update help section in linux example's makefile to correlate with windows case
> update wording in help section

- examples/cpp_sycl/makefile_lnx
- examples/cpp_sycl/makefile_win
* removing computecpp compiler support
> [releases]Removing icc and gnu compiler usage from sycl_examples (#489)

- algorithms/kernel/dbscan/dbscan_container.h
- algorithms/kernel/dbscan/dbscan_dense_default_batch_kernel_ucapi_fpt.cpp
- algorithms/kernel/dbscan/oneapi/cl_kernels/dbscan_cl_kernels.cl
- algorithms/kernel/dbscan/oneapi/dbscan_dense_default_batch_ucapi_impl.i
- algorithms/kernel/dbscan/oneapi/dbscan_kernel_ucapi.h
- examples/cpp_sycl/DAALExamples_sycl.sln
- examples/cpp_sycl/daal_lnx.lst
- examples/cpp_sycl/makefile_lnx
- examples/cpp_sycl/source/dbscan/dbscan_dense_batch.cpp
- examples/cpp_sycl/vcproj/dbscan_dense_batch/dbscan_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/dbscan_dense_batch/dbscan_dense_batch.vcxproj.filters
- examples/cpp_sycl/vcproj/dbscan_dense_batch/dbscan_dense_batch.vcxproj.user
> Added GPU backend for DBSCAN (#481)

- algorithms/kernel/pca/pca_input.cpp
- algorithms/kernel/svd/svd_dense_default_batch_impl.i
- algorithms/kernel/svd/svd_dense_default_distr_step3_impl.i
- algorithms/kernel/svd/svd_dense_default_impl.i
- algorithms/kernel/svd/svd_distr_step3_input.cpp
- algorithms/kernel/svd/svd_input.cpp
- algorithms/kernel/svd/svd_online_partial_result.cpp
Same as: https://github.com/oneapi-src/oneDAL/pull/497
CI (successful):  http://intel-ci.intel.com/ea73fcf3-48aa-f1c5-8568-8cdcd4b723a1
> [releases] Add ability to use PCA with svdDense method if n_observations < n_features

- include/algorithms/stump/stump_classification_model.h
- include/algorithms/stump/stump_classification_predict_types.h
- include/algorithms/stump/stump_classification_training_types.h
- include/algorithms/stump/stump_regression_model.h
- include/algorithms/stump/stump_regression_predict_types.h
- include/algorithms/stump/stump_regression_training_types.h
Fixed incorrectly generated documentation modules for decision stump (classification and regression).
> Fixes for stump documentation

- include/algorithms/stump/stump_classification_model.h
- include/algorithms/stump/stump_classification_predict_types.h
- include/algorithms/stump/stump_classification_training_types.h
- include/algorithms/stump/stump_regression_model.h
- include/algorithms/stump/stump_regression_predict_types.h
- include/algorithms/stump/stump_regression_training_types.h
> [releases] Stump comment fix

- include/algorithms/stump/stump_classification_model.h
- include/algorithms/stump/stump_classification_predict_types.h
- include/algorithms/stump/stump_classification_training_types.h
- include/algorithms/stump/stump_regression_model.h
- include/algorithms/stump/stump_regression_predict_types.h
- include/algorithms/stump/stump_regression_training_types.h
> [mnt] Stump comments fix

- algorithms/kernel/pca/pca_input.cpp
- algorithms/kernel/svd/svd_dense_default_batch_impl.i
- algorithms/kernel/svd/svd_dense_default_distr_step3_impl.i
- algorithms/kernel/svd/svd_dense_default_impl.i
- algorithms/kernel/svd/svd_distr_step3_input.cpp
- algorithms/kernel/svd/svd_input.cpp
- algorithms/kernel/svd/svd_online_partial_result.cpp
Same as: #500 
CI: http://intel-ci.intel.com/ea74c670-912b-f194-9025-8cdcd4b723a1
CI completed with errors due to timeout in Spark samples. Other tests have passed successfully.
> [daal-2020-mnt] Add ability to use PCA with svdDense method if n_observations < n_features

- include/data_management/data_source/data_source_dictionary.h
the same as https://github.com/oneapi-src/oneDAL/pull/394
> Fix msvs2019 build

- scripts/mklfpk.bat
- scripts/mklfpk.sh
> Update mklgpufpk version

- docs/source/dev_guide/algorithms/svd/singular-value-decomposition.rst
> [releases] Docs: Remove the restrictions on input dataset size in SVD algorithm

- scripts/mklfpk.bat
- scripts/mklfpk.sh
> [beta 5] Update mklgpufpk version

- algorithms/kernel/export_win32e.def
fpk_serv_realloc
fpk_serv_print
fpk_serv_exit
to resolve link issues with new fpk
corresponding CI passed
http://intel-ci.intel.com/ea799758-b9dd-f1f0-befb-8cdcd4b723a1
> added following mkl serv functions into export list

- scripts/mklfpk.bat
- scripts/mklfpk.sh
> [releases] Update mklgpufpk version

- scripts/mklfpk.bat
- scripts/mklfpk.sh
> [beta 6] Update mklgpufpk version

- include/algorithms/optimization_solver/coordinate_descent/coordinate_descent_types.h
fix of this mistake helps to place SAGA solver in correct place
> Fix doxygen in CD

- include/algorithms/optimization_solver/coordinate_descent/coordinate_descent_types.h
fix of this mistake helps to place SAGA solver in correct place
> [releases]: Fix doxygen in CD

- include/algorithms/optimization_solver/coordinate_descent/coordinate_descent_types.h
fix of this mistake helps to place SAGA solver in correct place
> [master]: Fix doxygen in CD 

- examples/cpp_sycl/makefile_lnx
- include/oneapi/internal/error_handling.h
- include/oneapi/internal/execution_context_sycl.h
- include/oneapi/internal/kernel_scheduler_sycl.h
- include/services/error_indexes.h
* layer for level 0 support
* fixed wrong formatting
* added error handling routines for level zero errors processing
* fixed formatting
* added define to remove level0 support during build, and addressed some feedbacks
* fixed formatiing
* introduced DAAL_DESABLE_LEVEL_ZERO and added support for skipping Level0 on windows
* last fixes for comments from review
* removed comments and full path to lze_loader
* adress clang-format
* adress copyrights check
* adress copyrights check
Co-authored-by: amaklaev <artem.maklaev@intel.com>
Co-authored-by: Petrov, Nikolay A <nikolay.a.petrov@intel.com>
> [beta06] Added support for level 0 dispatching

- examples/cpp_sycl/makefile_lnx
- include/oneapi/internal/error_handling.h
- include/oneapi/internal/execution_context_sycl.h
- include/oneapi/internal/kernel_scheduler_sycl.h
- include/services/error_indexes.h
* layer for level 0 support
* fixed wrong formatting
* added error handling routines for level zero errors processing
* fixed formatting
* added define to remove level0 support during build, and addressed some feedbacks
* fixed formatiing
* introduced DAAL_DESABLE_LEVEL_ZERO and added support for skipping Level0 on windows
* last fixes for comments from review
* removed comments and full path to lze_loader
* adress clang-format
* adress copyrights check
* adress copyrights check
Co-authored-by: amaklaev <artem.maklaev@intel.com>
Co-authored-by: Petrov, Nikolay A <nikolay.a.petrov@intel.com>
> [releases] Added support for level 0 dispatching

- algorithms/kernel/kernel_function/kernel_function_linear_dense_default_impl.i
- algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_impl.i
Some optimizations for SVM Predict have been done in Kernel Function
> SVM Predict Optimization for Column-Major Tables

- algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_impl.i
> SVM gcc building fix

- algorithms/kernel/kernel_function/kernel_function_linear_dense_default_impl.i
- algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_impl.i
Some optimizations for SVM Predict have been done in Kernel Function
> [mnt] SVM Predict Optimization for Column-Major Tables

- algorithms/kernel/kernel_function/kernel_function_linear_dense_default_impl.i
- algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_impl.i
Some optimizations for SVM have been done in Kernel Function
> [releases] SVM Predict Optimization for Column-Major Tables

- examples/cpp_sycl/vcproj/bf_knn_dense_batch/bf_knn_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/cor_dense_batch/cor_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/cor_dense_online/cor_dense_online.vcxproj
- examples/cpp_sycl/vcproj/datastructures_soa/datastructures_soa.vcxproj
- examples/cpp_sycl/vcproj/datastructures_usm/datastructures_usm.vcxproj
- examples/cpp_sycl/vcproj/dbscan_dense_batch/dbscan_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/gbt_reg_dense_batch/gbt_reg_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/kmeans_dense_batch/kmeans_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/kmeans_init_dense_batch/kmeans_init_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/lin_reg_norm_eq_dense_batch/lin_reg_norm_eq_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/lin_reg_norm_eq_dense_online/lin_reg_norm_eq_dense_online.vcxproj
- examples/cpp_sycl/vcproj/log_reg_binary_dense_batch/log_reg_binary_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/log_reg_dense_batch/log_reg_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/low_order_moms_dense_batch/low_order_moms_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/low_order_moms_dense_online/low_order_moms_dense_online.vcxproj
- examples/cpp_sycl/vcproj/pca_cor_dense_batch/pca_cor_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/pca_transform_dense_batch/pca_transform_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/sgd_mini_log_loss_dense_batch/sgd_mini_log_loss_dense_batch.vcxproj
cherry-pick of https://github.com/oneapi-src/oneDAL/pull/551
> change SDK to exact version to be compatible with msvs2017

- .ci/pipeline/docs.yml
- docs/Makefile
We introduce initial version of doc generation pipeline that will trigger on commits to docs and include directory
Example of job: 
https://dev.azure.com/IPLInfra/nikolayapetrov/_build/results?buildId=22&view=results
> Introduce initial version of doc generation pipeline

- scripts/mklfpk.bat
- scripts/mklfpk.sh
> Update mklgpufpk version to 20200414

- algorithms/kernel/elastic_net/elastic_net_train_dense_default_impl.i
- algorithms/kernel/lasso_regression/lasso_regression_train_dense_default_impl.i
- algorithms/kernel/objective_function/mse/mse_dense_default_batch_impl.i
- algorithms/kernel/objective_function/mse/mse_dense_default_batch_kernel.h
Some optimizations in Lasso, Elastic Net, and MSE kernels for SOA numeric tables
> Lasso and Elastic Net Optimization for Column-Major Tables

- algorithms/kernel/elastic_net/elastic_net_train_dense_default_impl.i
- algorithms/kernel/lasso_regression/lasso_regression_train_dense_default_impl.i
- algorithms/kernel/objective_function/mse/mse_dense_default_batch_impl.i
- algorithms/kernel/objective_function/mse/mse_dense_default_batch_kernel.h
Some optimizations in Lasso, Elastic Net, and MSE kernels for SOA numeric tables
> [releases] Lasso and Elastic Net Optimization for Column-Major Tables

- scripts/mklfpk.bat
- scripts/mklfpk.sh
> [beta06] Update mklgpufpk version to 20200414

- algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_impl.i
> [master] SVM Windows icc180 bug fix

- algorithms/kernel/elastic_net/elastic_net_train_dense_default_impl.i
- algorithms/kernel/lasso_regression/lasso_regression_train_dense_default_impl.i
- algorithms/kernel/objective_function/mse/mse_dense_default_batch_impl.i
Remove unnecessary variables from Elastic Net, Lasso, and MSE
> [master] Remove unnecessary variables

- algorithms/kernel/elastic_net/elastic_net_train_dense_default_impl.i
- algorithms/kernel/lasso_regression/lasso_regression_train_dense_default_impl.i
- algorithms/kernel/objective_function/mse/mse_dense_default_batch_impl.i
Remove unnecessary variables from Elastic Net, Lasso, and MSE
> [mnt] Remove unnecessary variables 

- algorithms/kernel/kernel.h
- service/kernel/compiler/generic/env_detect_features.cpp
- service/kernel/service_defines.h
Purpose of this PR is adding functionality for understanding platform where program is running
1) Change batch container dispatch mechanism
2) Add functionality for platform definition
> Safe dispatcher

- algorithms/kernel/dtrees/forest/oneapi/cl_kernels/df_common_kernels.cl
- algorithms/kernel/dtrees/forest/oneapi/df_feature_type_helper_oneapi.h
- algorithms/kernel/dtrees/forest/oneapi/df_feature_type_helper_oneapi.i
- algorithms/kernel/dtrees/forest/regression/df_regression_predict_dense_default_batch_fpt_dispatcher.cpp
- algorithms/kernel/dtrees/forest/regression/df_regression_train_container.h
- algorithms/kernel/dtrees/forest/regression/df_regression_train_dense_default_batch_oneapi_fpt.cpp
- algorithms/kernel/dtrees/forest/regression/df_regression_train_dense_default_impl.i
- algorithms/kernel/dtrees/forest/regression/df_regression_train_dense_default_kernel.h
- algorithms/kernel/dtrees/forest/regression/df_regression_train_hist_batch_fpt_cpu.cpp
- algorithms/kernel/dtrees/forest/regression/df_regression_train_hist_batch_fpt_dispatcher.cpp
- algorithms/kernel/dtrees/forest/regression/df_regression_train_hist_batch_oneapi_fpt.cpp
- algorithms/kernel/dtrees/forest/regression/oneapi/cl_kernels/df_batch_regression_kernels.cl
- algorithms/kernel/dtrees/forest/regression/oneapi/df_regression_train_dense_default_oneapi_impl.i
- algorithms/kernel/dtrees/forest/regression/oneapi/df_regression_train_hist_kernel_oneapi.h
- algorithms/kernel/dtrees/forest/regression/oneapi/df_regression_train_hist_oneapi_impl.i
- algorithms/kernel/dtrees/forest/regression/oneapi/df_regression_train_kernel_oneapi.h
- algorithms/kernel/dtrees/forest/regression/oneapi/df_regression_tree_helper_impl.i
- examples/cpp_sycl/DAALExamples_sycl.sln
- examples/cpp_sycl/daal_lnx.lst
- examples/cpp_sycl/makefile_lnx
- examples/cpp_sycl/source/decision_forest/df_reg_dense_batch.cpp
- examples/cpp_sycl/vcproj/df_reg_dense_batch/df_reg_dense_batch.filters
- examples/cpp_sycl/vcproj/df_reg_dense_batch/df_reg_dense_batch.user
- examples/cpp_sycl/vcproj/df_reg_dense_batch/df_reg_dense_batch.vcxproj
- include/algorithms/decision_forest/decision_forest_regression_training_types.h
first part of changes:
added same indexed features helper as in gbt with just files' names/namespaces renaming and removed BestSplitOneApi structure.
> added df oneapi indexed features

- algorithms/kernel/kmeans/kmeans_lloyd_batch_impl.i
- algorithms/kernel/kmeans/kmeans_lloyd_distr_step1_impl.i
- algorithms/kernel/kmeans/kmeans_lloyd_helper.h
- algorithms/kernel/kmeans/kmeans_lloyd_impl.i
- algorithms/kernel/kmeans/kmeans_lloyd_postprocessing.h
- service/kernel/service_environment.h
- service/kernel/service_topo.cpp
This request includes block size optimizations for KMeans.
> KMeans block size optimizations have been implemented.

- include/algorithms/kmeans/kmeans_multinode_batch.h
> Fixed issue with unknown identifier for daal4py build (#604)

- include/oneapi/internal/daal_ze_module_helper.h
modified level 0 module destroying process to resolve issues with launching under nmake on windows
> modified level 0 module destroying process

- algorithms/kernel/dtrees/forest/classification/df_classification_train_dense_default_kernel.h
DF: fix extra declaration of compute function
> DF: fix extra declaration of compute function

- .ci/pipeline/ci.yml
- .ci/scripts/conformance-scripts/algorithms.txt
- .ci/scripts/conformance-scripts/download_tests.sh
- .ci/scripts/conformance-scripts/run_tests.py
- .ci/scripts/conformance-scripts/utils.py
- .ci/scripts/conformance_test.sh
- .ci/scripts/daal4py_test.sh
This is automatic conformance tests in public CI
Report of testing is located in artifacts on azure
> [2020-mnt] Add conformance tests in public ci

- algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_impl.i
Merge https://github.com/oneapi-src/oneDAL/pull/614
> Optimize compute RBF Kernel for Matrix to Matrix case

- algorithms/kernel/kernel_function/kernel_function_linear_dense_default_impl.i
- algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_impl.i
- algorithms/kernel/kmeans/kmeans_lloyd_postprocessing.h
- algorithms/kernel/svm/svm_predict_impl.i
- algorithms/kernel/svm/svm_train_boser_impl.i
- algorithms/kernel/svm/svm_train_common_avx512_impl.i
- algorithms/kernel/svm/svm_train_common_impl.i
- algorithms/kernel/svm/svm_train_result.h
- algorithms/kernel/svm/svm_train_thunder_impl.i
- algorithms/kernel/svm/svm_train_thunder_workset.h
- examples/cpp/source/svm/svm_two_class_model_builder.cpp
- externals/service_blas.h
Replace TLS struct on LS struct
> Fix SVM predict not deterministic result & small refactor

- docs/doxygen/doxygen_conf_cpp.txt
- docs/doxygen/doxygen_conf_cpp_examples.txt
- docs/doxygen/doxygen_conf_cpp_web.txt
- docs/doxygen/doxygen_conf_java.txt
- docs/doxygen/doxygen_conf_java_examples.txt
- docs/doxygen/doxygen_conf_java_web.txt
- makefile.ver
> Product version is updated to Beta 8.

- algorithms/kernel/multiclassclassifier/inner/multiclassclassifier_train_batch_container_v1.h
- algorithms/kernel/multiclassclassifier/multiclassclassifier_train_batch_container.h
- algorithms/kernel/multiclassclassifier/multiclassclassifier_train_kernel.h
- algorithms/kernel/multiclassclassifier/multiclassclassifier_train_oneagainstone_impl.i
- algorithms/kernel/multiclassclassifier/multiclassclassifier_train_oneagainstone_kernel.h
- algorithms/kernel/svm/inner/svm_train_batch_container_v1.h
- algorithms/kernel/svm/svm_train_batch_container.h
- algorithms/kernel/svm/svm_train_boser_impl.i
- algorithms/kernel/svm/svm_train_boser_kernel.h
- algorithms/kernel/svm/svm_train_kernel.h
- algorithms/kernel/svm/svm_train_result.h
- algorithms/kernel/svm/svm_train_thunder_impl.i
- algorithms/kernel/svm/svm_train_thunder_kernel.h
- algorithms/kernel/svm/svm_train_thunder_workset.h
In SVC optimization, C parameter changes to C[i], where i is index of sample. Each C[i] is C[i] = C * weight[i].
> Support weights for SVM and Multiclass

- algorithms/kernel/multiclassclassifier/inner/multiclassclassifier_train_batch_container_v1.h
- algorithms/kernel/multiclassclassifier/multiclassclassifier_train_batch_container.h
- algorithms/kernel/multiclassclassifier/multiclassclassifier_train_kernel.h
- algorithms/kernel/multiclassclassifier/multiclassclassifier_train_oneagainstone_impl.i
- algorithms/kernel/multiclassclassifier/multiclassclassifier_train_oneagainstone_kernel.h
- algorithms/kernel/svm/inner/svm_train_batch_container_v1.h
- algorithms/kernel/svm/svm_train_batch_container.h
- algorithms/kernel/svm/svm_train_boser_impl.i
- algorithms/kernel/svm/svm_train_boser_kernel.h
- algorithms/kernel/svm/svm_train_kernel.h
- algorithms/kernel/svm/svm_train_result.h
- algorithms/kernel/svm/svm_train_thunder_impl.i
- algorithms/kernel/svm/svm_train_thunder_kernel.h
- algorithms/kernel/svm/svm_train_thunder_workset.h
merge https://github.com/oneapi-src/oneDAL/pull/635
> [mnt] Support weights for SVM and Multiclass 

- .github/CODEOWNERS
Adding 2 people for docs reviews
> update codeowners for doc review

- .ci/pipeline/ci.yml
- algorithms/kernel/service_hash_table.h
- algorithms/kernel/svm/svm_train_common.h
- algorithms/kernel/svm/svm_train_common_impl.i
- algorithms/kernel/svm/svm_train_result.h
- algorithms/kernel/svm/svm_train_thunder_cache.h
- algorithms/kernel/svm/svm_train_thunder_impl.i
- algorithms/kernel/svm/svm_train_thunder_kernel.h
- algorithms/kernel/svm/svm_train_thunder_workset.h
- include/data_management/data/soa_numeric_table.h
- service/kernel/data_management/service_numeric_table.h
- service/kernel/data_management/soa_numeric_table.cpp
- Implemented simple Hash table
- Implemented LRU cache
- Implemented LRU caching for result of kernel function
> [mnt] LRU cache for thunder method of SVM

- cpp/daal/include/algorithms/decision_forest/decision_forest_regression_training_types.h
- cpp/daal/src/algorithms/dtrees/forest/df_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_training_result.h
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_training_result_fpt.cpp
- examples/daal/cpp/source/decision_forest/df_cls_dense_batch.cpp
Fix performance degradation in DF;
Remove implementation of maxLeafNodes parameter;
Fix in interface
> Fix performance degradation in DF v2

- algorithms/kernel/service_hash_table.h
- algorithms/kernel/svm/svm_train_common.h
- algorithms/kernel/svm/svm_train_common_impl.i
- algorithms/kernel/svm/svm_train_result.h
- algorithms/kernel/svm/svm_train_thunder_cache.h
- algorithms/kernel/svm/svm_train_thunder_impl.i
- algorithms/kernel/svm/svm_train_thunder_kernel.h
- algorithms/kernel/svm/svm_train_thunder_workset.h
- include/data_management/data/soa_numeric_table.h
- service/kernel/data_management/service_numeric_table.h
- service/kernel/data_management/soa_numeric_table.cpp
Cherry-pick https://github.com/oneapi-src/oneDAL/pull/648
> [mnt-rls] LRU cache for thunder method of SVM (#648)

- .ci/pipeline/ci.yml
- .ci/scripts/conformance-scripts/run_tests.py
- .ci/scripts/conformance_test.sh
Logs of pytest was included in artifact, and scikit-learn version was changed to last.
> Add test logs of conformance testing to artifact in public CI

- .ci/pipeline/ci.yml
- .ci/scripts/conformance-scripts/run_tests.py
- .ci/scripts/conformance_test.sh
> [2020-mnt] Add test logs of conformance testing to artifact in public CI

- cpp/daal/include/data_management/data/soa_numeric_table.h
- cpp/daal/src/algorithms/service_hash_table.h
- cpp/daal/src/algorithms/svm/svm_train_common.h
- cpp/daal/src/algorithms/svm/svm_train_common_impl.i
- cpp/daal/src/algorithms/svm/svm_train_result.h
- cpp/daal/src/algorithms/svm/svm_train_thunder_cache.h
- cpp/daal/src/algorithms/svm/svm_train_thunder_impl.i
- cpp/daal/src/algorithms/svm/svm_train_thunder_kernel.h
- cpp/daal/src/algorithms/svm/svm_train_thunder_workset.h
- cpp/daal/src/data_management/service_numeric_table.h
- cpp/daal/src/data_management/soa_numeric_table.cpp
1. Implemented simple hash table
2. Implemented LRU cache 
3. Implemented LRU caching for result of kernel function  
4. Replace sort to heap in select working set
> LRU cache for thunder method of SVM

- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_training_result.h
DF: fix recursion in allocation
> DF: fix recursion in allocation

- cpp/oneapi/dal/.clang-format
- cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel.hpp
- cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_cov.cpp
- cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_svd.cpp
- cpp/oneapi/dal/algo/pca/backend/gpu/train_kernel.hpp
- cpp/oneapi/dal/algo/pca/backend/gpu/train_kernel_cov.cpp
- cpp/oneapi/dal/algo/pca/backend/gpu/train_kernel_svd.cpp
- cpp/oneapi/dal/algo/pca/common.cpp
- cpp/oneapi/dal/algo/pca/common.hpp
- cpp/oneapi/dal/algo/pca/detail/train_ops.cpp
- cpp/oneapi/dal/algo/pca/detail/train_ops.hpp
- cpp/oneapi/dal/algo/pca/detail/train_ops_dp.cpp
- cpp/oneapi/dal/algo/pca/train.hpp
- cpp/oneapi/dal/algo/pca/train_types.cpp
- cpp/oneapi/dal/algo/pca/train_types.hpp
- cpp/oneapi/dal/backend/dispatcher.hpp
- cpp/oneapi/dal/backend/dispatcher_dp.hpp
- cpp/oneapi/dal/backend/interop/common.hpp
- cpp/oneapi/dal/backend/interop/data_conversion.hpp
- cpp/oneapi/dal/backend/interop/table_conversion.hpp
- cpp/oneapi/dal/common.hpp
- cpp/oneapi/dal/data_parallel.hpp
- cpp/oneapi/dal/detail/common_helpers.hpp
- cpp/oneapi/dal/detail/train_ops.hpp
- cpp/oneapi/dal/execution_context.cpp
- cpp/oneapi/dal/execution_context.hpp
- cpp/oneapi/dal/util/detail/type_traits.hpp
- cpp/oneapi/dal/util/type_traits.hpp
Don't changes folder:
- data
- examples
> Clang-format for new interfaces

- cpp/oneapi/dal/common.hpp
- cpp/oneapi/dal/data/backend/empty_table_impl.hpp
- cpp/oneapi/dal/data/backend/homogen_table_impl.cpp
- cpp/oneapi/dal/data/backend/homogen_table_impl.hpp
- cpp/oneapi/dal/data/common_helpers.hpp
- cpp/oneapi/dal/data/detail/table_impl_iface.hpp
- cpp/oneapi/dal/data/detail/table_impl_wrapper.hpp
- cpp/oneapi/dal/data/table.cpp
- cpp/oneapi/dal/data/table.hpp
- cpp/oneapi/dal/data/table_builder.cpp
- cpp/oneapi/dal/data/table_builder.hpp
- cpp/oneapi/dal/data/table_builder_test.cpp
- cpp/oneapi/dal/data/table_metadata.cpp
- cpp/oneapi/dal/data/table_metadata.hpp
- cpp/oneapi/dal/data/table_test.cpp
- cpp/oneapi/dal/detail/common_helpers.hpp
- cpp/oneapi/dal/util/type_traits.hpp
This PR contains improvements of table metadata concept implementation
> [oneDAL interface] Table metadata

- makefile
> tbb update preparations

- cpp/daal/src/algorithms/kmeans/oneapi/cl_kernels/kmeans_cl_kernels.cl
- cpp/daal/src/algorithms/kmeans/oneapi/kmeans_dense_lloyd_batch_kernel_ucapi.h
- cpp/daal/src/algorithms/kmeans/oneapi/kmeans_dense_lloyd_batch_kernel_ucapi_impl.i
Optimization of bath K-Means algorithm
- Initialization of a distance matrix for GEMM was removed; affected kernels were updated
- Workflow was reworked to compute the best candidates to fill empty clusters only in case it is really necessary
- Refactoring was done
> Batch K-Means optimization

- cpp/daal/include/sycl/internal/math/mkl_lapack.h
Changes in API happened and adapters should be modified respectively
> Fixes for potrf and potrs API incompatibility

- cpp/daal/include/services/error_handling.h
- cpp/daal/include/services/error_indexes.h
- cpp/daal/include/services/internal/status_to_error_id.h
- cpp/daal/src/services/error_handling.cpp
- cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_cov.cpp
- cpp/oneapi/dal/backend/interop/error_converter.hpp
- cpp/oneapi/dal/exceptions.cpp
- cpp/oneapi/dal/exceptions.hpp
> oneDAL error handling impl

- cpp/daal/include/sycl/internal/communicator_oneccl_sycl.h
- samples/daal/cpp/oneccl/sources/kmeans_dense_multinode_batch.cpp
ccl_steam_sycl identifier was removed from oneCCL in the latest release
> Changed ccl stream type from sycl to cpu

- cpp/daal/src/algorithms/kmeans/oneapi/kmeans_dense_lloyd_batch_kernel_ucapi_impl.i
> Fixed warning on NULL in KMeans

- cpp/oneapi/dal/algo/decision_forest/backend/cpu/infer_kernel_classification_dense.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/cpu/infer_kernel_regression_dense.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_classification_dense.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_regression_dense.cpp
- cpp/oneapi/dal/algo/decision_forest/detail/infer_ops.hpp
- cpp/oneapi/dal/algo/decision_forest/detail/train_ops.hpp
added minimal error handling for RF new interfaces
> added minimal error handling for RF new interfaces

- examples/oneapi/dpc/source/knn/knn_cls_brute_force_dense_batch.cpp
- examples/oneapi/dpc/source/linear_kernel/linear_kernel_dense_batch.cpp
- examples/oneapi/dpc/source/pca/pca_cor_dense_batch.cpp
- examples/oneapi/dpc/source/tables/homogen_table_builder.cpp
> Added output of device name to dpc examples

- cpp/daal/src/algorithms/kmeans/oneapi/kmeans_dense_lloyd_batch_kernel_ucapi_impl.i
> Removed NULLs in GPU K-Means

- cpp/daal/src/threading/service_thread_pinner.cpp
- samples/daal/java/hadoop/launcher.sh
- samples/daal/java/spark/launcher.sh
- samples/daal/scala/spark/launcher.sh
Tbb changed .so files.
Appended checker of their naming.
> fix of spark and hadoop launcher scripts

- cpp/daal/src/threading/service_thread_pinner.cpp
- samples/daal/java/hadoop/launcher.sh
- samples/daal/java/spark/launcher.sh
- samples/daal/scala/spark/launcher.sh
* fix of spark and hadoop launcher scripts
* remove tbb deprecated header
Co-authored-by: konstantin.nektyagaev @teabagk7
> Removing old tbb dependencies 

- examples/daal/cpp/makefile_win
- examples/daal/cpp_sycl/makefile_win
- examples/oneapi/cpp/makefile_win
> [RELEASES] Fix nmake issue

- cpp/oneapi/dal/algo/pca/common.cpp
- cpp/oneapi/dal/algo/pca/detail/train_ops.hpp
> [RELEASES] oneAPI PCA error handling (#733)

- makefile
*appended tbb libs to fix java examples/samples
> [beta08] TBB libs fix for java

- makefile
cherry-pick #743 
*appended tbb libs to fix java examples/samples
> [beta08] TBB libs fix for java  (#743)

- makefile
> [BETA08] Turn off TBB ASSERTS (#747)

- examples/daal/cpp/makefile_win
- examples/daal/cpp_sycl/daal_win.vcxproj.tpl
- examples/daal/cpp_sycl/makefile_win
> Fix missing dependency on TBB on Windows

- cpp/daal/src/externals/service_math_mkl.h
- cpp/daal/src/externals/service_stat_rng_mkl.h
- samples/daal/java/hadoop/launcher.sh
- samples/daal/java/spark/launcher.sh
- samples/daal/scala/spark/launcher.sh
> [beta08] instructions sets fix for mac32e (#753)

- examples/daal/cpp/makefile_win
- examples/daal/cpp_sycl/daal_win.vcxproj.tpl
- examples/daal/cpp_sycl/makefile_win
Update windows examples to use tbb deps
> Attempt to fix tbb deps (#755)

- makefile
Changes to turn off tbb assert mode.
> [BETA08] Turn off TBB ASSERTS

- cpp/daal/include/data_management/data/internal/train_test_split.h
- cpp/daal/src/data_management/train_test_split.cpp
- cpp/daal/src/externals/service_rng.h
- cpp/daal/src/externals/service_rng_mkl.h
Optimization of indices shuffling for scikit-learn train_test_split function.
> Optimization for train_test_split indices shuffling

- algorithms/kernel/dbscan/dbscan_dense_default_batch_impl.i
- algorithms/kernel/dbscan/dbscan_kernel.h
- algorithms/kernel/dbscan/dbscan_utils.h
- algorithms/kernel/k_nearest_neighbors/kdtree_knn_impl.i
- algorithms/kernel/service_kernel_math.h
- service/kernel/service_defines.h
Duplicate of https://github.com/oneapi-src/oneDAL/pull/707 and https://github.com/oneapi-src/oneDAL/pull/727
> DBSCAN optimizations (mnt)

- docs/source/_static/style.css
- docs/source/notes/issues/2021.1-beta08/windows-static-debug-config.rst
- docs/source/notes/known_issues.rst
Updated known issues for beta08,
> [DOC] Updated known issues for beta08,

- docs/doxygen/custom/intel_doxygen.css
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/oneapi-src/onedal/file/master/docs/doxygen/custom/intel_doxygen.css).
> Apply fixes from CodeFactor

- dev/download_micromkl.sh
- dev/download_tbb.sh
- samples/daal/java/hadoop/launcher.sh
- samples/daal/java/spark/launcher.sh
- samples/daal/scala/spark/launcher.sh
fixing cppcheck oneMKL and oneTBB download scripts
> fixing cppcheck oneMKL/oneTBB download scripts and launcher scripts for hadoop/spark/scala

- .ci/env/clang.sh
- .ci/scripts/clang-format.sh
- examples/daal/java/launcher_fbsd.sh
- examples/daal/java/launcher_lnx.sh
- examples/daal/java/launcher_mac.sh
Cleaning bash code miss use in scripts
> Code cleanup for scripts

- algorithms/threading/threading.cpp
- algorithms/threading/threading.h
- externals/core_threading_win_dll.cpp
- service/kernel/data_management/finiteness_checker.cpp
Modifications for heterogeneous SOA in Finite Check
> [mnt] Removing conversions for SOA tables in Finite Check

- .ci/pipeline/ci.yml
- .ci/scripts/conformance-scripts/run_tests.py
- .ci/scripts/conformance_test.sh
- deploy/local/generate_win_makefile.py
- docs/source/conf.py
Cleaning pylint warnings in code
> cleaning python code

- examples/daal/cpp/daal_win.sln.tpl
- examples/daal/cpp/daal_win.vcxproj.tpl
- examples/daal/cpp/daal_win.vcxproj.user.tpl
- examples/daal/cpp/makefile_fbsd
- examples/daal/cpp/makefile_lnx
- examples/daal/cpp/makefile_win
- examples/daal/java/launcher.bat
- examples/daal/java/launcher_fbsd.sh
- examples/daal/java/launcher_lnx.sh
- samples/daal/cpp/kdb/launcher.bat
- samples/daal/cpp/kdb/makefile_lnx
- samples/daal/cpp/kdb/makefile_mac
- samples/daal/cpp/mpi/launcher.bat
- samples/daal/cpp/mpi/makefile_lnx
- samples/daal/cpp/mysql/launcher.bat
- samples/daal/cpp/mysql/makefile_lnx
- samples/daal/cpp/mysql/makefile_mac
- samples/daal/cpp/oneccl/makefile_lnx
- samples/daal/java/hadoop/launcher.sh
- samples/daal/java/spark/launcher.sh
- samples/daal/scala/spark/launcher.sh
In this PR we are removing all 32-bit mentions in examples and samples
> 32-bit support removal from examples/samples

- cpp/daal/src/data_management/finiteness_checker.cpp
Default case added to the switch in Finite Check
> [master] Default case in Finite Check

- service/kernel/data_management/finiteness_checker.cpp
Default case added to the switch in Finite Check
> [mnt] Default case in Finite Check

- cpp/daal/include/algorithms/boosting/adaboost_model.h
- cpp/daal/include/algorithms/boosting/brownboost_model.h
- cpp/daal/include/sycl/internal/daal_level_zero_types.h
- cpp/daal/src/services/compression/compression_stream.cpp
- cpp/daal/src/services/compression/rlecompression.cpp
- cpp/daal/src/services/service_topo.h
- examples/daal/cpp/source/utils/service.h
- examples/daal/cpp_sycl/source/utils/service.h
- examples/daal/java/com/intel/daal/examples/datasource/DataStructuresHomogen.java
- java/com/intel/daal/data_management/data/java_csr_numeric_table.h
- samples/daal/java/hadoop/sources/KmeansCSR.java
- samples/daal/java/hadoop/sources/KmeansDense.java
- samples/daal/scala/spark/sources/KMeans.scala
- samples/daal/scala/spark/sources/LinearRegression.scala
- samples/daal/scala/spark/sources/PCA.scala
- samples/daal/scala/spark/sources/SampleLinearRegression.scala
In this change we are cleaning up following code
- scala samples
- CPP code from redundant blank lines
- java code from empty statements
> Code style cleanup

- deploy/local/vars_fbsd.sh
- deploy/local/vars_lnx.sh
- deploy/local/vars_mac.sh
- Cleaning remains of arch support from env scripts 
- Enable zsh support 
- Unify shell based env scripts
- Fixes https://github.com/oneapi-src/oneDAL/issues/243
> Cleaning up env scripts to support zsh

- cpp/daal/include/algorithms/decision_forest/decision_forest_training_parameter.h
- cpp/daal/src/algorithms/dtrees/forest/df_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/df_training_parameter.cpp
- cpp/daal/src/services/daal_strings.h
> Best-first search

- algorithms/kernel/svm/svm_train_thunder_cache.h
Merge change from https://github.com/oneapi-src/oneDAL/pull/835
> [mnt] Reduce of calls memory allocate for cache in SVM

- cpp/oneapi/dal/io/csv/backend/cpu/read_kernel.cpp
- cpp/oneapi/dal/io/csv/backend/gpu/read_kernel_dpc.cpp
Added proper check for file open error.
> Improved csv reader error handling

- docs/doxygen/custom/intel_doxygen.css
> Fixing CSS style code problems

- INSTALL.md
- docs/source/conf.py
- docs/source/notes/issues/2021.1-beta06/includes/note-refer-to-dpcpp-level-zero.rst
- docs/source/notes/issues/2021.1-beta06/incorrect-linker-behavior.rst
- docs/source/notes/known_issues.rst
- docs/source/topics/build-examples.rst
- docs/source/topics/prerequisites.rst
Updated the naming and the links to Compiler docs.
> [DOC] Updated oneAPI DPC++ Compiler name

- examples/daal/java/com/intel/daal/examples/decision_forest/DfClsDenseBatch.java
- examples/daal/java/com/intel/daal/examples/decision_forest/DfClsTraversedModelBuilder.java
- java/com/intel/daal/algorithms/decision_forest/classification/train_types.cpp
- java/com/intel/daal/algorithms/decision_forest/classification/training/Parameter.java
- java/com/intel/daal/algorithms/decision_forest/regression/train_types.cpp
- java/com/intel/daal/algorithms/decision_forest/regression/training/Parameter.java
New parameters was added in cpp part of code in PR #533 and #681
> Desicion Forest: add new parameters for java interfaces

- examples/java/com/intel/daal/examples/decision_forest/DfClsDenseBatch.java
- examples/java/com/intel/daal/examples/decision_forest/DfClsTraversedModelBuilder.java
- lang_interface/java/com/intel/daal/algorithms/decision_forest/classification/training/Parameter.java
- lang_interface/java/com/intel/daal/algorithms/decision_forest/regression/training/Parameter.java
- lang_service/java/com/intel/daal/algorithms/decision_forest/classification/train_types.cpp
- lang_service/java/com/intel/daal/algorithms/decision_forest/regression/train_types.cpp
New parameters was added in cpp part of code in PR #897 
This is cherry-pick of PR #910
> [2020-mnt] Desicion Forest: add new parameters for java interfaces

- cpp/daal/include/algorithms/decision_forest/decision_forest_regression_training_types.h
- cpp/daal/src/algorithms/dtrees/dtrees_train_data_helper.i
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_container.h
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_dense_default_kernel.h
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_kernel.h
- cpp/daal/src/algorithms/dtrees/forest/classification/inner/df_classification_train_container_v1.h
- cpp/daal/src/algorithms/dtrees/forest/classification/inner/df_classification_train_container_v2.h
- cpp/daal/src/algorithms/dtrees/forest/df_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_container.h
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_dense_default_kernel.h
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_kernel.h
- cpp/daal/src/algorithms/dtrees/forest/regression/inner/df_regression_train_container_v1.h
- cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_classification_dense.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_regression_dense.cpp
Draft of adding weights in split part in classification & regression
> Decision Forest: add sample weights

- algorithms/kernel/dtrees/dtrees_train_data_helper.i
- algorithms/kernel/dtrees/forest/classification/df_classification_train_container.h
- algorithms/kernel/dtrees/forest/classification/df_classification_train_dense_default_impl.i
- algorithms/kernel/dtrees/forest/classification/df_classification_train_kernel.h
- algorithms/kernel/dtrees/forest/classification/inner/df_classification_train_container_v1.h
- algorithms/kernel/dtrees/forest/classification/inner/df_classification_train_container_v2.h
- algorithms/kernel/dtrees/forest/df_train_dense_default_impl.i
- algorithms/kernel/dtrees/forest/regression/df_regression_train_container.h
- algorithms/kernel/dtrees/forest/regression/df_regression_train_dense_default_impl.i
- algorithms/kernel/dtrees/forest/regression/df_regression_train_kernel.h
- algorithms/kernel/dtrees/forest/regression/inner/df_regression_train_container_v1.h
- include/algorithms/decision_forest/decision_forest_regression_training_types.h
This PR is the cherry-pick of #857
> [2020-mnt] Decision Forest: add sample weights

- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_classification_predict_dense_default_batch_fpt_dispatcher.cpp
Fix of the constructor which affected cloning of the algorithm
> Brute-Force kNN Constructor's Fix

- algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_impl.i
- algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_kernel.h
- algorithms/kernel/svm/svm_predict_impl.i
- algorithms/kernel/svm/svm_train_thunder_cache.h
- algorithms/kernel/svm/svm_train_thunder_impl.i
- algorithms/kernel/svm/svm_train_thunder_kernel.h
Merge from https://github.com/oneapi-src/oneDAL/pull/921
> [mnt][Part2] Optimize rbf & linear kernel for SOA table result 

- algorithms/kernel/dtrees/forest/regression/df_regression_train_dense_default_impl.i
> Decision Forest: fix bug for vs2017

- .mergify.yml
Updating mergify config with new rules
- Delete merged branches from renovate
- Assign napetrov as reviewer for renovate PRs
> Updating mergify config with new rules

- algorithms/kernel/dtrees/forest/classification/df_classification_train_dense_default_impl.i
- algorithms/kernel/dtrees/forest/regression/df_regression_train_dense_default_impl.i
Classification:
- Airline - 1.33x
- Higgs - 1.26x
Regression average - 1.1x
> RF minor performance optimizations

- cpp/daal/include/algorithms/k_nearest_neighbors/bf_knn_classification_model.h
- examples/daal/cpp/daal_fbsd.lst
- examples/daal/cpp/daal_lnx.lst
- examples/daal/cpp/daal_mac.lst
- examples/daal/cpp/source/k_nearest_neighbors/bf_knn_dense_batch.cpp
BF kNN doxygen and example fixes
> BF kNN doxygen and example fixes

- cpp/oneapi/dal/algo/knn/backend/gpu/train_kernel_brute_force_dpc.cpp
- cpp/oneapi/dal/backend/interop/error_converter.cpp
- cpp/oneapi/dal/exceptions.cpp
- cpp/oneapi/dal/exceptions.hpp
- cpp/oneapi/dal/io/detail/load_graph.hpp
- unimplemented_error -> unimplemented
- erase unavailable_error
- add unsupported_device
- add host_bad_alloc & device_bad_alloc
> Conformance between spec and API: error hadnling

- docs/source/dev_guide/algorithms/kmeans/k-means-clustering.rst
> Added a note to K-Means documentation

- algorithms/kernel/k_nearest_neighbors/bf_knn_impl.i
- algorithms/kernel/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch.h
- algorithms/kernel/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch_impl.i
- examples/cpp/source/k_nearest_neighbors/kdtree_knn_dense_batch.cpp
- examples/java/com/intel/daal/examples/knn_classification/KDTreeKNNDenseBatch.java
Fix class voting for brute force and kdtree methods of k-Nearest Neighbors
> [2020-u3-rls] Fix class voting for kNN

- cpp/daal/include/services/library_version_info.h
- makefile.ver
Product status is missed in header definition now
> Enable PRODUCT_STATUS update for headers version

- docs/source/dev_guide/algorithms/k_nearest_neighbors/k-nearest-neighbors-knn-classifier.rst
- docs/source/dev_guide/algorithms/kmeans/k-means-clustering.rst
- Fixed a broken link in knn
- Added links to dpc++ examples for kmeans
> [DOC] Updated links to examples

- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_impl.i
- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch.h
- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch_impl.i
- examples/daal/cpp/source/k_nearest_neighbors/kdtree_knn_dense_batch.cpp
- examples/daal/java/com/intel/daal/examples/knn_classification/KDTreeKNNDenseBatch.java
Duplicate of https://github.com/oneapi-src/oneDAL/pull/962
> [master] kNN Class voting and examples fix

- cpp/daal/src/algorithms/k_nearest_neighbors/oneapi/bf_knn_classification_model_ucapi_impl.h
`nFeatures` added to brute force kNN serialization
> Brute Force kNN Serialization Fix

- cpp/daal/src/algorithms/k_nearest_neighbors/oneapi/bf_knn_classification_model_ucapi_impl.h
> [2021-mnt] Brute Force kNN Serialization Fix

- examples/oneapi/cpp/source/jaccard/jaccard_batch_app.cpp
> fixed clear code

- docs/source/_static/style.css
- docs/source/contribution/coding_guide.rst
- docs/source/cpu-vs-gpu.rst
- docs/source/dev_guide/algorithms/normalization/z-score.rst
- docs/source/dev_guide/usage/algorithms.rst
- docs/source/dev_guide/usage/computation-modes.rst
- Small fixes in wording.
- Fix in css for coding guidelines
> [DOC] Fixed wording in docs

- cpp/daal/src/algorithms/elastic_net/elastic_net_train_dense_default_impl.i
- cpp/daal/src/algorithms/kernel_function/kernel_function_rbf_dense_default_impl.i
- cpp/daal/src/algorithms/logistic_regression/oneapi/logistic_regression_predict_dense_default_batch_oneapi_impl.i
- cpp/daal/src/algorithms/logistic_regression/oneapi/logistic_regression_train_dense_default_oneapi_impl.i
- cpp/daal/src/algorithms/svm/inner/svm_train_batch_container_v1.h
- cpp/daal/src/algorithms/svm/inner/svm_train_boser_batch_fpt_cpu_v1.cpp
- cpp/daal/src/algorithms/svm/oneapi/svm_helper_oneapi.h
- cpp/daal/src/algorithms/svm/oneapi/svm_predict_oneapi_impl.i
- cpp/daal/src/algorithms/svm/oneapi/svm_train_thunder_kernel_oneapi.h
- cpp/daal/src/algorithms/svm/oneapi/svm_train_thunder_oneapi_impl.i
- cpp/daal/src/algorithms/svm/oneapi/svm_train_workset_oneapi.h
- cpp/daal/src/algorithms/svm/svm_train_batch_container.h
- cpp/daal/src/algorithms/svm/svm_train_boser_batch_fpt_cpu.cpp
- cpp/daal/src/algorithms/svm/svm_train_boser_impl.i
- cpp/daal/src/algorithms/svm/svm_train_boser_kernel.h
- cpp/daal/src/algorithms/svm/svm_train_kernel.h
- cpp/daal/src/algorithms/svm/svm_train_result.h
- cpp/daal/src/algorithms/svm/svm_train_thunder_batch_fpt_cpu.cpp
- cpp/daal/src/algorithms/svm/svm_train_thunder_batch_oneapi_fpt.cpp
- cpp/daal/src/algorithms/svm/svm_train_thunder_impl.i
- cpp/daal/src/algorithms/svm/svm_train_thunder_kernel.h
- cpp/daal/src/externals/service_blas.h
- cpp/oneapi/dal/algo/svm/backend/cpu/train_kernel.cpp
- cpp/oneapi/dal/algo/svm/backend/gpu/train_kernel_thunder_dpc.cpp
- examples/daal/cpp_sycl/source/svm/svm_two_class_thunder_dense_batch.cpp
- examples/oneapi/cpp/source/svm/svm_two_class_smo_dense_batch.cpp
- examples/oneapi/cpp/source/svm/svm_two_class_thunder_dense_batch.cpp
- examples/oneapi/dpc/source/svm/svm_two_class_thunder_dense_batch.cpp
Clean code for thunder SVM on CPU and GPU
> Clean code for SVM

- cpp/daal/src/algorithms/dtrees/gbt/classification/gbt_classification_predict_dense_default_batch_impl.i
Fix for bug which was reported in #1002.
Same bug as #271. Was fixed by @ShvetsKS in #294.
> Fix for GBT cls prediction with mismatched types(like PR#294)

- cpp/daal/include/algorithms/covariance/covariance_distributed.h
- cpp/daal/src/algorithms/covariance/covariance_container.h
- cpp/daal/src/algorithms/covariance/covariance_dense_default_distr_step2_oneapi_fpt.cpp
- cpp/daal/src/algorithms/covariance/oneapi/covariance_dense_distr_step2_oneapi.h
- cpp/daal/src/algorithms/covariance/oneapi/covariance_dense_distr_step2_oneapi_impl.i
- examples/daal/cpp_sycl/daal_lnx.lst
- examples/daal/cpp_sycl/source/covariance/cor_dense_distr.cpp
> oneAPI multi-node covariance

- cpp/oneapi/dal/algo/kmeans_init/detail/compute_ops.hpp
> fix kmeans_init pre- and post- conditions

- cpp/oneapi/dal/algo/kmeans/detail/infer_ops.hpp
- cpp/oneapi/dal/algo/kmeans/detail/train_ops.hpp
> fix kmeans pre- and post- conditions

- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_classification_model_impl.cpp
- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_classification_predict_batch.cpp
- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_classification_training_input.cpp
- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_impl.i
- cpp/daal/src/data_management/finiteness_checker.cpp
- cpp/daal/src/data_management/train_test_split.cpp
Additional parameter and integer overflow checks in Brute Force k-Nearest Neighbors, NaN/Inf checker and train_test_split
> Additional checks in BF kNN, NaN/Inf checker and train_test_split

- examples/daal/cpp_sycl/daal_win.sln.tpl
- examples/daal/cpp_sycl/daal_win.vcxproj.tpl
- examples/daal/cpp_sycl/daal_win.vcxproj.user.tpl
- examples/daal/cpp_sycl/makefile_win
Removing support of static configuration from sycl examples
> Remove static configuration for sycl_examples

- docs/source/dev_guide/algorithms/logistic_regression/logistic-regression.rst
- docs/source/dev_guide/algorithms/svm_multi_class/multi-class-classifier.rst
- Added resultsToEvaluate parameter and output section to multiclass classifier
- Aligned markup for logistic regression and multiclass classifier
> [DOC] Updated docs for multiclass

- cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_avx2.hpp
- cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_scalar.hpp
- cpp/oneapi/dal/algo/jaccard/vertex_similarity_types.hpp
- examples/oneapi/cpp/source/example_util/output_helpers.hpp
- examples/oneapi/cpp/source/example_util/output_helpers_graph.hpp
- examples/oneapi/cpp/source/jaccard/jaccard_batch.cpp
> Jaccard result is in a column major format

- cpp/daal/src/externals/core_threading_win_dll.cpp
- Fix regression in dynamic DLL loading
> Fix DLL loading on windows

- docs/source/dev_guide/algorithms/k_nearest_neighbors/k-nearest-neighbors-knn-classifier.rst
> [DOC] Updated knn docs

- cpp/daal/src/algorithms/dbscan/oneapi/dbscan_dense_default_batch_ucapi_impl.i
- Fix incorrect auto merge caused by
> Fix incorrect status pointer in DBSCAN

- cpp/daal/include/services/error_indexes.h
- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_train_dense_default_impl.i
- cpp/daal/src/services/error_handling.cpp
Error handling for case then median does not split data at all
> Error handling for case then median does not split data at all

- docs/source/bibliography.rst
- docs/source/dev_guide/algorithms/engines/mt2203.rst
- docs/source/dev_guide/algorithms/implicit_als/implicit-alternating-least-squares.rst
- docs/source/dev_guide/algorithms/kernel_function/kernel-functions.rst
- docs/source/dev_guide/algorithms/lasso_elastic_net/lasso.rst
- docs/source/dev_guide/algorithms/linear_ridge_regression/linear-regression.rst
- docs/source/dev_guide/algorithms/logistic_regression/logistic-regression.rst
- docs/source/dev_guide/algorithms/optimization-solvers/solvers/limited-memory-broyden-fletcher-goldfarb-shanno-algorithm.rst
- docs/source/dev_guide/algorithms/svm/support-vector-machine-classifier.rst
- docs/source/topics/build-examples.rst
- Replaced Unicode character "‖" with "\\|"
- Replaced sphinx prompts with code-blocks (needed for Intel website output)
- Fixed bibliography references
> [DOC] Updated docs: small fixes

- examples/daal/cpp_sycl/daal_win.sln.tpl
- examples/daal/cpp_sycl/daal_win.vcxproj.tpl
- examples/daal/cpp_sycl/daal_win.vcxproj.user.tpl
- examples/daal/cpp_sycl/makefile_lnx
- examples/daal/cpp_sycl/makefile_win
- examples/oneapi/dpc/makefile_lnx
remove sequential support from male examples and win solution
> Remove sequential support from DPC++ examples

- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/df_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/df_training_parameter.cpp
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_dense_default_impl.i
cherry-pick from https://github.com/oneapi-src/oneDAL/pull/1014
> Decision Forest: fix gaps (#1014)

- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_classification_model_impl.cpp
- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_classification_predict_batch.cpp
- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_classification_train_dense_default_batch_fpt_dispatcher.cpp
- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_classification_training_input.cpp
- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_impl.i
- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_model_impl.h
- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch.h
- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch_impl.i
- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_predict_result.h
- cpp/daal/src/algorithms/k_nearest_neighbors/knn_heap.h
> kNN bf opts 

- cpp/daal/src/algorithms/covariance/oneapi/cl_kernels/covariance_kernels.cl
- cpp/daal/src/algorithms/covariance/oneapi/covariance_dense_batch_oneapi_impl.i
- cpp/daal/src/algorithms/covariance/oneapi/covariance_dense_online_oneapi_impl.i
- cpp/daal/src/algorithms/covariance/oneapi/covariance_oneapi_impl.i
> [RELEASES] Cov online & batch missed checks (#1085)

- cpp/daal/src/algorithms/pca/oneapi/cl_kernels/pca_cl_kernels.cl
- cpp/daal/src/algorithms/pca/oneapi/pca_dense_correlation_batch_kernel_ucapi_impl.i
- cpp/daal/src/algorithms/pca/oneapi/pca_dense_correlation_online_kernel_ucapi_impl.i
- cpp/daal/src/algorithms/pca/transform/oneapi/cl_kernels/pca_transform_cl_kernels.cl
- cpp/daal/src/algorithms/pca/transform/oneapi/pca_transform_dense_default_batch_oneapi.h
- cpp/daal/src/algorithms/pca/transform/oneapi/pca_transform_dense_default_batch_oneapi_impl.i
> PCA missed checks

- cpp/daal/src/algorithms/logistic_regression/logistic_regression_predict_dense_default_batch_impl.i
- cpp/daal/src/algorithms/objective_function/cross_entropy_loss/cross_entropy_loss_dense_default_batch_impl.i
- cpp/daal/src/algorithms/objective_function/cross_entropy_loss/cross_entropy_loss_dense_default_batch_kernel.h
- cpp/daal/src/algorithms/objective_function/logistic_loss/logistic_loss_dense_default_batch_impl.i
- cpp/daal/src/algorithms/objective_function/logistic_loss/logistic_loss_dense_default_batch_kernel.h
- cpp/daal/src/services/service_data_utils.h
This changes improve cache locality for LogLoss & Cross Entropy calculation
> Optimizations for LogLoss & Cross Entropy

- examples/daal/cpp_sycl/daal_win.sln.tpl
- examples/daal/cpp_sycl/daal_win.vcxproj.tpl
- examples/daal/cpp_sycl/daal_win.vcxproj.user.tpl
- examples/oneapi/dpc/onedal_win.sln.tpl
- examples/oneapi/dpc/onedal_win.vcxproj.tpl
- examples/oneapi/dpc/onedal_win.vcxproj.user.tpl
Remove debug case from examples on Windows for DPC++
> Remove debug examples for DPCPP

- cpp/daal/include/services/daal_defines.h
- cpp/daal/src/algorithms/logistic_regression/oneapi/cl_kernel/logistic_regression_dense_default.cl
- cpp/daal/src/algorithms/logistic_regression/oneapi/logistic_regression_predict_dense_default_batch_oneapi_impl.i
- cpp/daal/src/algorithms/logistic_regression/oneapi/logistic_regression_train_dense_default_oneapi_impl.i
This PR does not include solvers and loss functions
> Safety checks: Logistic regression

- .ci/scripts/conformance-scripts/utils.py
Align name change with https://github.com/IntelPython/daal4py/pull/357
> align mesage with daal4py change

- cpp/oneapi/dal/io/detail/load_graph.hpp
No segmentation fault for work with big graphs.
> Load graph bug fix

- docs/source/dev_guide/algorithms/decision_forest/decision-forest-classification.rst
- docs/source/dev_guide/algorithms/decision_forest/decision-forest-regression.rst
- docs/source/dev_guide/algorithms/decision_forest/decision-forest.rst
- docs/source/dev_guide/algorithms/decision_forest/index.rst
- Updated decision forest chapter with the input
Screenshots:
- index:
- termination criteria:
- tree building strategies:
- Regression details:
- Classification details:
> [DOC] Updated decision forest chapter

- deploy/local/dal
- deploy/local/vars_fbsd.sh
- deploy/local/vars_lnx.sh
- deploy/local/vars_mac.sh
- deploy/local/vars_win.bat
Adding DALROOT variable
Adding Major and Minor version env variables to identify DLL versions
Updating path for installed lib search
> Introduce DALROOT and Major Minor versions in env scripts

- cpp/oneapi/dal/algo/decision_forest/backend/cpu/infer_kernel_classification_dense.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_classification_dense.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_regression_dense.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/gpu/infer_kernel_classification_dense_dpc.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/gpu/infer_train_cls_kernel_dpc_test.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/gpu/infer_train_reg_kernel_dpc_test.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_classification_hist_dpc.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_regression_hist_dpc.cpp
- cpp/oneapi/dal/algo/decision_forest/detail/train_ops.hpp
- cpp/oneapi/dal/backend/interop/error_converter.cpp
added tests for checks of params don't exceed int32_max.
added corresponding casts
> added more safety checks for df new interfaces

- cpp/daal/src/services/compiler/generic/env_detect_features.cpp
- cpp/daal/src/services/service_defines.h
- cpp/oneapi/dal/backend/dispatcher.cpp
- cpp/oneapi/dal/common.hpp
Check availability of CPU extensions before detection
> Add safe CPU dispatcher

- examples/daal/cpp_sycl/makefile_lnx
- examples/daal/cpp_sycl/makefile_win
switching nmake example to dpcpp
> change compiler for sycl examples

- examples/daal/cpp_sycl/source/k_nearest_neighbors/bf_knn_dense_batch.cpp
> enable knn on CPU for sycl_examples

- docs/source/build_app/build-application.rst
Addition of major and minor binary versions of library to docs.
> [DOC] Binary versions info

- deploy/local/dal
- deploy/local/vars_fbsd.sh
- deploy/local/vars_lnx.sh
- deploy/local/vars_mac.sh
- deploy/local/vars_win.bat
- examples/daal/cpp/daal_win.vcxproj.tpl
- examples/daal/cpp/makefile_win
- examples/daal/cpp_sycl/daal_win.vcxproj.tpl
- examples/daal/cpp_sycl/makefile_win
- examples/oneapi/cpp/makefile_win
- examples/oneapi/cpp/onedal_win.vcxproj.tpl
- examples/oneapi/dpc/makefile_win
- examples/oneapi/dpc/onedal_win.vcxproj.tpl
- makefile
- makefile.ver
- samples/daal/cpp/arrow/launcher.bat
- samples/daal/cpp/kdb/launcher.bat
- samples/daal/cpp/mpi/launcher.bat
- samples/daal/cpp/mysql/launcher.bat
- Avoid double copy of static libs on Win
- Store version in one place (makefile.ver)
- Example and samples link to non-versioned Win library file
> Versioning update

- cpp/daal/src/algorithms/logistic_regression/oneapi/logistic_regression_train_dense_default_oneapi_impl.i
- cpp/daal/src/algorithms/objective_function/common/oneapi/objective_function_utils_oneapi.h
- cpp/daal/src/algorithms/objective_function/cross_entropy_loss/oneapi/cross_entropy_loss_dense_default_oneapi_impl.i
- cpp/daal/src/algorithms/objective_function/logistic_loss/oneapi/logistic_loss_dense_default_oneapi_impl.i
- examples/daal/cpp_sycl/daal_lnx.lst
- examples/daal/cpp_sycl/source/logistic_regression/log_reg_binary_dense_online.cpp
- examples/daal/cpp_sycl/source/logistic_regression/log_reg_dense_online.cpp
- examples/daal/cpp_sycl/source/logistic_regression/logistic_regression_online.h
- examples/daal/cpp_sycl/source/logistic_regression/logistic_regression_online.hpp
- created SYCL examples of logistic regression online algorithm using SGD solver and loss functions
- fixed initialization of starting point in logistic regression batch algorithm
- relaxed conditions of some asserts in logreg - they are valid now in the case of both batch and online computations
> Logistic regression online example

- samples/daal/cpp/oneccl/sources/low_order_moments_dense_distributed_oneccl.cpp
removed extra space in legal notice for lom sample
> fixed legal notice for lom distr sample

- docs/source/conf.py
Changed registered signed in the title to (R) -- output is the same.
> [DOC] Fixed conf.py

- cpp/oneapi/dal/algo/svm/infer_types.hpp
- docs/source/daal-interfaces.rst
- docs/source/daal/algorithms/pca/transform.rst
- docs/source/data-analytics-pipeline.rst
- docs/source/index.rst
- docs/source/onedal/get-started/build-and-run-examples.rst
- Addressed @rlnx 's comment about extra nested level
- Fixed spelling
> [DOC] Fixed spelling and structure

- cpp/daal/include/algorithms/boosting/logitboost_predict.h
- cpp/daal/include/algorithms/dbscan/dbscan_types.h
- cpp/daal/include/algorithms/decision_forest/decision_forest_classification_model_builder.h
- cpp/daal/include/algorithms/decision_forest/decision_forest_classification_predict.h
- cpp/daal/include/algorithms/decision_forest/decision_forest_classification_training_types.h
- cpp/daal/include/algorithms/em/em_gmm_types.h
- cpp/daal/include/algorithms/gradient_boosted_trees/gbt_classification_model_builder.h
- cpp/daal/include/algorithms/gradient_boosted_trees/gbt_classification_predict.h
- cpp/daal/include/algorithms/gradient_boosted_trees/gbt_regression_model_builder.h
- cpp/daal/include/algorithms/linear_regression/linear_regression_model_builder.h
- cpp/daal/include/algorithms/logistic_regression/logistic_regression_model_builder.h
- cpp/daal/include/algorithms/logistic_regression/logistic_regression_predict.h
- cpp/daal/include/algorithms/moments/low_order_moments_types.h
- cpp/daal/include/algorithms/svm/svm_model_builder.h
- cpp/daal/include/algorithms/tree_utils/tree_utils.h
- cpp/daal/include/algorithms/tree_utils/tree_utils_classification.h
- cpp/daal/include/algorithms/tree_utils/tree_utils_regression.h
- cpp/daal/include/data_management/features/internal/identifiers_impl.h
- cpp/daal/include/services/error_indexes.h
> [DOC] Fixed spelling in header files

- README.md
Fix broken link to get started
> Fix get-started link

- cpp/daal/src/algorithms/objective_function/cross_entropy_loss/cross_entropy_loss_dense_default_batch_impl.i
- cpp/daal/src/algorithms/objective_function/cross_entropy_loss/cross_entropy_loss_dense_default_batch_kernel.h
- cpp/daal/src/algorithms/objective_function/logistic_loss/logistic_loss_dense_default_batch_impl.i
- cpp/daal/src/algorithms/objective_function/logistic_loss/logistic_loss_dense_default_batch_kernel.h
Threading reading rows was added for LogLoss & CrossEntropy
> Threading read rows for CrossEntropy & LogLoss

- cpp/daal/src/algorithms/objective_function/cross_entropy_loss/cross_entropy_loss_dense_default_batch_impl.i
- cpp/daal/src/algorithms/objective_function/logistic_loss/logistic_loss_dense_default_batch_impl.i
- cpp/daal/src/algorithms/optimization_solver/sgd/sgd_dense_minibatch_impl.i
This PR contains additional marks that are used for kernel profiling on the benchmarks level.
> Benchmark labels added to CPU Logistic regression

- deploy/local/vars_lnx.sh
- deploy/local/vars_mac.sh
Updating env scripts to support mksh
> Update env script to support mksh

- README.md
> [DOC] Updated README

- cpp/oneapi/dal/algo/decision_forest/common.hpp
- cpp/oneapi/dal/algo/knn/common.hpp
- cpp/oneapi/dal/algo/svm/common.hpp
- docs/source/onedal/get-started/build-and-run-examples.rst
- docs/source/onedal/get-started/prerequisites.rst
> [DOC] Fixed broken links and product names

- CODE_OF_CONDUCT.md
Introducing initial version of code of conduct statement for repository.
> Introduce initial version of  CODE_OF_CONDUCT.md

- cpp/daal/include/algorithms/k_nearest_neighbors/bf_knn_classification_predict.h
- cpp/daal/include/algorithms/k_nearest_neighbors/bf_knn_classification_training_batch.h
- cpp/daal/include/algorithms/k_nearest_neighbors/kdtree_knn_classification_predict.h
- cpp/daal/include/algorithms/k_nearest_neighbors/kdtree_knn_classification_training_batch.h
- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_classification_predict_dense_default_batch_fpt_dispatcher.cpp
- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_classification_train_dense_default_batch_fpt_dispatcher.cpp
Add kNN batch constructors with nClasses parameter to align with other classification algorithms.
Fix typos in bf_knn_classification_training_batch.h
> Add kNN constructors with nClasses

- examples/oneapi/dpc/source/decision_forest/df_cls_dense_batch.cpp
Add  queue for y_test in df_cls_dense_batch.cpp
> Fix decision forest queue in example

- samples/daal/cpp/oneccl/daal_lnx.lst
- samples/daal/cpp/oneccl/sources/pca_dense_batch_distributed_oneccl.cpp
- samples/daal/cpp/oneccl/sources/pca_dense_online_distributed_oneccl.cpp
correctness of work was checked
> PCA online oneCCL sample

- README.md
- Added links to wiki and discussions
- Added a badge for discussions and fixed the badge for license
- Updated some wording
> [DOC] README update

- .ci/pipeline/ci.yml
- cpp/daal/src/algorithms/svm/svm_predict_impl.i
daal4py CI always green, also if errors occured. PR contains fix.
- ci.yml
> Fix daal4py CI

- README.md
- Updated wording in Support section as was discussed last week
- Moved contribution section up to place it under Support
- Removed resources from DAAL vs. oneDAL table because links to DAAL redirect to oneDAL resources now.
> [DOC] Updated info in readme

- dev/make/cmplr.dpcpp.mk
- dev/make/common.mk
Attempt to fix missing DPC++ symbols on Windows.
> Link DLL on windows with DPC++

- .ci/pipeline/ci.yml
- WORKSPACE
- dev/bazel/deps/mkl.bzl
- dev/bazel/repos.bzl
Download MKL via Bazel instead apt-get installation.
> Download MKL from PIP instead oneAPI toolkit installation

- docs/source/daal/algorithms/decision_forest/decision-forest-classification.rst
- docs/source/daal/algorithms/decision_forest/decision-forest-regression.rst
- docs/source/daal/algorithms/kmeans/initialization-batch.rst
- docs/source/daal/algorithms/kmeans/k-means-clustering.rst
- Updated links to daal4py examples
- Fixed bibliography links
> [DOC] Fixed links in docs

- cpp/daal/src/algorithms/dtrees/dtrees_train_data_helper.i
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/df_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_dense_default_impl.i
> DF: improve accuracy

- examples/daal/java/com/intel/daal/examples/knn_classification/BFKNNDenseBatch.java
- java/com/intel/daal/services/DaalContext.java
To align output of the example with c++ analogue.
- remove redundant line
> Fix BF kNN java example

- cpp/daal/src/algorithms/elastic_net/elastic_net_train_dense_default_impl.i
- cpp/daal/src/algorithms/lasso_regression/lasso_regression_train_dense_default_impl.i
- cpp/daal/src/algorithms/objective_function/mse/mse_dense_default_batch_impl.i
- cpp/daal/src/algorithms/service_threading.h
> Fix Elastic Net & Lasso regression run-to-run stability

- cpp/oneapi/dal/algo/linear_kernel/test/batch.cpp
- cpp/oneapi/dal/algo/pca/test/batch.cpp
- cpp/oneapi/dal/algo/rbf_kernel/test/batch.cpp
- cpp/oneapi/dal/test/engine/dataframe_actions.hpp
- cpp/oneapi/dal/test/engine/dataframe_common.cpp
- cpp/oneapi/dal/test/engine/dataframe_common.hpp
- cpp/oneapi/dal/test/engine/linalg/matrix.hpp
- cpp/oneapi/dal/test/engine/linalg/umath.hpp
- cpp/oneapi/dal/test/engine/math.hpp
> Normal generator

- cpp/oneapi/dal/algo/triangle_counting/common.cpp
- cpp/oneapi/dal/io/detail/load_graph.cpp
> Fixed KW issues brought by TC algorithm addition

- cpp/daal/src/externals/core_threading_win_dll.cpp
- cpp/oneapi/dal/algo/triangle_counting/common.cpp
- cpp/oneapi/dal/io/detail/load_graph.cpp
> Fixed build issue on VS2017 and VS2019

- cpp/oneapi/dal/algo/triangle_counting/backend/cpu/vertex_ranking_default_kernel_avx512.hpp
- cpp/oneapi/dal/algo/triangle_counting/backend/cpu/vertex_ranking_default_kernel_scalar.hpp
> Fixed issue with uninitialized memory for TC

- dev/bazel/HOWTO.md
Upstream the changes presented on the meeting.
> Update Bazel HOWTO

- docs/source/api/algorithms/clustering/kmeans.rst
> [DOC] Fix kmeans doc

- README.md
> [DOC] Readme license update

- docs/source/daal/algorithms/optimization-solvers/solvers/limited-memory-broyden-fletcher-goldfarb-shanno-algorithm.rst
- docs/source/onedal/appendix/decision-tree.rst
Minor fixes for empty toctree, equations, and incorrect rendering of sphinx-tabs
Before: 
After:
> [DOC] Fix doc issues

- dev/bazel/config/config.bzl
- docs/doxygen/doxygen_conf_cpp.txt
- docs/doxygen/doxygen_conf_cpp_examples.txt
- docs/doxygen/doxygen_conf_cpp_web.txt
- docs/doxygen/doxygen_conf_java.txt
- docs/doxygen/doxygen_conf_java_examples.txt
- docs/doxygen/doxygen_conf_java_web.txt
- makefile.ver
> Update to 2021.2.2

- cpp/daal/src/algorithms/dtrees/forest/classification/oneapi/df_classification_tree_helper_impl.i
- cpp/daal/src/algorithms/dtrees/forest/regression/oneapi/df_regression_tree_helper_impl.i
added num of samples info into split nodes which was the root cause for failures in feature importance conformance tests
> fixed issues to pass conf tests with features' importance

- deploy/local/dal
> Updating our modulefile to comply with requerements

- deploy/local/vars_lnx.sh
> Updating vars script to new requirements

- cpp/oneapi/dal/backend/primitives/test/fill_dpc.cpp
Add checks for the fill result.
> Update DPC++ fill test

- cpp/oneapi/dal/algo/jaccard/detail/vertex_similarity_default_kernel.hpp
- cpp/oneapi/dal/algo/jaccard/detail/vertex_similarity_ops.hpp
Fix the jaccard algorithm for tables with zero columns and non-zero rows
> Fix empty table case for jaccard algo

- .ci/pipeline/ci.yml
> Fix passed build daal4py when there are failed

- cpp/oneapi/dal/algo/jaccard/detail/vertex_similarity_default_kernel.hpp
Fix jaccard build fail with gnu compiler
> Fix jaccard build fail with gnu compiler

- dev/bazel/config/config.bzl
- docs/doxygen/doxygen_conf_cpp.txt
- docs/doxygen/doxygen_conf_cpp_examples.txt
- docs/doxygen/doxygen_conf_cpp_web.txt
- docs/doxygen/doxygen_conf_java.txt
- docs/doxygen/doxygen_conf_java_examples.txt
- docs/doxygen/doxygen_conf_java_web.txt
- makefile.ver
> 2021.2.2 -> 20221.2.3

- cpp/oneapi/dal/detail/common.cpp
This is a fix of debug build on MacOS
CI (debug build): http://intel-ci.intel.com/ebb6ecd0-7382-f1d5-8066-8cdcd4b723a1
> Explicit instantiation for integer_overflow_ops on size_t

- docs/source/onedal/get-started/build-and-run-examples.rst
Updating examples commands to correct lines
> Updating examples to correct command lines

- cpp/daal/src/algorithms/svm/svm_train_thunder_impl.i
> Reduce block size for compute gradient in SVM

- cpp/daal/src/data_management/roc_auc_score.cpp
> Workaround roc_auc from hanging

- cpp/daal/src/algorithms/service_kernel_math.h
Change operators in implicit_als code to avoid fail of build on VS compiler
> Fix Implicit ALS build on VS compiler

- cpp/oneapi/dal/algo/subgraph_isomorphism/backend/cpu/bit_vector.hpp
- cpp/oneapi/dal/algo/subgraph_isomorphism/backend/cpu/matching.hpp
- cpp/oneapi/dal/algo/subgraph_isomorphism/backend/cpu/si.hpp
- cpp/oneapi/dal/algo/subgraph_isomorphism/backend/cpu/sorter.hpp
- cpp/oneapi/dal/algo/subgraph_isomorphism/backend/cpu/sorter_cpu.cpp
- cpp/oneapi/dal/algo/subgraph_isomorphism/backend/cpu/stack.hpp
CPU-ed sconsistent_conditions, kw fixes
> Subgraph isomorphism, kw fix

- cpp/oneapi/dal/algo/subgraph_isomorphism/backend/cpu/matching.hpp
> Fixed infinite loop bug in Subgraph isomorphism

- cpp/daal/src/algorithms/svm/svm_train_common.h
- cpp/daal/src/algorithms/svm/svm_train_common_impl.i
- cpp/daal/src/algorithms/svm/svm_train_thunder_impl.i
> [rls] SVM Weights Initialization Fix

- cpp/daal/src/algorithms/dtrees/forest/classification/oneapi/cl_kernels/df_batch_predict_classification_kernels.cl
- cpp/daal/src/algorithms/dtrees/forest/classification/oneapi/df_classification_predict_dense_oneapi_impl.i
- cpp/oneapi/dal/algo/subgraph_isomorphism/backend/cpu/matching.hpp
migrated to using float class hist, instead of double, for float prediction
> migrated to using float class hist, instead of double, for float prediction

- docs/source/api/algorithms/nearest-neighbors/knn-classification.rst
- docs/source/api/algorithms/pairwise-distances/chebyshev-distance.rst
- docs/source/api/algorithms/pairwise-distances/index.rst
- docs/source/api/algorithms/pairwise-distances/minkowski-distance.rst
- docs/source/includes/nearest-neighbors/knn-examples.rst
- docs/source/includes/pairwise-distances/chebyshev-distance-introduction.rst
- docs/source/includes/pairwise-distances/minkowski-distance-introduction.rst
- docs/source/onedal/algorithms/index.rst
- docs/source/onedal/algorithms/nearest-neighbors/knn-classification.rst
- docs/source/onedal/algorithms/pairwise-distances/chebyshev-distance.rst
- docs/source/onedal/algorithms/pairwise-distances/index.rst
- docs/source/onedal/algorithms/pairwise-distances/minkowski-distance.rst
Documents update for previous changes in kNN API due to Minkowski and Chebyshev distance support addition.
Cherry-pick from master: #1684
> kNN and Pairwise Distances docs update

- dev/make/cmplr.dpcpp.mk
- examples/daal/cpp_sycl/daal_win.vcxproj.tpl
- examples/daal/cpp_sycl/makefile_lnx
- examples/daal/cpp_sycl/makefile_win
- examples/oneapi/dpc/makefile_lnx
- examples/oneapi/dpc/makefile_win
- examples/oneapi/dpc/onedal_win.vcxproj.tpl
- samples/daal/cpp/oneccl/makefile_lnx
Copy of [this](https://github.com/oneapi-src/oneDAL/pull/1680) PR for release
> [rls] Additional option 

- cpp/daal/include/data_management/data_source/csv_feature_manager.h
- cpp/daal/include/data_management/data_source/modifiers/csv/modifier.h
Fixes #1670 
- Wrong type in `daal::data_management::ModifierIface`
- Wrong type in `daal::data_management::modifiers::csv::Context`
> fix wrong type in CSVDataSource

- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_impl.i
- cpp/daal/src/algorithms/service_kernel_math.h
> Fix for kNN distance calculation

- cpp/oneapi/dal/algo/subgraph_isomorphism/backend/cpu/graph.hpp
- cpp/oneapi/dal/algo/subgraph_isomorphism/backend/cpu/matching.hpp
> Subgraph isomorphism: enabling state_exploration_list

- cpp/oneapi/dal/algo/subgraph_isomorphism/detail/graph_matching_ops.hpp
- cpp/oneapi/dal/algo/subgraph_isomorphism/test/badargs.cpp
- cpp/oneapi/dal/detail/error_messages.cpp
- cpp/oneapi/dal/detail/error_messages.hpp
> Subgraph isomorphism: error handling when target graph is smaller than pattern - 2

- deploy/local/vars_win.bat
> Fix pkgconfig for win vars

- cpp/daal/src/algorithms/dtrees/forest/classification/oneapi/df_classification_predict_dense_oneapi_impl.i
added processing of situation when only class probas are required
> add processing of situation when only class probas are required

- docs/source/onedal/build_app/build-application.rst
Added debug libs + fixed rendering issues
> [DOC] Add debug libs

- .ci/env/clang.sh
- .gitignore
> azure ci: fix apt-key error in clang-format check

- java/com/intel/daal/utils/LibUtils.java
> Fix incorrect TBB version in Java API

- docs/source/_templates/layout.html
To collect usage data for published documentation.
> [DOC] Add analytics script

- cpp/daal/include/algorithms/decision_forest/decision_forest_classification_model.h
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_model.cpp
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_model_impl.h
Revert traverse changes to repair dynamic BC
> Revert traverse changes

- cpp/oneapi/dal/backend/primitives/selection/kselect_by_rows_quick.hpp
> Fixed accuracy for DPC kNN

- examples/daal/cpp_sycl/daal_win.vcxproj.tpl
- examples/oneapi/dpc/onedal_win.vcxproj.tpl
Copy of the [Compilation Option (#1878) PR](https://github.com/oneapi-src/oneDAL/pull/1878)
> Compilation Option

- cpp/oneapi/dal/algo/knn/backend/gpu/infer_kernel_brute_force_dpc.cpp
- cpp/oneapi/dal/algo/knn/test/batch.cpp
- cpp/oneapi/dal/backend/primitives/voting.hpp
- cpp/oneapi/dal/backend/primitives/voting/distance.hpp
- cpp/oneapi/dal/backend/primitives/voting/distance_dpc.cpp
- cpp/oneapi/dal/backend/primitives/voting/naive_distance_dpc.cpp
- cpp/oneapi/dal/backend/primitives/voting/test/distance_dpc.cpp
- cpp/oneapi/dal/detail/common.hpp
- cpp/oneapi/dal/detail/error_messages.cpp
Refers to [original PR](https://github.com/oneapi-src/oneDAL/pull/1870).
> New distance voting PR

- cpp/oneapi/dal/graph/directed_adjacency_vector_graph.hpp
- cpp/oneapi/dal/graph/service_functions.hpp
- cpp/oneapi/dal/graph/undirected_adjacency_vector_graph.hpp
- docs/doxygen/oneapi/Doxyfile
- docs/source/_static/style.css
- docs/source/api/data-management/graph-service.rst
- docs/source/api/data-management/graph-service/directed-adjacency-vector-graph.rst
- docs/source/api/data-management/graph-service/undirected-adjacency-vector-graph.rst
- docs/source/api/data-management/graph/directed-adjacency-vector-graph.rst
- docs/source/api/data-management/graph/undirected-adjacency-vector-graph.rst
- docs/source/api/data-management/graphs.rst
- docs/source/api/data-management/index.rst
- docs/source/bibliography.rst
- docs/source/conf.py
- docs/source/onedal/data-management/graph/directed-adjacency-vector-graph.rst
- docs/source/onedal/data-management/graph/undirected-adjacency-vector-graph.rst
- docs/source/onedal/data-management/graphs.rst
- docs/source/onedal/data-management/index.rst
- docs/source/onedal/data-management/table/homogen.rst
- docs/source/onedal/data-management/tables.rst
- docs/source/onedal/glossary.rst
- docs/source/onedal/notations.rst
Doc changes from PR #1767 have to be in the release branch as well
> Add docs for graphs (#1767)

- cpp/daal/include/services/internal/sycl/level_zero_module_sycl.h
> patch for levz descriptor

- cpp/oneapi/dal/graph/detail/directed_adjacency_vector_graph_topology_builder.hpp
- cpp/oneapi/dal/graph/detail/undirected_adjacency_vector_graph_topology_builder.hpp
Fix of compile error while lazy header dal.hpp is used.
> Fix lazy header include

- cpp/daal/src/algorithms/dtrees/forest/df_train_dense_default_impl.i
- Fix formula min_impurity_decrease
- Change chooseFeatures
- Fix resetting constant features
> Fix bugs in RandomForest

- cpp/daal/src/algorithms/service_kernel_math.h
- cpp/oneapi/dal/algo/knn/backend/model_conversion.hpp
\>1.5x against scikit-learn on real datasets.
Includes #2072 optimizations
> [BF kNN] Minkowski distance optimizations

- cpp/daal/src/algorithms/service_kernel_math.h
fix sqrt normalization for cosine distance computation
> [BF kNN] Fix cosine distance calculation

- cpp/oneapi/dal/algo/basic_statistics/backend/gpu/compute_kernel_dense_impl_dpc.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/gpu/infer_kernel_impl_dpc.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_feature_type_dpc.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_hist_impl_dpc.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_service_kernels_dpc.cpp
- cpp/oneapi/dal/backend/primitives/selection/select_flagged_dpc.cpp
- cpp/oneapi/dal/backend/primitives/sort/sort_dpc.cpp
made required changes to enable build with latest 2022.2.22 compiler
>  migration to 2022 compiler

- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_dense_default_impl.i
leftWeights doesn't include 0 sample
> Fix minor bug in RF

- cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_cov.cpp
- cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_svd.cpp
- cpp/oneapi/dal/algo/pca/backend/gpu/train_kernel_cov_impl_dpc.cpp
- cpp/oneapi/dal/algo/pca/common.cpp
- cpp/oneapi/dal/algo/pca/common.hpp
- cpp/oneapi/dal/algo/pca/train_types.cpp
- cpp/oneapi/dal/algo/pca/train_types.hpp
its copy of https://github.com/oneapi-src/oneDAL/pull/2070
> Add optional results for pca

- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_train_dense_default_impl.i
> kNN KD-Tree split condition bugfix 

- cpp/daal/src/algorithms/service_kernel_math.h
> Fix memory leak for Manhattan distances

- examples/oneapi/dpc/makefile_lnx
nit: The closing quote is missing
> Update makefile_lnx otherwise make error

- .ci/pipeline/ci.yml
- INSTALL.md
- `msys/dos2unix` package installation (required by makefile)
- `develop` branch for cloning
- New/updated links and commands
- Exclude docs from CI pipeline
> INSTALL.md update

- cmake/templates/oneDALConfig.cmake.in
- deploy/nuget/inteldal.nuspec.tpl
- deploy/nuget/prepare_dal_nuget.sh
- makefile
- Optionally disable tbb in cmake config
- Add tbb dependency in nuget packages
> TBB cmake config and nuget pkgs update

- cmake/templates/oneDALConfig.cmake.in
- makefile
added opencl deps for lnx32 DPC plat. `libonedal_dpc.so` have some symbols from opencl lib
> FIX: undef  symbol issue

- cpp/oneapi/dal/algo/BUILD
- cpp/oneapi/dal/algo/dbscan/BUILD
- examples/oneapi/dpc/BUILD
- examples/oneapi/dpc/onedal_lnx.lst
- examples/oneapi/dpc/source/covariance/cor_dense_batch.cpp
- examples/oneapi/dpc/source/covariance/cov_dense_batch.cpp
- examples/oneapi/dpc/source/dbscan/dbscan_brute_force_batch.cpp
This pull request contain changes for enable kmeans and dbscan in bazel examples. Also, minor fixes for covariance examples.
> Fix bazel examples

- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_model.cpp
- Add probability table for RF classification deserialization and applicable DAAL versions
> Serialization fixes

- cpp/oneapi/dal/algo/dbscan/BUILD
- cpp/oneapi/dal/algo/dbscan/backend/gpu/kernel_fp_impl.hpp
- cpp/oneapi/dal/algo/dbscan/backend/gpu/results.hpp
- cpp/oneapi/dal/backend/primitives/ndarray.hpp
- cpp/oneapi/dal/backend/primitives/selection.hpp
1) Fixed logical error with copying data from host to device
2) Reduced volume of memory copied host <-> device
3) Modified build file to speed up compilation
4) Improved performance (refers to point 2)
> Fixes in DBSCAN algorithm

- docs/source/get-started/build-and-run-examples.rst
- docs/source/get-started/prerequisites.rst
- docs/source/system-requirements.rst
Updated DPC++ references in oneDAL documentation.
> SYCL refocus

- .github/renovate.json
Fix configuration of renovate to resolve parsing issue
> Fixing renovate configuration

- .ci/pipeline/ci.yml
- .ci/pipeline/docs.yml
Skipping CI execution for doc changes to reduce CI load during doc requirement updates
> Exclude CI execution on doc changes

- .github/CODEOWNERS
- .mergify.yml
Updating codeowners + mergify configs.  Automerge for mergify doesn't work now due to branch protection rules
> Updating codeowners

- WORKSPACE
- dev/download_micromkl.bat
- dev/download_micromkl.sh
Updating to recent FPK version for CPU and GPU
> Updating to recent FPKs

- examples/daal/cpp/makefile_win
Adding /ignore:4996 to cpp examples
> Remove deprecated warning on windows

- .ci/pipeline/ci.yml
- .ci/scripts/build.sh
- .ci/scripts/test.sh
- deploy/nuget/prepare_dal_nuget.sh
- dev/make/identify_os.sh
- makefile
- Autodetection of platform using `uname`
- Removal of platform arg. from CI and other scripts 
- Generation of cmake configs in makefile if cmake is available
> makefile helpers

- .ci/pipeline/ci.yml
Set DALROOT required by setup_sklearnex.py
> Fix sklearnex setup

- cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_cls.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_reg.cpp
- cpp/oneapi/dal/algo/decision_forest/common.hpp
- cpp/oneapi/dal/algo/decision_forest/train_types.cpp
- cpp/oneapi/dal/algo/decision_forest/train_types.hpp
Addition of all OOB error types of DAAL to oneDAL interface.
> Update OOB error results in decision forest

- .ci/pipeline/ci.yml
required for https://github.com/intel/scikit-learn-intelex/pull/1217
> FIX: updates examples runner path

- cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_hist_impl.hpp
- cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_hist_impl_dpc.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_splitter_impl.hpp
- cpp/oneapi/dal/algo/decision_forest/common.hpp
- docs/source/api/algorithms/ensembles/decision-forest.rst
Changes requested in PR#2270 but not made before merge. All usage of 'treshold' to 'threshold'.
Changes proposed in this pull request: Corrections to operational functions with RF GPU splitters and documentation.
> treshold -> threshold

- docs/source/onedal/algorithms/clustering/dbscan.rst
> Documentation update: DBSCAN

- cpp/oneapi/dal/algo/kmeans/infer_types.hpp
- cpp/oneapi/dal/algo/kmeans/train_types.hpp
- docs/source/onedal/algorithms/clustering/kmeans.rst
Kmeans doc update
- Fix stop condition description
- Add empty cluster handling description
- Add SPMD mode mentioning
- Docstring fix for K-means
> Kmeans doc update

- cpp/daal/include/services/daal_defines.h
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
- cpp/daal/src/algorithms/dtrees/gbt/gbt_train_hist_kernel.i
- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_train_dense_default_impl.i
- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_impl.i
- cpp/daal/src/algorithms/kernel_function/kernel_function_csr_impl.i
- cpp/daal/src/algorithms/kernel_function/kernel_function_rbf_helper.h
- cpp/daal/src/algorithms/qr/qr_dense_default_pcl_impl.i
- cpp/daal/src/algorithms/service_kernel_math.h
- cpp/daal/src/algorithms/service_sort.h
- cpp/daal/src/algorithms/svm/svm_train_common_impl.i
- cpp/daal/src/algorithms/tsne/tsne_gradient_descent_fpt_cpu.cpp
- cpp/daal/src/data_management/data_conversion.cpp
- cpp/daal/src/data_management/data_conversion_cpu.cpp
- cpp/daal/src/data_management/data_conversion_cpu.h
- cpp/daal/src/data_management/finiteness_checker.cpp
- cpp/daal/src/externals/service_blas.h
- cpp/daal/src/services/service_defines.h
- cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_avx512.hpp
- cpp/oneapi/dal/algo/subgraph_isomorphism/backend/cpu/compiler_adapt.hpp
- cpp/oneapi/dal/algo/triangle_counting/backend/cpu/intersection_tc.hpp
- cpp/oneapi/dal/backend/primitives/intersection/intersection.hpp
- docs/source/contribution/coding_guide.rst
Reverts oneapi-src/oneDAL#2258
> Revert "Intel_LLVM compiler macros"

- cpp/oneapi/dal/algo/knn/backend/gpu/infer_kernel_impl_dpc_distr.hpp
- cpp/oneapi/dal/algo/knn/test/spmd.cpp
- cpp/oneapi/dal/backend/primitives/selection/select_indexed_dpc.cpp
-Resolution for bug with poor inference quality for any inferences outside of first inference data block
-Addition to knn spmd tests to improve coverage
-Assertion in selection primitives to catch similar issues in future
> distributed kNN multiple inference blocks bug resolution

- .github/renovate.json
Grouping update for doc pacakges
> Group doc packages updates

- cpp/oneapi/dal/algo/kmeans_init/common.hpp
- docs/source/api/algorithms/clustering/kmeans-init.rst
- docs/source/includes/clustering/kmeans-init-introduction.rst
- docs/source/onedal/algorithms/clustering/kmeans-init.rst
K-Means init doc update
- Add Usage example reference to interface description
- Add random_dense method description
- Add K-Means++ description
- Add parallel K-Means++ mentioning
- Add tag-types descriptions in API section
> Kmeans init doc update

- docs/source/api/algorithms/statistics/basic-statistics.rst
- docs/source/includes/statistics/basic-statistics-introduction.rst
- docs/source/includes/statistics/basic-statistics-usage-examples.rst
- docs/source/onedal/algorithms/statistics/basic-statistics.rst
- Add basic-statistics usage example
- Fix table in basic-statistics introduction
- Add reference to basic-statistics examples
- Fix a typo in basic-statistics doc SMPD -> SPMD
> Basic statistics doc update

- .ci/scripts/conformance-scripts/run_tests.py
Update for conformance tests report script to listen from stderr for sklearnex verbosity messages
> Align conformance tests to updated verbose mode

- cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_fp_impl.hpp
This splitting is necessary to support huge datasets in KMeans
> kmeans (feature): split select function by blocks in external loop

- makefile
The PR aims to reflect a change of the major version of the default sycl library.
> Increase major version of the default sycl library

- cpp/oneapi/dal/algo/rbf_kernel/backend/gpu/compute_kernel_dense_dpc.cpp
- cpp/oneapi/dal/algo/rbf_kernel/test/batch.cpp
- Fix event dependencies
- Fix range definition
- Rewrite results check
> Fix rbf_kernel

- .ci/pipeline/ci.yml
- INSTALL.md
Solves https://github.com/oneapi-src/oneDAL/issues/2388
> Remove develop branch from INSTALL and CI

- cpp/daal/include/algorithms/decision_forest/decision_forest_training_parameter.h
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_dense_default_impl.i
- cpp/oneapi/dal/table/csr.hpp
Using CamelCase for variable naming
> MAINT: update splitter mode variable name

- INSTALL.md
- deploy/maven/README-doc
- deploy/maven/daal.pom
- deploy/maven/dal-natives.pom
- deploy/maven/dal-parent.pom
- deploy/maven/dal.pom
- deploy/pkg-config/pkg-config.tpl
The PR aims to address potential issues with the IDZ redirections.
> doc: IDZ links update

- INSTALL.md
- deploy/maven/README-doc
- deploy/maven/daal.pom
- deploy/maven/dal-natives.pom
- deploy/maven/dal-parent.pom
- deploy/maven/dal.pom
- deploy/pkg-config/pkg-config.tpl
The PR aims to address potential issues with the IDZ redirections
> doc: IDZ links update (#2415)

- cpp/oneapi/dal/algo/kmeans/BUILD
- cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_fp_impl.hpp
Rewrite compute_objective_function and compute_squares kernels in K-Means using primitives
> Rewrite kernels in K-Means

- docs/source/deprecation.rst
Listing deprecation mentioned in other places to centralized location in documentation
> Updating list of deprecations

- cpp/oneapi/dal/backend/primitives/blas/gemv_dpc.cpp
- cpp/oneapi/dal/backend/primitives/objective_function/logloss_dpc.cpp
Fix error that occurs with new logloss hessian product primitive
> Fix logloss hessian product primitive private CI error 

- .ci/pipeline/ci.yml
- .ci/scripts/install_dpcpp.sh
Changes:
- impi 2021.8 -> 2021.10
- dpcpp compiler 2023.1.0 -> 2023.2.1
> Update dependencies in CI

- cpp/oneapi/dal/algo/decision_forest/common.hpp
- cpp/oneapi/dal/backend/memory.hpp
Restores #2390 and #2392 (reverted accidentally by #2396)
> infra: restore PRs 2390, 2392

- cpp/daal/include/data_management/features/internal/identifiers_impl.h
- cpp/daal/include/services/collection.h
- cpp/daal/src/algorithms/dbscan/dbscan_result_types.cpp
- cpp/daal/src/algorithms/distributions/uniform/uniform_impl.i
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_predict_dense_default_batch_container.h
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_container.h
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_training_types.cpp
- cpp/daal/src/algorithms/dtrees/forest/df_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_container.h
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_dense_default_impl.i
- cpp/daal/src/algorithms/optimization_solver/sgd/sgd_dense_minibatch_impl.i
- cpp/daal/src/algorithms/pca/pca_result.cpp
- cpp/daal/src/algorithms/stump/stump_classification_train_aux.i
- cpp/oneapi/dal/detail/common.hpp
> Coverity hits fixes

- cpp/daal/src/algorithms/dtrees/gbt/classification/gbt_classification_train_container.h
- cpp/daal/src/algorithms/dtrees/gbt/regression/gbt_regression_train_container.h
As far as DAAL_ASSERT operates only in debug mode, one should replace it for checking the result of the dynamic_cast
> FIX replace DAAL_ASSERT by DAAL_CHECK in GBT

- cpp/daal/src/algorithms/dtrees/gbt/gbt_train_tree_builder.i
Fix the potential integer overflow by casting to uint64_t
> FIX potential integer overflow

- .ci/pipeline/ci.yml
- .ci/scripts/test.sh
Changes:
- Add mpi installation and update python version in LinuxDaal4py job
- Enable n_jobs for examples building
> CI configuration update

- .github/renovate.json
finally fixing doc package groping
> recovering renovate config

- .ci/scripts/conformance-scripts/run_tests.py
- .ci/scripts/conformance-scripts/run_xpu_conformance.py
- deploy/local/vars_lnx.sh
- deploy/local/vars_mac.sh
- docs/dalapi/doxypy/model.py
Addressing codefactor hits - https://www.codefactor.io/repository/github/oneapi-src/onedal/pull/fixed/2496
1. disable checks in vars script as they have strange code to work with multiple different shells
2. Fix python Except
3. Fix python extra space
> Fixing part of codefactor hits

- cpp/daal/src/algorithms/kernel_function/oneapi/kernel_function_linear_kernel_oneapi.h
- cpp/daal/src/algorithms/kernel_function/oneapi/kernel_function_rbf_kernel_oneapi.h
remove unreachable return statement
> Coverity fixes

- deploy/local/vars_lnx.sh
The PR aims to address the most recent requirements related to the env script on Linux
> Update env script according to the latest comments

- .ci/pipeline/ci.yml
- docs/source/conf.py
- docs/source/daal/algorithms/covariance/correlation-and-variance-covariance-matrices.rst
- docs/source/daal/algorithms/dbscan/index.rst
- docs/source/daal/algorithms/gradient_boosted_trees/gradient-boosted-trees-regression.rst
- docs/source/daal/algorithms/k_nearest_neighbors/k-nearest-neighbors-knn-classifier.rst
- docs/source/daal/algorithms/kmeans/k-means-clustering.rst
- docs/source/daal/algorithms/linear_ridge_regression/linear-ridge-regression-computation.rst
- docs/source/daal/algorithms/logistic_regression/logistic-regression.rst
- docs/source/daal/algorithms/moments/moments-of-low-order.rst
- docs/source/daal/algorithms/pca/principal-component-analysis.rst
- docs/source/daal/algorithms/pca/transform.rst
- docs/source/daal/algorithms/svm/support-vector-machine-classifier.rst
- docs/source/includes/clustering/dbscan-examples.rst
- docs/source/includes/clustering/kmeans-examples.rst
- docs/source/includes/decomposition/pca-examples.rst
- docs/source/includes/ensembles/df-classification-examples.rst
- docs/source/includes/ensembles/df-regression-examples.rst
- docs/source/includes/nearest-neighbors/knn-examples.rst
- docs/source/includes/svm/svm-examples.rst
> infra: update public ci sycl examples path

- samples/daal/cpp/mpi/launcher.bat
- samples/oneapi/dpc/ccl/makefile_lnx
The PR aims to adjust path to the CCL includes according to the upcoming layout changes.
> Adjust path to CCL includes

- cpp/oneapi/dal/table/BUILD
- cpp/oneapi/dal/table/backend/convert/copy_convert.cpp
- cpp/oneapi/dal/table/backend/convert/copy_convert.hpp
- cpp/oneapi/dal/table/backend/convert/copy_convert_dpc.cpp
- cpp/oneapi/dal/table/backend/convert/copy_convert_impl.hpp
- cpp/oneapi/dal/table/backend/convert/copy_convert_impl_cpu.cpp
- cpp/oneapi/dal/table/backend/convert/copy_convert_impl_dpc.cpp
- cpp/oneapi/dal/table/backend/heterogen_kernels.cpp
- cpp/oneapi/dal/table/backend/heterogen_table_impl.hpp
- cpp/oneapi/dal/table/backend/register_serializable.cpp
- cpp/oneapi/dal/table/test/heterogen.cpp
- cpp/oneapi/dal/table/test/heterogen_serialization.cpp
> Heterogen table extension & fixes.

- cpp/daal/include/algorithms/algorithm_container_base_batch.h
- cpp/daal/include/algorithms/algorithm_container_base_common.h
- cpp/daal/include/services/daal_defines.h
- cpp/daal/include/services/daal_string.h
- cpp/daal/include/services/error_handling.h
- cpp/daal/include/services/error_id.h
- cpp/daal/include/services/error_indexes.h
- cpp/daal/include/services/internal/execution_context.h
- cpp/daal/include/services/internal/sycl/math/mkl_blas.h
- cpp/daal/include/services/internal/sycl/math/mkl_dal_utils.h
- cpp/daal/include/services/internal/sycl/math/mkl_lapack.h
- cpp/daal/include/services/library_version_info.h
- cpp/daal/src/externals/core_threading_win_dll.cpp
- cpp/oneapi/dal/detail/error_messages.hpp
- cpp/oneapi/dal/detail/mpi/communicator.hpp
- cpp/oneapi/dal/table/detail/access_iface_compat.hpp
- cpp/oneapi/dal/table/detail/table_iface.hpp
- examples/daal/cpp/source/optimization_solvers/custom_obj_func.h
- examples/daal/cpp/source/services/library_version_info.cpp
The PR aims to address the most recent Trademarks' modifications in the codebase.
- Only comments sections have been adjusted
> Apply Trademarks' recent adjustments

- third-party-programs.txt
The PR aims to add a cuML section to the third-party-programs file.
> Update TPP file with cuML

- cpp/oneapi/dal/table/csr.cpp
- cpp/oneapi/dal/table/csr.hpp
- cpp/oneapi/dal/table/detail/table_utils.cpp
- cpp/oneapi/dal/table/detail/table_utils.hpp
- cpp/oneapi/dal/table/test/csr.cpp
This PR adds the copy constructor and the respective test.
> Implement copy constructor for csr_table class

- third-party-programs.txt
The PR reflects the most recent changes in the oneDAL 3rd parties.
> Update TPP file according to the recent changes

- .github/renovate.json
> Monthly doc package updates

- examples/oneapi/cpp/source/example_util/output_helpers.hpp
- examples/oneapi/cpp/source/table/csr_table.cpp
- examples/oneapi/cpp/source/table/heterogen_table.cpp
- examples/oneapi/cpp/source/table/homogen_table.cpp
- examples/oneapi/dpc/source/example_util/array_helpers.hpp
- examples/oneapi/dpc/source/example_util/dpc_helpers.hpp
- examples/oneapi/dpc/source/example_util/output_helpers.hpp
- examples/oneapi/dpc/source/table/csr_table.cpp
- examples/oneapi/dpc/source/table/heterogen_table.cpp
- examples/oneapi/dpc/source/table/homogen_table.cpp
> Table examples

- cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_fast_batch_fpt_cpu.cpp
- cpp/daal/src/algorithms/low_order_moments/moments_batch.h
- cpp/oneapi/dal/algo/basic_statistics/backend/cpu/compute_kernel.cpp
- cpp/oneapi/dal/algo/basic_statistics/test/fixture.hpp
> Basic statistics nightly CI hotfix

- cpp/oneapi/dal/table/BUILD
- cpp/oneapi/dal/table/backend/csr_table_builder_impl.hpp
- cpp/oneapi/dal/table/detail/table_builder.cpp
- cpp/oneapi/dal/table/detail/table_builder.hpp
- cpp/oneapi/dal/table/detail/table_iface.hpp
- cpp/oneapi/dal/table/detail/test/csr_utils.cpp
Implement detail::csr_table_builder class that works on host.
> Add initial implementation for  detail::csr_table_builder

- cpp/oneapi/dal/table/backend/csr_table_builder_impl.hpp
- cpp/oneapi/dal/table/detail/table_builder.hpp
- cpp/oneapi/dal/table/detail/table_iface.hpp
- cpp/oneapi/dal/table/detail/test/csr_utils.cpp
Add ability to build CSR tables from USM-allocated data.
> Add GPU support in detail::csr_table_builder class

- cpp/oneapi/dal/algo/kmeans/backend/cpu/infer_kernel.cpp
- cpp/oneapi/dal/algo/kmeans/backend/gpu/infer_kernel_dpc.cpp
- cpp/oneapi/dal/algo/kmeans/common.cpp
- cpp/oneapi/dal/algo/kmeans/common.hpp
- cpp/oneapi/dal/algo/kmeans/detail/infer_ops.hpp
- cpp/oneapi/dal/algo/kmeans/infer_types.cpp
- cpp/oneapi/dal/algo/kmeans/infer_types.hpp
- cpp/oneapi/dal/algo/kmeans/test/badarg.cpp
- cpp/oneapi/dal/algo/kmeans/test/batch.cpp
- cpp/oneapi/dal/algo/kmeans/test/fixture.hpp
- examples/oneapi/dpc/source/kmeans/kmeans_lloyd_dense_batch.cpp
Adding optional results to align predict behavior between scikit-learn-intelex and daal4py
> feature: adding optional results in kmeans infer

- docs/requirements.txt
Updates to jinja2 3.1.3 to avoid potential vulnerability
> [deps] upgrade jinja

- cpp/daal/src/algorithms/optimization_solver/coordinate_descent/coordinate_descent_types_fpt.cpp
Coverity hit associated with useless branching.
> Remove useless branching

- cpp/daal/src/algorithms/dtrees/dtrees_train_data_helper.i
- cpp/daal/src/algorithms/dtrees/forest/df_train_dense_default_impl.i
Pr contains fixes for coverity in Decision Forest algorithm
> fix: forest coverity issues

- cpp/oneapi/dal/partial_compute.hpp
- samples/oneapi/dpc/ccl/sources/cov_online_distr_ccl.cpp
- samples/oneapi/dpc/mpi/sources/cov_online_distr_mpi.cpp
Pr contains the fix for nightly job + removing definition of partial compute(comm version)
> fix: distributed online covariance samples fix

- .ci/scripts/build.sh
- .github/workflows/docker-validation-nightly.yml
- .github/workflows/renovate-validation.yml
> CI: fix docker nightly

- .ci/env/apt.sh
- WORKSPACE
- dev/download_micromkl.bat
- dev/download_micromkl.sh
Cherry pick commits from main.
> Update mkl fpk GPU and compiler version for 2024.2.0

- cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_fp_impl.hpp
- cpp/oneapi/dal/backend/primitives/selection/kselect_by_rows_heap_dpc.cpp
- cpp/oneapi/dal/backend/primitives/selection/kselect_by_rows_simd.hpp
- cpp/oneapi/dal/backend/primitives/selection/kselect_by_rows_single_col.hpp
- cpp/oneapi/dal/backend/primitives/selection/row_partitioning_kernel.hpp
- cpp/oneapi/dal/backend/primitives/sort/sort_dpc.cpp
> FIX: sycl barrier() deprecation alternative

- cpp/oneapi/dal/io/csv/backend/cpu/read_kernel.cpp
- cpp/oneapi/dal/io/csv/backend/cpu/read_kernel.hpp
- cpp/oneapi/dal/io/csv/backend/gpu/read_kernel.hpp
- cpp/oneapi/dal/io/csv/backend/gpu/read_kernel_dpc.cpp
- cpp/oneapi/dal/io/csv/common.hpp
- cpp/oneapi/dal/io/csv/detail/read_ops.cpp
- cpp/oneapi/dal/io/csv/detail/read_ops.hpp
- cpp/oneapi/dal/io/csv/detail/read_ops_dpc.cpp
- examples/oneapi/cpp/BUILD
- examples/oneapi/cpp/source/misc/read_batch.cpp
- examples/oneapi/dpc/BUILD
- examples/oneapi/dpc/source/dbscan/dbscan_brute_force_batch.cpp
- examples/oneapi/dpc/source/misc/read_batch.cpp
- Ability to set data type in read function for tables
> Feature: Data type support in read function

- .github/renovate.json
Change frequency of dockerfile updates to monthly
> MAINT: monthly dockerfile updates

- docs/source/daal/algorithms/quality_metrics/default/for-multi-class-classification.rst
The PR addresses an error raised by the Sphinx generator.
> Fix a misprint for Sphinx generator

- samples/oneapi/dpc/ccl/sources/pca_online_distr_ccl.cpp
- samples/oneapi/dpc/mpi/sources/pca_online_distr_mpi.cpp
> fix: online distr PCA samples

- deploy/local/dal
The PR addresses the most recent changes in the modulefile.
> Adjust modulefile

- cpp/oneapi/dal/detail/cpu_info_impl.cpp
Cherry-picking the changes from main branch.
> Fix coverity 'invalid iterator' failure (#2766)

- README.md
- Update `README.md` with new UXL identity according to [#66](https://github.com/uxlfoundation/open-source-working-group/issues/66)
- https://github.com/uxlfoundation/open-source-working-group/issues/66
> docs: update `README.md` with UXL identity

- docs/requirements.txt
The PR aims to address `requests` lib issue caught by dependabot.
> Update requests version

- README.md
- Updated `Installation` section with another ways
- https://github.com/uxlfoundation/open-source-working-group/issues/43#issue-2202438296
> docs: update `Installation` section in `README.md`

- CONTRIBUTING.md
- README.md
This PR improves  documentation details to comply with UXL expectations
- Listing maintainers in contributing section. @keeranroth  @rakshithgb-fujitsu  - added as contact points
- Adding link to slack channel
- Update wording on expected bazel validation and linking bazel guide
> How to contact maintainers + some clarifications

- cpp/daal/include/services/env_detect.h
- cpp/daal/src/externals/core_threading_win_dll.cpp
- cpp/daal/src/services/env_detect.cpp
- cpp/daal/src/threading/service_thread_pinner.cpp
- cpp/daal/src/threading/threading.cpp
- cpp/daal/src/threading/threading.h
Cherry-picking the changes related to TBB fix from 2024.5 to 2024.6 branch.
> Adding TBB scheduler handle

- .ci/env/environment.yml
> CI: conda fixes for public CI

- deploy/local/dal
The PR aims to address issues with the modulefile discovered within the latest test sessions.
> Adjust modulefile according to the latest requirements

- deploy/local/dal
The PR aims to adjust modulefile according to the latest requirements
> Adjust modulefile according to the latest requirements (#2823)

- .ci/pipeline/ci.yml
Follow up to #2842. Feel free to merge if Linuxdaal4py python311 step turns green.
> CI: remove intel channel from public CI

- .ci/env/apt.sh
> update qemu debian emulation version

- .ci/env/apt.sh
version 9.0.1 was removed, using a slightly older version to avoid frequent update.
-
-
-
> qemu version change

- .ci/pipeline/ci.yml
> CI: LinuxSklearnex missing MPI resolution

- cpp/daal/src/algorithms/implicit_als/implicit_als_predict_ratings_result_fpt.cpp
- cpp/daal/src/algorithms/linear_model/linear_model_predict_batch_fpt.cpp
- cpp/daal/src/algorithms/normalization/minmax/minmax_fpt.cpp
- cpp/daal/src/algorithms/pca/pca_result_fpt.cpp
- cpp/daal/src/algorithms/pca/transform/pca_transform_batch_fpt.cpp
- cpp/daal/src/algorithms/svd/svd_dense_default_batch_fpt.cpp
- cpp/daal/src/algorithms/svd/svd_dense_default_online_fpt.cpp
Fixes for some symbols in d4p build.
> fix: add new DAAL_EXPORT macros for ICX support

- deploy/pkg-config/pkg-config.tpl
- dev/bazel/config/config.bzl
- docs/doxygen/doxygen_conf_cpp.txt
- docs/doxygen/doxygen_conf_cpp_examples.txt
- docs/doxygen/doxygen_conf_cpp_web.txt
- makefile.ver
Upgrade oneDAL to build as 2025.0
- update makefile.ver
- update bazel configuration
- update documentation
- update deployment package tpl file
> Update to 2025.0.0 version

- .ci/env/apt.sh
> CI: Add more qemu versions

- cpp/daal/src/algorithms/elastic_net/elastic_net_training_result_fpt.cpp
- cpp/daal/src/algorithms/lasso_regression/lasso_regression_training_result_fpt.cpp
- cpp/daal/src/algorithms/normalization/zscore/zscore_fpt.cpp
- cpp/daal/src/algorithms/pca/pca_partialresult_correlation_fpt.cpp
- cpp/daal/src/algorithms/pca/pca_partialresult_svd.h
- cpp/daal/src/algorithms/pca/pca_partialresult_svd_fpt.cpp
- cpp/daal/src/algorithms/pca/pca_result_fpt.cpp
- cpp/daal/src/algorithms/svd/svd_dense_default_distr_step2.h
- cpp/daal/src/algorithms/svd/svd_dense_default_distr_step2_fpt.cpp
- cpp/daal/src/algorithms/svd/svd_dense_default_distr_step3.h
- cpp/daal/src/algorithms/svd/svd_dense_default_distr_step3_fpt.cpp
> fix: adding daal exports for vc compiler

- MAINTAINERS.md
_Add a comprehensive description of proposed changes_
_List associated issue number(s) if exist(s): #6 (for example)_
_Documentation PR (if needed): #1340 (for example)_
_Benchmarks PR (if needed): https://github.com/IntelPython/scikit-learn_bench/pull/155 (for example)_
---
**Testing**
> Add copyright to MAINTAINERS

- .github/workflows/pr-checklist.yml
Changes:
- Explicitly declare permissions of PR checklist workflow
- Skip this check for PRs from `renovate`
- Add trigger for draft state changes of PR.
---
**Testing**
> Fixes for PR checklist workflow

- .github/workflows/nightly-build.yml
Made a mistake in #2938
---
**Testing**
> [fix] Correct VC naming in nightly-build.yml

- cpp/oneapi/dal.hpp
- cpp/oneapi/dal/algo/finiteness_checker.hpp
introduced in #2781, the root header file for the algorithm was forgotten. This corrects that mistake.
---
**Testing**
> [fix] add missing headers for finiteness_checker algorithm

- .github/workflows/nightly-build.yml
TBB must also be loaded to properly build oneDAL, this modifies the vars setting to include TBB as was done in #2958
---
**Testing** …
> [CI] fix Nightly-build following on #2958

- .ci/pipeline/ci.yml
- .github/workflows/nightly-build.yml
_Add a comprehensive description of proposed changes_
_List associated issue number(s) if exist(s): #6 (for example)_
_Documentation PR (if needed): #1340 (for example)_
_Benchmarks PR (if needed): https://github.com/IntelPython/scikit-learn_bench/pull/155 (for example)_
---
For example, PR with docs update doesn't require checkboxes for performance while PR with any change in actual code should have checkboxes and justify how this code change is expected to affect performance (or …
> [CI] Windows basekit upgrade 2025.0

- INSTALL.md
This PR updates the installation instructions for building oneDAL from source after the last changes in dependencies that have happened, and replaces dead links with more current ones.
---
**Testing**
> DOC: Update instructions for installing from source

- README.md
Updated the link for the build status badge to a valid URL.
---
> docs: update build status badge link in `README.md`

- INSTALL.md
Command as it is in the docs is not always accepted by all shells. This PR switches it to a more universal form.
---
**Testing** …
> DOC: Fix command for installing conda dependencies

- docs/source/contribution/ideas.rst
- docs/source/index-toc.rst
This PR adds a few ideas for oneDAL/sklearnex enhancements that I had and which are good candidates for getting started with development of this library.
It copy-pastes the classification system introductory paragraphs from this other PR in sklearnex:
https://github.com/uxlfoundation/scikit-learn-intelex/pull/2297
---
For example, PR with docs update doesn't require checkboxes for performance while PR with any change in actual code should have checkboxes and justify how this code …
> DOC: Add list of ideas for potential contributors

- .github/.licenserc.yaml
- .github/pull_request_template.md
I found this highly annoying and fixed it, this matches uxlfoundation/scikit-learn-intelex#2223
---
**Testing**
> [CI] Remove license header from PR template

- .github/workflows/docs-release.yml
This PR intends to add doc automation trigger by release tag for onedal
**Testing**
> feature: doc automation for onedal

- INSTALL.md
- makefile
The gcov code coverage tool support was integrated in #3010. However, it was not documented for general use. This PR adds the necessary documentation to the makefile help and INSTALL.md to allow for general use, and for general documentation of features that exist.
Performance benchmarks unnecessary.
---
For example, PR with docs update doesn't require checkboxes for performance while PR with any change in actual code should have checkboxes and justify how this code change is …
> [docs] add missing documentation of gcov support from #3010

- .ci/env/openblas.sh
- .github/renovate.json
Update openblas to latest
---
**Testing**
> [CI] Update openBLAS to v0.3.29

- cpp/daal/include/algorithms/qr/qr_distributed.h
Remove a dead line of code that's impossible to reach.
> fix: remove dead code

- deploy/local/dal
- deploy/local/vars_lnx.sh
- deploy/local/vars_mac.sh
- deploy/local/vars_win.bat
- docs/source/get-started/build-and-run-examples.rst
_Add a comprehensive description of proposed changes_
_List associated issue number(s) if exist(s): #6 (for example)_
_Documentation PR (if needed): #1340 (for example)_
_Benchmarks PR (if needed): https://github.com/IntelPython/scikit-learn_bench/pull/155 (for example)_
---
For example, PR with docs update doesn't require checkboxes for performance while PR with any change in actual code should have checkboxes and justify how this code change is expected to affect performance (or …
> replace CPATH variable with CPLUS_INCLUDE_PATH

- README.md
- docs/source/get-started/prerequisites.rst
- docs/source/installation.rst
This PR fixes the doc section about installation instructions (which currently points to non-existent binary releases in github) to show the same potential mediums as the readme file.
---
Checklist to comply with **before moving PR from …
> DOC: Correct installation instructions

- docs/source/installation.rst
Small amendment to previous PR https://github.com/uxlfoundation/oneDAL/pull/3205 which left one substitution unrendered.
---
**Testing**
> DOC: Fix misrendered substitution

- cpp/oneapi/dal/backend/primitives/objective_function/logloss_functors_dpc.cpp
- cpp/oneapi/dal/backend/primitives/objective_function/test/fixture.hpp
- cpp/oneapi/dal/backend/primitives/optimizers/line_search_dpc.cpp
- cpp/oneapi/dal/backend/primitives/optimizers/newton_cg_dpc.cpp
- cpp/oneapi/dal/backend/primitives/optimizers/test/cg_solver_dpc.cpp
- cpp/oneapi/dal/backend/primitives/optimizers/test/fixture.hpp
- cpp/oneapi/dal/backend/primitives/optimizers/test/newton_cg_dpc.cpp
This PR address multiple issues in computation of logistic loss and newton-cg optimization process:
- Issue with logloss computation in logloss_function class is fixed, additional tests were added
- Issue with incorrect sign of precomputed gradient provided to backtracking algorithm is fixed
- Additional stopping criteria is added to newton-cg algorithm
- Tolerance for solution vector is raised a little bit
- Additional test is added to compare the value at the optimal point and in the orginal point
---
**Testing**
> Fix issues with Logistic Regression and Newton-CG

- INSTALL.md
This PR adds instructions for executing the auto-generated examples with ASAN when the library is built with it, as it's not very obvious how to do so.
--- …
> DOC: Add instructions for executing examples with ASAN

- .github/workflows/ci-aarch64.yml
This changes one of the arm runners to build and test with clang instead of gnu to reduce duplication. 
no perf benchmarks necessary.
--- …
> [CI, enhancement] Switch an arm github actions runner to clang build

- .github/workflows/ci.yml
In newer versions of the gpu driver the DisableScratchPages setting is set to false by default.
---
**Testing**
> Updating DisableScratchPages setting 

- .ci/env/apt.sh
- .github/.abignore
Companion to #3164 which updates the Linux DPCPP and MKL versions from 2025.0 to 2025.1 and TBB to 2022.1 when installed by apt.
This also adds an ignore for ```tbb::``` namespaces as recommended here: https://github.com/uxlfoundation/oneDAL/pull/3225#issuecomment-2909494747
Performance benchmarks not necessary.
---
For example, PR with docs update doesn't require checkboxes for performance while PR with any change in actual code should have checkboxes and justify how this code …
> [CI] Update apt Linux MKL and DPCPP 2025.1, TBB 2022.1

- .github/workflows/docs-release.yml
Backport of https://github.com/uxlfoundation/oneDAL/pull/3212
> MAINT: Backport GH action for automated doc deployments

- README.md
- docs/source/index.rst
This PR provides a more descriptive introduction of what oneDAL does, which is not very clear at first sight from the landing pages of GH and docs.
--- …
> DOC: Better description of what oneDAL does

- README.md
- docs/source/examples.rst
This PR updates a few links that have moved domains.
---
**Testing**
> FIX: Update links that have moved

- README.md
This PR removes the note about the licensing of MKL FPK at the end of the readme, since it's no longer in usage.
---
**Testing**
> DOC: Remove note about MKL FPK

- MODULE.bazel
Remove `http_archive` rule.
---
**Testing**
> bazel http_archive removing

- cpp/daal/src/algorithms/objective_function/logistic_loss/logistic_loss_dense_default_batch_impl.i
- cpp/daal/src/externals/service_blas.h
- cpp/daal/src/externals/service_blas_declar_ref.h
- cpp/daal/src/externals/service_blas_mkl.h
- cpp/daal/src/externals/service_blas_ref.h
This PR improves the numerical precision of the logistic loss function by splitting the term into separate parts that are then multiplied and summed as needed.
---
**PR completeness …
> ENH: Improve numerical precision of logistic function

- cpp/daal/include/algorithms/qr/qr_distributed.h
PR removes code that cannot be reached due to presence of an if-else where both branches return.
---
<details>
**Testing**
</details>
> MAINT: Remove unreachable code

- cpp/daal/src/services/service_profiler.h
Class destructors are implicit 'noexcept'. The profiler logic uses destructors as a form of calling functions, but these destructors then do operations that can throw exceptions. This PR catches the exceptions and logs them, in order to avoid undefined behavior.
---
<details>
**Testing**
</details>
> FIX: Catch exceptions thrown during destructor calls
