uxlfoundation/oneDAL

- algorithms/kernel/dtrees/gbt/gbt_train_updater.i
Fixed typos leading to incorrect impurity decrease computation and incorrect early stop which reduces final accuracy.
> Fixed impurity decrease computation in GBT.

- include/algorithms/kmeans/kmeans_batch.h
- include/algorithms/kmeans/kmeans_distributed.h
- include/algorithms/kmeans/kmeans_init_batch.h
- include/algorithms/kmeans/kmeans_init_distributed.h
- include/algorithms/kmeans/kmeans_init_types.h
- include/algorithms/kmeans/kmeans_types.h
Changes in doxygen comments for K-Means header files:
- Removed wrong references "See section..."
- Removed all the articles before "K-Means algorithm"
> Edited K-Means doxy comments

- algorithms/kernel/assocrules/assoc_rules_apriori_mine_impl.i
If not ok, then we should read status first, after than we should remove object. Not vice-verse.
> Fix nullptr dereference if not ok

- include/algorithms/linear_regression/linear_regression_model_builder.h
- include/algorithms/logistic_regression/logistic_regression_model_builder.h
- include/algorithms/multi_class_classifier/multi_class_classifier_model_builder.h
- include/data_management/data_source/modifiers/csv/internal/default_modifiers.h
I spotted several places where using throwIfPossible leads to unexpected behaviour if exceptions are: disabled(3 places, 2 files with +return); enabled(shall we release block in this case). 
But I'm not quite sure. Could you please help me figure out ;)
> throwIfPossible usage flaws fix

- README.md
Fix broken link for DAL documentation  to http://intel.github.io/daal/
You can check that link works here - https://github.com/napetrov/daal/tree/fix_doc_link
> fix link for oneDAL documentation

- algorithms/kernel/logistic_regression/logistic_regression_predict_container.h
- algorithms/kernel/logistic_regression/oneapi/logistic_regression_predict_dense_default_batch_oneapi_impl.i
- algorithms/kernel/objective_function/logistic_loss/oneapi/cl_kernel/logistic_loss_dense_default.cl
- algorithms/kernel/objective_function/logistic_loss/oneapi/logistic_loss_dense_default_kernel_oneapi.h
- algorithms/kernel/objective_function/logistic_loss/oneapi/logistic_loss_dense_default_oneapi_impl.i
In the old version of binary logistic regression for GPU, users can get a probability of the only positive label ("1"). Here I aligned the behavior of this classifier with all other: User can get the probabilities for both two class labels ("0" and "1")
**Private CI**: [link](https://ecmd.inn.intel.com/commander/link/jobDetails/jobs/ea09e3ef-5088-f1d7-bdf6-8cdcd4b723a1?)
> Fix of probabilities calculation in binary log regression

- algorithms/kernel/dtrees/dtrees_feature_type_helper.i
- algorithms/kernel/dtrees/gbt/classification/gbt_classification_train_dense_default_impl.i
- algorithms/kernel/dtrees/gbt/gbt_train_aux.i
- algorithms/kernel/dtrees/gbt/gbt_train_dense_default_impl.i
- algorithms/kernel/dtrees/gbt/gbt_train_tree_builder.i
- algorithms/kernel/dtrees/gbt/regression/gbt_regression_train_dense_default_impl.i
GBT performance optimizations for specific dimensions. Change of GBT initialization behavior on small number of rows.
- Threading in Squared Loss and Log Loss, TreeBuilder of GBT.
- Change of GBT initialization to avoid early switch to factually exact split mode if maxBins*minBinSize < nRows.
> Gradient Boosted Trees performance optimizations

- include/data_management/data/csr_numeric_table.h
We should check the first argument before invoke the `getVectorUpCast` function. We can't apply UpCast to _Other_ type.
> Check arguments of getVectorUpCast function

- scripts/tbb.bat
- scripts/tbb.sh
Fixes for helper scripts.
- "tbb.{sh,bat} do tbb download even if tbb already downloaded." - Fixed.
- TBB location fixed on Windows to be able to build DAAL
> helper scripts fixed

- examples/cpp_sycl/makefile_lnx
- examples/cpp_sycl/makefile_win
- examples/cpp_sycl/vcproj/bf_knn_dense_batch/bf_knn_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/cor_dense_batch/cor_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/cor_dense_online/cor_dense_online.vcxproj
- examples/cpp_sycl/vcproj/datastructures_soa/datastructures_soa.vcxproj
- examples/cpp_sycl/vcproj/datastructures_usm/datastructures_usm.vcxproj
- examples/cpp_sycl/vcproj/gbt_reg_dense_batch/gbt_reg_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/kmeans_dense_batch/kmeans_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/kmeans_init_dense_batch/kmeans_init_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/lin_reg_norm_eq_dense_batch/lin_reg_norm_eq_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/log_reg_binary_dense_batch/log_reg_binary_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/log_reg_dense_batch/log_reg_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/low_order_moms_dense_batch/low_order_moms_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/low_order_moms_dense_online/low_order_moms_dense_online.vcxproj
- examples/cpp_sycl/vcproj/pca_cor_dense_batch/pca_cor_dense_batch.vcxproj
- examples/cpp_sycl/vcproj/sgd_mini_log_loss_dense_batch/sgd_mini_log_loss_dense_batch.vcxproj
- include/oneapi/internal/math/blas_executor.h
- include/oneapi/internal/math/lapack_executor.h
Macro **ONEAPI_DAAL_USE_MKL_GPU_FUNC** was replaced by **ONEAPI_DAAL_NO_MKL_GPU_FUNC** with inversing of benaviour. MKL functions are used by default now.
It is fix isuue #245
> MKL functions are enabled by default

- CONTRIBUTING.md
`withoutElse` option is available only since 9.0.0 clang format.
In other ways:
```
YAML:18:38: error: invalid boolean
AllowShortIfStatementsOnASingleLine: WithoutElse
```
> Add a note about minimal ClangFormat version

- algorithms/kernel/adaboost/adaboost_predict_dense_default_batch_fpt_cpu.cpp
- algorithms/kernel/adaboost/adaboost_predict_impl.i
- algorithms/kernel/adaboost/adaboost_predict_kernel.h
Fixed:
- hidden nested threader_for that causes incorrect results
- removed unnecessary includes
> Fix of sporadic adaboost multiclass samme java example

- algorithms/kernel/adaboost/adaboost_predict_dense_default_batch_fpt_cpu.cpp
- algorithms/kernel/adaboost/adaboost_predict_impl.i
- algorithms/kernel/adaboost/adaboost_predict_kernel.h
Fixed:
- hidden nested threader_for that causes incorrect results
- removed unnecessary includes
> Fix of sporadic adaboost multiclass samme java example [to releases branch]

- algorithms/kernel/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
- include/algorithms/algorithm_container_base_batch.h
- include/algorithms/decision_forest/decision_forest_classification_training_types.h
- include/algorithms/decision_forest/decision_forest_regression_training_types.h
- include/algorithms/k_nearest_neighbors/bf_knn_classification_model.h
- include/algorithms/kernel_function/kernel_function.h
- include/algorithms/lasso_regression/lasso_regression_training_batch.h
- include/algorithms/optimization_solver/iterative_solver/iterative_solver_types.h
- include/data_management/data/data_archive.h
- include/services/daal_atomic_int.h
- include/services/env_detect.h
- include/services/error_handling.h
removed unused variables
disabled op=/cpyctors for classes w/ raw allocated pointers
fixed build(linkage) on msvc
> Code cleanup

- externals/service_dispatch.h
- include/data_management/data/internal/finiteness_checker.h
- include/services/daal_kernel_defines.h
- service/kernel/data_management/finiteness_checker.cpp
NaN/Inf checker for Numeric Tables with base and AVX512 branches for float32/64 types.
Checker has two stages:
1. Compute sum of all values and check its finiteness
2. If sum isn't finite, check finiteness of all values.
> [rls/daal-2020-mnt] Finiteness checker

- include/data_management/data/internal/finiteness_checker.h
- service/kernel/data_management/finiteness_checker.cpp
NaN/Inf checker for Numeric Tables with base and AVX512 branches for float32/64 types.
Checker has two stages:
1. Compute sum of all values and check its finiteness
2. If sum isn't finite, check finiteness of all values.
Duplicate of pull request [373](https://github.com/intel/daal/pull/373) to 2020-mnt
> [releases] Finiteness checker

- include/data_management/data/soa_numeric_table.h
Fix for SOA optimizations(https://github.com/intel/daal/pull/422) to be able to build examples with pedantic mode(https://github.com/intel/daal/pull/435).
> Fix for soa optimizations

- makefile
- scripts/mklfpk.bat
- scripts/mklfpk.sh
In case we try to install mklfpk at the same place for another system we receive message that mklfpk was already installed. To avoid that situation we may put each mklfpk in its own folder with name of system they are installed.
> fix helper scripts

- makefile
- scripts/mklfpk.bat
- scripts/mklfpk.sh
In case we try to install mklfpk at the same place for another system we receive message that mklfpk was already installed. To avoid that situation we may put each mklfpk in its own folder with name of system they are installed.
Cherry-pick of https://github.com/intel/daal/pull/452
> [releases] fix helper scripts

- docs/source/bibliography.rst
- docs/source/conf.py
- docs/source/dev_guide/algorithms/dbscan/computation-batch.rst
- docs/source/dev_guide/algorithms/dbscan/computation-distributed.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/includes/default_result_data_collection.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/includes/default_result_numeric_table.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/includes/input_data_collection.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/includes/input_data_collection_with_exceptions.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/includes/input_numeric_table.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/includes/parameters.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/includes/parameters_blocks.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/includes/parameters_blocks_left_right.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-1.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-10.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-11.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-12.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-13.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-2.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-3.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-4.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-5.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-6.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-7.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-8.rst
- docs/source/dev_guide/algorithms/dbscan/distributed-steps/step-9.rst
- docs/source/dev_guide/algorithms/dbscan/index.rst
Converted documentation for DBSCAN (see [output](https://outoftardis.github.io/daal/dev_guide/algorithms/dbscan/index.html))
> Docs for DBSCAN converted

- algorithms/kernel/linear_model/linear_model_train_qr_common_impl.i
- algorithms/kernel/linear_model/linear_model_train_qr_update_impl.i
- algorithms/kernel/linear_regression/linear_regression_training_input.cpp
Same as, but to releases: #455
The changes aim to pass arguments properly to LAPACK XORMRQ function in case n_observations < n_betas.
The results of XORMRQ are appended: R - with unit diagonal sub-matrix; QtY - with zero rows; to make the resulting linear system solvable.
CI (successful): http://intel-ci.intel.com/ea6cecf3-a379-f1a9-8625-8cdcd4b723a1
> [releases] Add ability to train linear and ridge regression with n_observations < n_beta in QR method

- algorithms/kernel/linear_model/linear_model_train_normeq_update_impl.i
- algorithms/kernel/linear_model/linear_model_train_qr_common_impl.i
- algorithms/kernel/linear_regression/linear_regression_training_input.cpp
Same as, but to rls/daal-2020-mnt: https://github.com/intel/daal/pull/455
The changes aim to pass arguments properly to LAPACK XORMRQ function in case n_observations < n_betas.
The results of XORMRQ are appended: R - with unit diagonal sub-matrix; QtY - with zero rows; to make the resulting linear system solvable.
CI (successful):  http://intel-ci.intel.com/ea6ceb77-3e57-f18f-9a61-8cdcd4b723a1
> [rls/daal-2020-mnt] Add ability to train linear and ridge regression with n_observations < n_beta in QR method

- algorithms/kernel/pca/transform/pca_transform_dense_default_batch_impl.i
A bug which was a reason of PCA Transform degradation with SOA tables has been fixed
> [master] PCA Transform Bug Fix

- algorithms/kernel/pca/transform/pca_transform_dense_default_batch_impl.i
A bug which was a reason of PCA Transform degradation with SOA tables has been fixed
> [releases] PCA Transform Bug Fix

- algorithms/kernel/pca/transform/pca_transform_dense_default_batch_impl.i
A bug which was a reason of PCA Transform degradation with SOA tables has been fixed
> [daal-2020-mnt] PCA Transform Bug Fix

- examples/cpp_sycl/makefile_lnx
- examples/cpp_sycl/makefile_win
Currently icc and gnu compilers supported only together with computeCPP compiler that we have been used at initial stages of oneDAL development. 
We never supported this configuration officially and now removing remaining parts of it's usage.
> Removing icc and gnu compiler usage from sycl_examples

- algorithms/kernel/pca/pca_input.cpp
- algorithms/kernel/svd/svd_dense_default_batch_impl.i
- algorithms/kernel/svd/svd_dense_default_distr_step2_impl.i
- algorithms/kernel/svd/svd_dense_default_distr_step3_impl.i
- algorithms/kernel/svd/svd_dense_default_impl.i
- algorithms/kernel/svd/svd_distr_step3_input.cpp
- algorithms/kernel/svd/svd_input.cpp
- algorithms/kernel/svd/svd_online_partial_result.cpp
Input checks for n_observations >= n_features were removed in svdDense method in PCA.
SVD algorithm was modified to let it work with n_observations < n_features in batch, online and distributed compute modes.
SVD is computed using QR decomposition, so I've changed the code of QR decomposition to let it pack the resulting R matrix properly when n_observations < n_features.
Successful CI: http://intel-ci.intel.com/ea734df7-9982-f136-ac5c-8cdcd4b723a1
> [master] Add ability to use PCA with svdDense method if n_observations < n_features

- algorithms/kernel/linear_model/oneapi/linear_model_predict_dense_default_batch_oneapi_impl.i
Small fix of ```BlasGpu<algorithmFPType>::xgemm``` call signature. The value "1" in this context should be ```uint32_t```, not ```algorithmFPType```.
> Fix of xgemm call.

- docs/source/dev_guide/algorithms/svd/singular-value-decomposition.rst
SVD algorithm was modified recently. Now it can process input data set with any positive number of rows, so I removed the restriction on the number of rows from the docs.
> [master] Docs: Removed the restrictions on input dataset size in SVD algorithm

- examples/cpp/makefile_lnx
- include/algorithms/boosting/adaboost_model.h
- include/algorithms/classifier/classifier_model.h
- include/algorithms/dbscan/dbscan_types.h
- include/algorithms/elastic_net/elastic_net_training_types.h
- include/algorithms/gradient_boosted_trees/gbt_training_parameter.h
- include/algorithms/lasso_regression/lasso_regression_training_types.h
- include/algorithms/normalization/minmax_types.h
- include/algorithms/normalization/zscore_types.h
- include/algorithms/optimization_solver/adagrad/adagrad_types.h
- include/algorithms/optimization_solver/coordinate_descent/coordinate_descent_types.h
- include/algorithms/optimization_solver/lbfgs/lbfgs_types.h
- include/algorithms/optimization_solver/objective_function/objective_function_types.h
- include/algorithms/optimization_solver/objective_function/sum_of_functions_types.h
- include/algorithms/optimization_solver/saga/saga_types.h
- include/algorithms/ridge_regression/ridge_regression_training_types.h
- include/oneapi/internal/execution_context.h
- include/oneapi/internal/math/types.h
oneAPI header files are included to some classical DAAL headers, namely `env_detect.h`, because  `Environment` class depends on `ExecutionContext` that defined in `oneapi/execution_context.hpp`, where C++11 features are used.
C++11 features are removed from `oneapi/execution_context.hpp` and other oneAPI included header files.
> Remove C++11 features from oneapi headers exposed in classical DAAL

- algorithms/kernel/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch.h
- algorithms/kernel/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch_impl.i
- include/data_management/data/soa_numeric_table.h
The PR optimizes knn predict algorithm if training data set in model is represented as a homogen SOA numeric table (default behavior for C++ and only one available for IDP Sklearn).
> kNN predict optimizations

- algorithms/kernel/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch.h
- algorithms/kernel/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch_impl.i
- include/data_management/data/soa_numeric_table.h
This is a cherry-pick from #518
The PR optimizes knn predict algorithm if training data set in model is represented as a homogen SOA numeric table (default behavior for C++ and only one available for IDP Sklearn).
> [releases] kNN predict optimizations

- algorithms/kernel/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch.h
- algorithms/kernel/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch_impl.i
- include/data_management/data/soa_numeric_table.h
This is a cherry-pick from https://github.com/oneapi-src/oneDAL/pull/518
The PR optimizes knn predict algorithm if training data set in model is represented as a homogen SOA numeric table (default behavior for C++ and only one available for IDP Sklearn).
> [beta 6] kNN predict optimizations

- examples/cpp/makefile_lnx
- include/algorithms/boosting/adaboost_model.h
- include/algorithms/classifier/classifier_model.h
- include/algorithms/dbscan/dbscan_types.h
- include/algorithms/elastic_net/elastic_net_training_types.h
- include/algorithms/gradient_boosted_trees/gbt_training_parameter.h
- include/algorithms/lasso_regression/lasso_regression_training_types.h
- include/algorithms/normalization/minmax_types.h
- include/algorithms/normalization/zscore_types.h
- include/algorithms/optimization_solver/adagrad/adagrad_types.h
- include/algorithms/optimization_solver/coordinate_descent/coordinate_descent_types.h
- include/algorithms/optimization_solver/lbfgs/lbfgs_types.h
- include/algorithms/optimization_solver/objective_function/objective_function_types.h
- include/algorithms/optimization_solver/objective_function/sum_of_functions_types.h
- include/algorithms/optimization_solver/saga/saga_types.h
- include/algorithms/ridge_regression/ridge_regression_training_types.h
- include/oneapi/internal/execution_context.h
- include/oneapi/internal/math/types.h
- Remove c++11 features from oneAPI headers exposed in classical DAAL headers
- Add `-std=c++03`, `-Wno-variadic-macros`, `-Wno-long-long` for GCC 
- Fix some ISO C++ 2003 violations in DAAL headers
> Remove c++11 features from headers

- algorithms/kernel/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch.h
- algorithms/kernel/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch_impl.i
- include/data_management/data/soa_numeric_table.h
This is a cherry-pick from #518
The PR optimizes knn predict algorithm if training data set in model is represented as a homogen SOA numeric table (default behavior for C++ and only one available for IDP Sklearn).
> [daal-2020-mnt] kNN predict optimizations

- algorithms/kernel/dtrees/dtrees_feature_type_helper.i
I detected a memory leak in GBT.
This was due to the fact that the destructor of the ColIndexTaskBins object is not called.
I added a virtual destructor  for the parent ColIndexTask object to fix this.
> [master] added a virtual destructor to fix memory leak in gbt

- algorithms/kernel/dbscan/oneapi/dbscan_dense_default_batch_ucapi_impl.i
- algorithms/kernel/dbscan/oneapi/dbscan_kernel_ucapi.h
- Fixed behavior for very small datasets (nRows < 64)
- Optimized copyCoreObservations for current oneapi state
> Hot fixes for dbscan

- algorithms/kernel/logistic_regression/logistic_regression_predict_container.h
- algorithms/kernel/logistic_regression/logistic_regression_predict_dense_default_batch_oneapi_fpt.cpp
- algorithms/kernel/logistic_regression/oneapi/logistic_regression_predict_dense_default_batch_oneapi_impl.i
- algorithms/kernel/logistic_regression/oneapi/logistic_regression_predict_kernel_oneapi.h
In windows testing we have inlegal symbols in SVM Predict from Logistic Regression Predict. It changes fixed instance Logistic Regression Predict.
> Fix logreg predict instance for GPU

- README.md
- Removed:
- mentions of the `releases` branch
- info about preview features (it heavily depended on two-branch scheme) -- as soon as we have a new proposal, I'll update the readme again
- Moved TOC up and the oneDAL vs DAAL section down
- Added a link to the latest rls branch for oneDAL
> Doc readme update

- algorithms/kernel/dtrees/dtrees_feature_type_helper.i
I detected a memory leak in GBT.
This was due to the fact that the destructor of the ColIndexTaskBins object is not called.
I added a virtual destructor for the parent ColIndexTask object to fix this.
> [daal-2020-mnt] added a virtual destructor to fix memory leak in gbt

- build/cmplr.clang.mk
- build/cmplr.gnu.mk
- include/services/daal_defines.h
This minor step towards preparation to new interface integration. The change is needed to **have more or less conformant build parameters for both interfaces**.
Testing: http://intel-ci.intel.com/ea95d390-ea3e-f188-bb5e-8cdcd4b723a1
> Move definition of __int from makefile to defines

- algorithms/kernel/dtrees/forest/classification/df_classification_model.cpp
- algorithms/kernel/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
There is difference between master and rls/daal-2020-mnt branches which leads to failing serialization tests in daal4py.
> Fix for Random Forest deserialization in daal4py

- algorithms/kernel/dtrees/forest/classification/df_classification_model.cpp
- algorithms/kernel/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
There is difference between master and rls/daal-2020-mnt branches which leads to failing serialization tests in daal4py. https://github.com/oneapi-src/oneDAL/pull/603
* merge difference with mnt branch
* Fix for 32bit ssystem: without aligned memory support (#376)
Co-authored-by: ShvetsKS <33296480+ShvetsKS@users.noreply.github.com>
> [Beta 07]Fix for Random Forest deserialization in daal4py.

- algorithms/kernel/dtrees/forest/classification/df_classification_predict_dense_default_batch_fpt_dispatcher.cpp
- algorithms/kernel/dtrees/forest/classification/df_classification_train_container.h
- algorithms/kernel/dtrees/forest/classification/df_classification_train_dense_default_impl.i
- algorithms/kernel/dtrees/forest/classification/df_classification_train_dense_default_kernel.h
- algorithms/kernel/dtrees/forest/classification/df_classification_train_hist_batch_fpt_cpu.cpp
- algorithms/kernel/dtrees/forest/classification/df_classification_train_hist_batch_fpt_dispatcher.cpp
- algorithms/kernel/dtrees/forest/classification/df_classification_train_hist_batch_oneapi_fpt.cpp
- algorithms/kernel/dtrees/forest/classification/oneapi/cl_kernels/df_batch_classification_kernels.cl
- algorithms/kernel/dtrees/forest/classification/oneapi/df_classification_train_hist_kernel_oneapi.h
- algorithms/kernel/dtrees/forest/classification/oneapi/df_classification_train_hist_oneapi_impl.i
- algorithms/kernel/dtrees/forest/classification/oneapi/df_classification_tree_helper_impl.i
- algorithms/kernel/dtrees/forest/oneapi/cl_kernels/df_tree_level_build_helper_kernels.cl
- algorithms/kernel/dtrees/forest/oneapi/df_tree_level_build_helper_oneapi.h
- algorithms/kernel/dtrees/forest/oneapi/df_tree_level_build_helper_oneapi.i
- algorithms/kernel/dtrees/forest/regression/oneapi/cl_kernels/df_batch_regression_kernels.cl
- algorithms/kernel/dtrees/forest/regression/oneapi/df_regression_train_hist_kernel_oneapi.h
- algorithms/kernel/dtrees/forest/regression/oneapi/df_regression_train_hist_oneapi_impl.i
- algorithms/kernel/dtrees/forest/regression/oneapi/df_regression_tree_helper_impl.i
- examples/cpp_sycl/DAALExamples_sycl.sln
- examples/cpp_sycl/daal_lnx.lst
- examples/cpp_sycl/source/decision_forest/df_cls_dense_batch.cpp
- examples/cpp_sycl/vcproj/df_cls_dense_batch/df_cls_dense_batch.filters
- examples/cpp_sycl/vcproj/df_cls_dense_batch/df_cls_dense_batch.user
- examples/cpp_sycl/vcproj/df_cls_dense_batch/df_cls_dense_batch.vcxproj
- include/algorithms/decision_forest/decision_forest_classification_training_types.h
Added RF classifier for GPU.
Most part of the kernels are very like to regressor's. The main difference in best split calculation and classes statistic processing.
Common kernels for manipulation with nodes were moved into shared helper between classifier and regressor.
Corresponding changes in regressor (for migration into shared part) will be added a little bit later
> Added RF classifier for GPU

- algorithms/threading/threading.h
- include/data_management/data/internal/train_test_split.h
- service/kernel/data_management/finiteness_checker.cpp
- service/kernel/data_management/train_test_split.cpp
Optimizations for [train_test_split function from scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html). Includes separate branches for SOA and AOS layouts.
[daal4py pull request](https://github.com/IntelPython/daal4py/pull/215)
> [mnt] Train test split optimizations

- .ci/scripts/clang-format.sh
Enabling oneapi/dal directory for clang-format validation in CI
> Adding oneapi/dal under code format monitoring

- cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_cov.cpp
- cpp/oneapi/dal/data/array.hpp
- cpp/oneapi/dal/data/array_dpc_test.cpp
- cpp/oneapi/dal/data/array_test.cpp
- cpp/oneapi/dal/data/backend/homogen_table_impl.cpp
- cpp/oneapi/dal/data/backend/homogen_table_impl.hpp
- cpp/oneapi/dal/data/table_builder_test.cpp
- cpp/oneapi/dal/data/table_metadata.cpp
- cpp/oneapi/dal/detail/common.hpp
- cpp/oneapi/dal/detail/common_dpc.hpp
- cpp/oneapi/dal/detail/memory.hpp
- cpp/oneapi/dal/detail/memory_impl_dpc.hpp
- cpp/oneapi/dal/detail/memory_impl_host.hpp
Surprisingly, @michael-smirnov's array merge was not checked by clang-format (it was added later). Here is the fix.
> Fix clang format in master

- cpp/daal/src/algorithms/decision_tree/decision_tree_train_impl.i
- cpp/daal/src/data_management/service_numeric_table.cpp
- cpp/daal/src/data_management/service_numeric_table.h
The problem is that on Windows Intel compiler replaces the `new BlockDescritptor<T>[n]` expression with the custom compiler-generated function that allocates and initializes all `BlockDesriptor` elements in the array. The function is compiled multiple times with different compiler options and behaves as C++ `inline` that leads to ODR violation. Some versions of that function being compiled for multiple CPUs contain AVX2 instructions. When user's application (in fact, example or test system) is linked statically against DAL, the linker selects 'wrong' version of the function (the one which contains AVX2) that leads to 'illegal' instruction on old architectures.
The fix consists in moving `new BlockDescritptor<T>[n]` to separate object file that will be compiled once to satisfy ODR. …
> Fix illegal instructions on Windows

- cpp/daal/src/algorithms/dbscan/dbscan_dense_default_batch_impl.i
- cpp/daal/src/algorithms/dbscan/dbscan_kernel.h
- cpp/daal/src/algorithms/dbscan/dbscan_utils.h
- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_impl.i
- cpp/daal/src/algorithms/service_kernel_math.h
- cpp/daal/src/services/service_defines.h
Speedup relies on dimensions highly, but here are some numbers just for reference:
100k rows x nFeatures | master, ms | this PR, ms | Speedup
-- | -- | -- | --
10 | 4100 | 846 | 4.84
50 | 6160 | 1485 | 4.15
Out of scope of this PR:
- noMemSafe mode optimizations
- Distributed mode optimizations
it's quite easy to do, but need to allocate additional time for this.
> DBSCAN optimizations for CPU

- samples/daal/cpp/mpi/launcher.bat
Fix for infinite compilation of MPI samples with oneDAL built by VS2017.
Old line `call mpiicc %LFLAGS% %RESULT_DIR%\%%T.obj %LFLAGS_DAAL% -Fe%RESULT_DIR%\%%T.exe 2>&1 >> %MPI_LOGFILE%` leads to infinite compilation and error 10014 (code -42) on cancelling.
Example of failed job:
http://intel-ci.intel.com/eac15e34-a163-f19a-92ed-8cdcd4b723a1
Successful PCm with changes:
http://intel-ci.intel.com/eac4f9c0-00cd-f13e-8adb-8cdcd4b723a1
Duplicate of https://github.com/oneapi-src/oneDAL/pull/734
> MPI samples launcher fix for VS2017 [beta 08 rls]

- samples/daal/cpp/mpi/launcher.bat
Fix for infinite compilation of MPI samples with oneDAL built by VS2017.
Old line `call mpiicc %LFLAGS% %RESULT_DIR%\%%T.obj %LFLAGS_DAAL% -Fe%RESULT_DIR%\%%T.exe 2>&1 >> %MPI_LOGFILE%` leads to infinite compilation and error 10014 (code -42) on cancelling.
Example of failed job:
http://intel-ci.intel.com/eac15e34-a163-f19a-92ed-8cdcd4b723a1
Successful PCm with changes:
http://intel-ci.intel.com/eac4f9c0-00cd-f13e-8adb-8cdcd4b723a1
> MPI samples launcher fix for VS2017

- cpp/daal/src/externals/service_blas_mkl.h
- cpp/daal/src/externals/service_lapack_mkl.h
- cpp/daal/src/externals/service_spblas_mkl.h
- cpp/daal/src/externals/service_stat_rng_mkl.h
- dev/make/cmplr.icc.mk
* fix of spark and hadoop launcher scripts
* remove tbb deprecated header
* remove ssse3 for mac
* lapack defines for mac fix
* fix other mkl macroses
Co-authored-by: konstantin.nektyagaev @teabagk7
> [beta08] Remove sse3 on mac (#740)

- algorithms/kernel/dtrees/gbt/gbt_train_dense_default_impl.i
We found that using observationsPerTreeFraction <1.0 leads to some very wrong predictions.
After some research, it became clear that the reason for this is incorrectly built trees.
At the first iteration, the initial estimation of y is initialized by single value: sum (column) / nRows.
The final step is updating the values ​​of this estimation for OOB objects. At the first iteration, this value is obtained sum (column) / nRows + inc. This leads to a very large value of OOB objects, which leads to the incorrect construction of subsequent trees.
I believe that the best way to fix this is to initialize the current estimation of y for OOB objects with zeros in the first iteration.
> [mnt] fix observationsPerTreeFraction in GBT regression

- docs/source/dev_guide/algorithms/kernel_function/kernel-functions.rst
- docs/source/dev_guide/algorithms/svm/support-vector-machine-classifier.rst
- docs/source/dev_guide/algorithms/svm_multi_class/multi-class-classifier.rst
1. Update reference for multiclass & svm for example
2. Add reference dpc++ examples for Kernel Functions
3. Add info for thunder method for CPU
4. Fix name typo `ComputationMode`->`computationMode` for Kernel Functions and default parameter `sigma=0`->`sigma=1.0` (mathematically `sigma` cannot be 0) for RBF. Need apply same here: [DevGuide](https://software.intel.com/content/www/us/en/develop/documentation/daal-programming-guide/top/algorithms/analysis/kernel-functions/radial-basis-function-kernel/batch-processing-19.html)
5. Add daal4py examples for SVM
> Update reference for example in docs & fix minor mistakes

- externals/service_rng.h
- externals/service_rng_mkl.h
- include/data_management/data/internal/train_test_split.h
- service/kernel/data_management/train_test_split.cpp
Optimization of indices shuffling for scikit-learn train_test_split function.
Duplication of https://github.com/oneapi-src/oneDAL/pull/677
> [2020-mnt] Optimization for train_test_split indices shuffling

- docs/source/build_app/build-application.rst
- docs/source/topics/build-examples.rst
- Updated paths to examples
- Fixed a typo in the name of the lib file
> [DOC] Fixed paths to examples

- cpp/daal/src/algorithms/multiclassclassifier/multiclassclassifier_predict_votebased_impl.i
- cpp/daal/src/algorithms/multiclassclassifier/multiclassclassifier_train_oneagainstone_impl.i
- cpp/daal/src/algorithms/multiclassclassifier/multiclassclassifier_train_oneagainstone_kernel.h
- cpp/daal/src/algorithms/svm/svm_predict_impl.i
- cpp/daal/src/data_management/service_numeric_table.h
1. Fix allocation for training CSR multiclass: `nSubsetVectors =classLabelsCount[nClasses - 1] + classLabelsCount[nClasses - 2];`
2. Fix vote predict for CSR multiclass - need to set offset indices between rows correctly
> Fix count subvectors for multiclass SVM for CSR data

- cpp/daal/src/data_management/finiteness_checker.cpp
- cpp/daal/src/externals/core_threading_win_dll.cpp
- cpp/daal/src/threading/threading.cpp
- cpp/daal/src/threading/threading.h
New versions of ```computeSum()``` and ```checkFiniteness()``` have been created for SOA tables
> [master] Removing conversions for SOA tables in Finite Check

- cpp/oneapi/dal/util/type_traits.hpp
fix of misprint in variable name (it causes issue that oob_error_per_observation table isn't generated)
> fix of misprint in variable name

- .mergify.yml
In this change we enable mergify configuration to use 'backport-2020' and 'backport-2021' to be used for automatic backport PRs creation
https://doc.mergify.io/examples.html#using-labels-to-backport-pull-requests
> enable initial mergify config for labels

- .ci/pipeline/ci.yml
In this change we are enabling public CI for non master branches
> enable public CI for rls branches

- cpp/oneapi/dal/algo/kmeans_init/backend/cpu/compute_kernel.hpp
- cpp/oneapi/dal/algo/kmeans_init/backend/cpu/compute_kernel_dense.cpp
- cpp/oneapi/dal/algo/kmeans_init/backend/gpu/compute_kernel.hpp
- cpp/oneapi/dal/algo/kmeans_init/backend/gpu/compute_kernel_dense_dpc.cpp
- cpp/oneapi/dal/algo/kmeans_init/common.cpp
- cpp/oneapi/dal/algo/kmeans_init/common.hpp
- cpp/oneapi/dal/algo/kmeans_init/compute_types.cpp
- cpp/oneapi/dal/algo/kmeans_init/compute_types.hpp
- cpp/oneapi/dal/algo/kmeans_init/detail/compute_ops.cpp
- cpp/oneapi/dal/algo/kmeans_init/detail/compute_ops.hpp
- cpp/oneapi/dal/algo/kmeans_init/detail/compute_ops_dpc.cpp
- examples/oneapi/cpp/source/kmeans_init/kmeans_init_dense.cpp
- examples/oneapi/dpc/source/kmeans_init/kmeans_init_dense.cpp
- default method: dense
- Task for `compute_input`, `compute_result` and `compute(...)`
> conformance between spec and API: kmeans_init

- cpp/oneapi/dal/algo/knn/backend/cpu/infer_kernel_kd_tree.cpp
- cpp/oneapi/dal/algo/knn/backend/cpu/train_kernel_kd_tree.cpp
- cpp/oneapi/dal/algo/knn/backend/gpu/infer_kernel_brute_force_dpc.cpp
- cpp/oneapi/dal/algo/knn/backend/gpu/train_kernel_brute_force_dpc.cpp
- cpp/oneapi/dal/algo/knn/common.cpp
- cpp/oneapi/dal/algo/knn/common.hpp
- examples/oneapi/cpp/source/knn/knn_cls_kd_tree_dense_batch.cpp
- examples/oneapi/dpc/source/knn/knn_cls_brute_force_dense_batch.cpp
`data_use_in_model` parameter removed from new Knn interfaces since it makes no sense with the accordance of input table immutability.
> Knn: set_data_use_in_model parameter removed

- .mergify.yml
In case of merge conflicts backports are get lost - they will be created anyway now
> Force backports in case of conflicts

- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch.h
- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch_impl.i
- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_predict_result.h
KDTree kNN indices type fix to prevent warning with clang compiler.
> KDTree kNN indices type fix

- cpp/daal/include/services/library_version_info.h
- examples/daal/cpp/daal_win.vcxproj.tpl
- examples/daal/cpp/makefile_win
- examples/daal/cpp_sycl/daal_win.vcxproj.tpl
- examples/daal/cpp_sycl/makefile_win
- examples/oneapi/cpp/makefile_win
- examples/oneapi/cpp/onedal_win.vcxproj.tpl
- examples/oneapi/dpc/makefile_win
- examples/oneapi/dpc/onedal_win.vcxproj.tpl
- makefile
- makefile.ver
- samples/daal/cpp/arrow/launcher.bat
- samples/daal/cpp/kdb/launcher.bat
- samples/daal/cpp/mpi/launcher.bat
- samples/daal/cpp/mysql/launcher.bat
Rename dynamic library files and create new chain of links:
1. Linux:
- Old: libdaal*.so -> libonedal*.so
- New: libonedal*.so -> libonedal*.so.{major version} -> libonedal*.so.{major version}.{minor version}
2. MacOS:
- Old: libdaal*.dylib -> libonedal*.dylib
- New: libonedal*.dylib -> libonedal*.{major version}.dylib -> libonedal*.{major version}.{minor version}.dylib
3. Windows:
- Old: onedal_dll.lib
- New: onedal_dll.{major version}.lib
> New library versioning

- java/com/intel/daal/data_management/data/csr_numeric_table_impl.cpp
rowOffsetsBuffer length should be nRows+1
I found this one when using Java CSRNumericTable interfaces long[] getRowOffsetsArray() with native allocation (dataAllocatedInJava=false)
I am not sure if there is same bug elsewhere.
> Fix copying rowOffsets buffer in CSRNumericTableImpl_getRowOffsetsBuffer

- cpp/daal/include/data_management/data/internal/numeric_table_sycl_soa.h
After resize _arrays still had a size of 0. Because of this, there were problems with MergedTable in benchmarks
> Fix array size in sycl SOA

- .ci/pipeline/docs.yml
- cpp/oneapi/dal/algo/kmeans/common.hpp
- cpp/oneapi/dal/algo/kmeans/infer_types.hpp
- cpp/oneapi/dal/algo/kmeans/train_types.hpp
- cpp/oneapi/dal/algo/kmeans_init/common.hpp
- cpp/oneapi/dal/algo/kmeans_init/compute_types.hpp
- cpp/oneapi/dal/algo/knn/common.hpp
- cpp/oneapi/dal/algo/knn/infer_types.hpp
- cpp/oneapi/dal/algo/knn/train_types.hpp
- cpp/oneapi/dal/algo/pca/common.hpp
- cpp/oneapi/dal/algo/pca/infer_types.hpp
- cpp/oneapi/dal/algo/pca/train_types.hpp
- cpp/oneapi/dal/array.hpp
- cpp/oneapi/dal/table/column_accessor.hpp
- cpp/oneapi/dal/table/common.hpp
- cpp/oneapi/dal/table/homogen.hpp
- cpp/oneapi/dal/table/row_accessor.hpp
From #1074: the part with doxygen comments 
- transferred doxygen comments from specs, made small changes in wording (e.g. removed "shall")
RST files will be added separately. The tool is in #1303 and will also be merged separately.
> [DOC] Added doxygen comments from spec

- cpp/daal/src/algorithms/linear_regression/linear_regression_training_input.cpp
condition for normEqDense has changed,  so no need to add interceptFlag.
> Modifying the input check for normEqDense for linear regression 

- cpp/daal/include/services/internal/sycl/error_handling_sycl.h
Adds the check for linking DPCPP without Level0 on the CPU
> Fix levelzero include

- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_model.cpp
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_model_impl.h
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
- cpp/daal/src/algorithms/dtrees/forest/classification/oneapi/df_classification_train_hist_oneapi_impl.i
- cpp/daal/src/algorithms/dtrees/forest/df_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_model.cpp
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_model_impl.h
- cpp/daal/src/algorithms/dtrees/forest/regression/oneapi/df_regression_train_hist_oneapi_impl.i
- cpp/daal/src/externals/core_threading_win_dll.cpp
- cpp/daal/src/threading/threading.cpp
- cpp/daal/src/threading/threading.h
1. Fixed instability in training due to undefined order of pushing trees into a model.
2. Fixed instability in prediction due to usage of TLS with undefined order of reduction in one of code branches. + possible optimizations for this case.
3. More accurate summation for probabilities in prediction to avoid cases, when sum of probabilities > 1.0
> Fix stability in decision forest prediction

- .bazelrc
- .ci/pipeline/ci.yml
- cpp/oneapi/dal/algo/pca/test/badarg.cpp
Test [cache feature](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops) of Azure pipelines on Bazel.
**Results:** LinuxBazel pipeline run time reduced from **36 min** to **6 min** :fire:
@napetrov, have a look: [before caching](https://dev.azure.com/daal/DAAL/_build/results?buildId=8460&view=logs&jobId=7b57b3de-9813-5583-aff5-3419092f5c46) vs [after caching](https://dev.azure.com/daal/DAAL/_build/results?buildId=8512&view=logs&jobId=7b57b3de-9813-5583-aff5-3419092f5c46).
> Test bazel cache in Azure pipelines

- cpp/oneapi/dal/test/engine/dataframe_common.cpp
- dev/bazel/flags.bzl
Tried to build bazel tests on GCC 7.4 and got some errors caused by warnings in test infrastructure.
> Fix warnings that cause error on GCC 7.4

- .bazelrc
- cpp/oneapi/dal/algo/pca/BUILD
- cpp/oneapi/dal/backend/primitives/BUILD
- cpp/oneapi/dal/backend/primitives/blas/BUILD
- cpp/oneapi/dal/test/engine/config.cpp
- dev/bazel/cc/common.bzl
- dev/bazel/dal.bzl
- dev/bazel/deps/onedal.tpl.BUILD
- makefile
- Add \*-public configs (public stands for public C++ interface):
- host-public
- dpc-cpu-public
- dpc-gpu-public
- Bugfixes to make `--test_link_mode=release_*` work with DPC++
> Add Bazel config to filter out public interface tests

- .bazelrc
- cpp/daal/BUILD
- dev/bazel/HOWTO.md
- dev/bazel/config/config.bzl
- dev/bazel/config/config.tpl.BUILD
- dev/bazel/dal.bzl
- Split `dpc-cpu` and `dpc-gpu` configs into two options:
- `--config` can be either `host` or `dpc`.
- Add one more parameter `--device`, can be `cpu` or `gpu`. 
- Add `--test_external_datasets` option to enable tests tagged with `[external-dataset]`
- Update bazel HOWTO
- Refactor and simplify `.bazelrc` and options definitions
> Support more switches to control tests configurations

- .bazelrc
- cpp/oneapi/dal/backend/primitives/stat/BUILD
- Add configs `private`, `public`, `host-private` and `dpc-private`
- Fix `private` attribute for covariance tests
> Ad public and private configs to Bazel

- cpp/oneapi/dal/test/engine/BUILD
- This issue sometimes causes multiple definition of symbols when tests are built with `--test_link_mode=release_static`.
> Fix wrong dependency in Bazel test module

- cpp/oneapi/dal/table/test/row_accessor.cpp
- cpp/oneapi/dal/test/engine/linalg/matrix.hpp
Fix the following case:
```sh
bazel test -c dbg //cpp/oneapi/dal/table:test_row_accessor_dpc --device=cpu
```
> Fix flaky test for row accessor

- cpp/daal/src/algorithms/implicit_als/implicit_als_train_init_partial_result.cpp
Fix of check in Implicit ALS Init reported in https://github.com/oneapi-src/oneDAL/issues/1304. According to ALS documentation ([general](https://software.intel.com/content/www/us/en/develop/documentation/onedal-developer-guide-and-reference/top/daal-interfaces/training-and-prediction/implicit-alternating-least-squares.html) and for [Init Step 1](https://software.intel.com/content/www/us/en/develop/documentation/onedal-developer-guide-and-reference/top/daal-interfaces/training-and-prediction/implicit-alternating-least-squares/distributed-processing-2.html#distributed-processing_step-1-on-local-nodes)), column index in input data table is user ID and number of columns in this table should be compared with fullNUsers parameter while number of rows is compared to it and leads to unexpected …
> Fix of check in Implicit ALS Init

- cpp/oneapi/dal/table/BUILD
- cpp/oneapi/dal/table/backend/homogen_table_impl.hpp
- cpp/oneapi/dal/table/detail/homogen_utils.cpp
- cpp/oneapi/dal/table/detail/homogen_utils.hpp
- cpp/oneapi/dal/table/detail/test/homogen_utils.cpp
Created function ``detail::get_original_data()`` that allows getting an array with data located directly in the homogen table without any copies. This is required for Python API to get a mutable pointer from a resulting table without unnecessary data copies.
> Internal API to get original data from homogen_table

- .bazelrc
- cpp/oneapi/dal/test/engine/common_dpc.cpp
- dev/bazel/HOWTO.md
- dev/bazel/config/config.tpl.BUILD
- dev/bazel/dal.bzl
- Add flag to disable double precision tests in Bazel
> Add --test_disable_fp64 option

- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_classification_predict_kernel.h
- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_impl.i
- cpp/daal/src/algorithms/service_kernel_math.h
- cpp/oneapi/dal/algo/BUILD
- cpp/oneapi/dal/algo/chebyshev_distance/BUILD
- cpp/oneapi/dal/algo/chebyshev_distance/common.cpp
- cpp/oneapi/dal/algo/chebyshev_distance/common.hpp
- cpp/oneapi/dal/algo/knn/BUILD
- cpp/oneapi/dal/algo/knn/backend/gpu/infer_kernel_brute_force_classification_dpc.cpp
- cpp/oneapi/dal/algo/knn/backend/gpu/train_kernel_brute_force_classification_dpc.cpp
- cpp/oneapi/dal/algo/knn/common.hpp
- cpp/oneapi/dal/algo/knn/detail/distance.cpp
- cpp/oneapi/dal/algo/knn/detail/distance.hpp
- cpp/oneapi/dal/algo/knn/test/batch.cpp
- cpp/oneapi/dal/detail/error_messages.cpp
- cpp/oneapi/dal/detail/error_messages.hpp
- docs/source/conf.py
- makefile.lst
Chebychev -> Chebyshev
In original scikit-learn it is named as "chebyshev"
> Fix Chebyshev distance naming

- cpp/daal/src/services/service_topo.cpp
We found that the getL1cache, getL2cache, and getLLcache methods cause sporadic crashes of the decisionForest algorithm on CentOs. 
It was decided to hardcode these values ​​and add their computation later.
> hardcode l1, l2 and ll cache sizes

- cpp/oneapi/dal/algo/knn/common.cpp
- cpp/oneapi/dal/algo/knn/common.hpp
Dynamic BC was accidentally broken by latest kNN API changes.
> Fix for dynamic BC for kNN

- docs/Makefile
`make doxygen` does not work as expected because invalid relative input tags.
- fix broken doxygen in docs/Makefile
> fix broken manually doxygen in docs/Makefile

- cpp/daal/include/services/internal/daal_kernel_defines.h
- cpp/daal/src/algorithms/kernel.h
- cpp/oneapi/dal/backend/dispatcher.hpp
When we building of oneDAL with custom IS (Instruction Set), for example:
```bash
make onedal REQCPU=avx2
```
Kernels implementation use the selected custom IS, only on the machine that has the top cpu extension (_kernels will run with avx2 only on Haswell or Broadwell IA_), in other cases, kernels work only with sse2 code, even on SKX, CLX, etc IA.
This is because we have a similar code with the dispatcher
```c++
cpuid = avx512
switch (cpuid):
// case avx512: ... (not compiler code for custom build with avx2)
case avx2: ... // <-avx2 kernel
default: ...   // <-sse2 kernel
```
Use minimal between custom IS (from make) and top cpu extension from run on IA
> Fix building with custom instruction set

- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/df_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_dense_default_impl.i
Accuracy/MSE and performance were measured and compared on some datasets. Accuracy score was compared on autogluon dataset.
> RF: support filtering of const features

- docs/source/conf.py
To collect usage data for GitHub Pages, we need to link to the Intel cookies notice.
Plus other minor updates to align with the oneAPI content strategy.
> [DOC] Update doc configurations

- cpp/oneapi/dal/algo/subgraph_isomorphism/common.hpp
- cpp/oneapi/dal/algo/triangle_counting/common.hpp
- examples/oneapi/cpp/source/connected_components/connected_components_batch.cpp
- examples/oneapi/cpp/source/example_util/output_helpers.hpp
- examples/oneapi/cpp/source/graph/directed_graph.cpp
- examples/oneapi/cpp/source/graph/graph_service_functions.cpp
- examples/oneapi/cpp/source/graph/load_graph.cpp
- examples/oneapi/cpp/source/jaccard/jaccard_batch.cpp
- examples/oneapi/cpp/source/shortest_paths/shortest_paths_batch.cpp
- examples/oneapi/cpp/source/subgraph_isomorphism/subgraph_isomorphism_batch.cpp
- examples/oneapi/cpp/source/triangle_counting/triangle_counting_batch.cpp
deleting allocator usage in examples, beautifying example output
> Graph examples: delete allocator usage in example

- dev/bazel/cc.bzl
- dev/bazel/cc/link.bzl
- dev/l0_tools/.clang-format
- dev/l0_tools/BUILD
- dev/l0_tools/utils.hpp
- dev/l0_tools/zeinfo.cpp
- dev/l0_tools/zexx.hpp
Introduce L0-based tool to get information about GPU :fire:
**Build:**
```sh
bazel build //dev/l0_tools:zeinfo
```
**Usage:**
```sh
./bazel-bin/dev/l0_tools/zeinfo
./bazel-bin/dev/l0_tools/zeinfo info
./bazel-bin/dev/l0_tools/zeinfo freq
```
In general, you may find out LevelZero API usage examples useful in the future.
Example of tool output:
```sh
[GPU:0] XXXXXXXXXXXXXXXXXXX [xxxxxx] 
Threads per EU: X
EU SIMD width (32-bit lane): X
EUs layout (EUs x sub-slices x slices): X x X x X = XX
Peak f32_mad/clock: XXX
Min frequency (core): XXXMHz
Max frequency (core): XXXXMHz
```
> Add L0-based tools for GPU monitoring

- cpp/daal/src/data_management/train_test_split.cpp
Fix for incorrect work of train_test_split when `train_size + test_size < input_size`. In previous version of code, input numeric table wasn't fully read and incorrect exception was raised. Fixes https://github.com/intel/scikit-learn-intelex/issues/767 issue.
> Train_test_split fix for specific subset sizes

- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_model.cpp
Since 2020.0 release decision forest serialized model grew 10x times because of probabilities tables addition. Collection of these tables has nTrees items of shape nClasses rows x nNodes columns, each item is Homogen table with dictionary property `featuresEqual = notEqual`. On serialization, numeric table dictionary saves every Feature (i.e. nNodes Features), which has 5 properties (each stored in 64 bytes block because of DataArchive implementation). In result, rough memory usage of serialized prob. tables collection: `nTrees x nNodes x 5 x 64 bytes +  nTrees x nClasses x nNodes x sizeof(double)`. 
Fix: set `featuresEqual = equal` to serialize Feature once for each table
Deserialization from previous releases is saved and checked.
> Fix of Decision Forest model serialization

- cpp/daal/src/data_management/train_test_split.cpp
oneDAL train_test_split produces indices differed from sklearn because of insufficient amount of generated random numbers. This bug causes CI fails for cases where `n` is small or/and far from powers of 2.
Solution: increase RNG numbers from 150% of `n` to 200% of `n` + 32.
> Train_test_split indices fix

- examples/oneapi/cpp/onedal_mac.lst
Remove extra space from first line of list to fix examples running.
> Fix for oneAPI C++ Mac examples list

- cpp/oneapi/dal/algo/basic_statistics/backend/gpu/compute_kernel_dense_impl_dpc.cpp
workaround for the failure under level0 in case of whole set of benchmarks is launched
> workaround for the failure under level0

- cpp/oneapi/dal/backend/communicator.cpp
- cpp/oneapi/dal/backend/communicator.hpp
- cpp/oneapi/dal/detail/ccl/communicator.hpp
- cpp/oneapi/dal/detail/communicator.cpp
- cpp/oneapi/dal/detail/communicator.hpp
- cpp/oneapi/dal/detail/error_messages.cpp
- cpp/oneapi/dal/detail/error_messages.hpp
- cpp/oneapi/dal/detail/mpi/communicator.hpp
- cpp/oneapi/dal/spmd/communicator.cpp
- cpp/oneapi/dal/spmd/communicator.hpp
- cpp/oneapi/dal/spmd/detail/communicator_utils.hpp
- cpp/oneapi/dal/test/ccl_communicator.cpp
- cpp/oneapi/dal/test/communicator.cpp
- cpp/oneapi/dal/test/engine/thread_communicator.cpp
- cpp/oneapi/dal/test/engine/thread_communicator.hpp
- cpp/oneapi/dal/test/mpi_communicator.cpp
- Renamed send_receive_replace communicator method to sendrecv_replace
- Fixed incorrect assertions in communicator methods
> Renamed send_receive_replace communicator method to sendrecv_replace

- cpp/daal/src/algorithms/dtrees/forest/classification/oneapi/df_classification_train_hist_oneapi_impl.i
fix for the issue with 0 selected features, the root cause is that under icx daal::internal::Math<float, sse2>::sSqrt(1) returns 0.9999.
> fixed issue with calculating sqrt for classification

- dev/make/cmplr.icx.mk
- dev/make/deps.mk
- examples/daal/cpp_sycl/makefile_lnx
- examples/daal/cpp_sycl/makefile_win
- examples/oneapi/cpp/makefile_lnx
- examples/oneapi/cpp/makefile_win
- examples/oneapi/dpc/makefile_lnx
- examples/oneapi/dpc/makefile_win
- makefile
- samples/daal/cpp/oneccl/makefile_lnx
- samples/oneapi/dpc/ccl/makefile_lnx
This PR contains: 
- Replacing clang (Intel clang) driver with dpcpp in the makefiles
- Enabling library building with icx
> Replacing Intel clang with dpcpp in makefiles

- cpp/oneapi/dal/backend/serialization.hpp
- cpp/oneapi/dal/table/backend/csr_table_impl.hpp
- cpp/oneapi/dal/table/backend/register_serializable.cpp
Add serialization functions for CSR table. Solves https://github.com/intel/scikit-learn-intelex/issues/1005
> CSR table serialization

- cpp/oneapi/dal/common.hpp
Fix for 'unused variable' DPC++ compiler error when assertion (`ONEDAL_ENABLE_ASSERT`) is disabled.
> Fix for 'unused variable' DPC++ compiler error

- cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_fp_impl.hpp
Using `device_global_mem_size` instead of `device_global_mem_cache_size`
> FIX: kmeans bad alloc issue

- docs/source/onedal/build_app/build-application.rst
Update build-application.rst since dpcpp driver is deprecated in the 2023.0 release.
> doc: Update build-application.rst

- examples/daal/cpp/makefile_win
- examples/daal/cpp_sycl/makefile_win
- examples/oneapi/cpp/makefile_win
- examples/oneapi/dpc/makefile_win
Removes unneeded linking on windows and resolves multiply linked symbols error with daal cpp_sycl dynamically linked examples. This error occurred as a result of a previous [pull request](https://github.com/oneapi-src/oneDAL/commit/ad9103a711d8d6ea704b74323bffe68bd0b63d08#diff-db189495ec2d3afed2d74de2deffdcbe325519345bfcf0a2cfda66417a848027) removing the condition to only link the threading library if static linking is indicated. The addition of the thread linking in dynamic mode produces a multiply defined symbols error on windows. Additional unneeded linking is also removed.
-Each windows makefile in oneDAL examples has been modified to remove unnecessary linking for dynamic builds
Each makefile's updates have been tested with both dynamic and …
> removal of unnecessary windows examples linking

- dev/l0_tools/zexx.hpp
`stype` and `pNext` members of `ze_device_properties_t` are input parameters and should be initialized before calling  `zeDeviceGetProperties` 
Signed-off-by: Mateusz Jablonski <mateusz.jablonski@intel.com>
> Initialize ze_device_properties_t before calling zeDeviceGetProperties

- .github/renovate.json
- .github/workflows/renovate-validation.yml
This change is intended for enabling automerge for doc dependencies generated by renovate
- enable automerge for renovate jobs on docs
- add github action validation for renovate config
> Introducing automerge for doc requerements

- .ci/pipeline/ci.yml
There is no guaranties for such configuration from us. GNU compilers supported for linux only. 
Also this is longest build step, so suggest to remove it
> Removign MacOS GNU config

- .ci/pipeline/ci.yml
- Update DPC++ compiler to 2023.0.0 from APT
- Remove LinuxMakeClang as partial duplicate of LinuxMakeDPCPP
> Update DPC++ compiler to 2023.0.0 in public CI

- dev/make/common.mk
- Change install_name (similar to SONAME on linux) of mac libs to one with major binary version
> Change install_name of mac libs

- cpp/daal/src/algorithms/kernel_function/kernel_function.cpp
- cpp/daal/src/algorithms/kernel_function/polynomial/kernel_function_polynomial_csr_fast_impl.i
- cpp/daal/src/algorithms/kernel_function/polynomial/kernel_function_polynomial_dense_default_impl.i
- cpp/daal/src/algorithms/svm/svm_predict_impl.i
- cpp/daal/src/algorithms/svm/svm_predict_kernel.h
New branch of SVM inference for small number of samples:
- Avoid threading in SVM inference when nBlocks == 1 or nBlocks * nBlocksSV < 16
- Use `matrixVector` instead of `matrixMatrix` method of kernel function if number of rows in X == 1
- Implement `matrixVector` method for `polynomial` and `sigmoid` kernels
> SVM inference for small number of samples

- cpp/daal/src/algorithms/linear_regression/linear_regression_training_input.cpp
- cpp/daal/src/algorithms/ridge_regression/ridge_regression_training_input.cpp
Ridge and linear regressions in batch/online mode might work for some cases where n_samples < n_features and especially for online mode where total n_samples > n_features.
According to that, input check should be less strict to allow users compute linear models for these cases.
Solves https://github.com/intel/scikit-learn-intelex/issues/1025
> Less strict input check for linear models

- cpp/daal/src/threading/threading.h
When compiling w/ [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer) we are getting
```
ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs operator delete)
```
presumably due to the mismatch between
https://github.com/oneapi-src/oneDAL/blob/63681e65828995164ea4986fb2174e61f63cd647/cpp/daal/src/threading/threading.h#L399
and
https://github.com/oneapi-src/oneDAL/blob/63681e65828995164ea4986fb2174e61f63cd647/cpp/daal/src/threading/threading.h#L432
It appears that the latter should be
```
delete[] _storage;
```
> Fix AddressSanitizer error: alloc-dealloc-mismatch

- cpp/oneapi/dal/algo/knn/backend/gpu/infer_kernel_impl_dpc.hpp
- cpp/oneapi/dal/algo/knn/backend/gpu/infer_kernel_impl_dpc_distr.hpp
Pass class count to distance voting primitive instead of k value. This resolves incorrect knn classification using distance voting on single gpu and distributed implementations. (ie examples/oneapi/dpc/knn_cls_brute_force_dense_batch)
> resolving knn classification distance voting issue

- cpp/daal/include/services/daal_defines.h
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
- cpp/daal/src/algorithms/dtrees/gbt/gbt_train_hist_kernel.i
- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_train_dense_default_impl.i
- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_impl.i
- cpp/daal/src/algorithms/kernel_function/kernel_function_csr_impl.i
- cpp/daal/src/algorithms/kernel_function/kernel_function_rbf_helper.h
- cpp/daal/src/algorithms/qr/qr_dense_default_pcl_impl.i
- cpp/daal/src/algorithms/service_kernel_math.h
- cpp/daal/src/algorithms/service_sort.h
- cpp/daal/src/algorithms/svm/svm_train_common_impl.i
- cpp/daal/src/algorithms/tsne/tsne_gradient_descent_fpt_cpu.cpp
- cpp/daal/src/data_management/data_conversion.cpp
- cpp/daal/src/data_management/data_conversion_cpu.cpp
- cpp/daal/src/data_management/data_conversion_cpu.h
- cpp/daal/src/data_management/finiteness_checker.cpp
- cpp/daal/src/externals/service_blas.h
- cpp/daal/src/services/service_defines.h
- cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_avx512.hpp
- cpp/oneapi/dal/algo/subgraph_isomorphism/backend/cpu/bit_vector.hpp
- cpp/oneapi/dal/algo/subgraph_isomorphism/backend/cpu/compiler_adapt.hpp
- cpp/oneapi/dal/algo/triangle_counting/backend/cpu/intersection_tc.hpp
- cpp/oneapi/dal/backend/common.hpp
- cpp/oneapi/dal/backend/primitives/intersection/intersection.hpp
- docs/source/contribution/coding_guide.rst
Update intel compiler macros checks with Intel_LLVM case for migration to ICX compiler
> Intel_LLVM compiler macros

- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_dense_default_impl.i
Corrects an error with random histogram selection when the minidx =0, it causes minidx to underflow size_t.
- Swaps the order for proper logic in the ternary operator, this is in training df_regression and df_classification. The ternary checks if minidx is 0 by using the fact that (bool) of 0 is False, and then doesn't do the subtraction and instead uses other logic.
-
-
> DAAL random splitter bugfix histogram size_t underflow

- docs/source/onedal/algorithms/clustering/kmeans.rst
Fix typo in math syntax in K-Means algorithm description
> Fix typo in K-Means docs

- cpp/oneapi/dal/backend/primitives/split_table.hpp
Fix for split_table bazel test failures in oneDAL internal CI
> split table event modifications

- cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
The algorithm is not implemented for CPU therefore we cannot test it
> fixup: skip tests on unsupported device/CPU

- .ci/pipeline/ci.yml
- dev/make/common.mk
- makefile
Remove '\b' symbol from sed command on macOS to fix selection of kernels.
> Fix for kernels selector sed command on macOS

- cpp/daal/include/algorithms/decision_forest/decision_forest_training_parameter.h
- cpp/daal/src/algorithms/dtrees/dtrees_feature_type_helper.h
- cpp/daal/src/algorithms/dtrees/dtrees_feature_type_helper.i
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/classification/oneapi/df_classification_train_hist_oneapi_impl.i
- cpp/daal/src/algorithms/dtrees/forest/df_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/df_training_parameter.cpp
- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/forest/regression/oneapi/df_regression_train_hist_oneapi_impl.i
Improve API that allows feature discretization for RF training.
The quantile indexing that is currently hardcoded and tough to disable should be
* more easy to disable / configure (maxBins, binWidth, memorySavingMode, bUseIndexedFeatures, etc.)
* happening in a more transparent fashion
* extended by average binning
Kicked off by https://github.com/intel/scikit-learn-intelex/issues/1090, this draft already improves the MSE on the reported dataset. In a test run I find
```
Intel® extension for Scikit-learn Mean Squared Error using quantiles binning: 64401.01440419433  *current release*
Intel® extension for Scikit-learn Mean Squared Error using averages binning: 21383.80560598015  *new option*
stock-learn Mean Squared Error: 20962.250402202062
```
I will run more tests as soon as the API is …
> Provide quantiles and average binning for RF histograms

- cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_cls.cpp
- cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_reg.cpp
For whatever reason, the seed is not passed to the RNG constructor for decision forest on CPU in oneDAL. While this doesn't enable engines other than MT2203, at least this can enable various random state starting points.
- Use seed from descriptor and pass to the DAAL RNG constructor in classifier
- Use seed from descriptor and pass to the DAAL RNG constructor in regressor
> Add RNG seed to oneDAL Decision Forest on CPU

- .ci/pipeline/ci.yml
- cpp/daal/include/data_management/data/internal/finiteness_checker.h
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_predict_dense_default_batch_fpt_cpu.cpp
- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
- cpp/daal/src/algorithms/dtrees/gbt/classification/gbt_classification_predict_dense_default_batch_impl.i
- cpp/daal/src/algorithms/dtrees/gbt/gbt_predict_dense_default_impl.i
- cpp/daal/src/algorithms/dtrees/gbt/regression/gbt_regression_predict_dense_default_batch_impl.i
- cpp/oneapi/dal/algo/triangle_counting/backend/cpu/intersection_tc.hpp
Changes:
- Set compiler to `icx` for `LinuxMakeDPCPP` job
- Set optimization level to avx2 for `LinuxMake*` jobs
- Fix `icx` compilation errors:
- Force inline for some of decision forest classification `PredictClassificationTask` methods
- Replace std::isnan with `x != x` comparison (orevents icx error: `explicit comparison with NaN in fast floating point mode`)
- Explicit ifdef(AVX512F) in intersection_tc.hpp
> icx compiler and avx2 optimization level for CI

- docs/source/daal/algorithms/decision_forest/decision-forest-classification.rst
- docs/source/daal/algorithms/decision_forest/decision-forest-regression.rst
- docs/source/daal/algorithms/decision_forest/decision-forest.rst
I think `maxBins` and `minBinSize` descriptions should have been added before. Would be great if someone could double-check.
The `binningStrategy` description is new and should certainly be added.
> doc: provide maxBins/minBinSize/binningStrategy description

- cpp/daal/include/algorithms/kmeans/kmeans_init_distributed.h
This patch is the minimally possible correction for the identified memory leaks in "kmeans" example.
I verified that all classes in KMeans using the base class DistributedBase do this in the same manner:
: DistributedBase(new ParameterType(...)), parameter(*static_cast<ParameterType *>(_par))
Thus, in the existing code this patch is applicable and correct. Removing the field _par in the deeper base class (like Algorithm<batch>) is not applicable since sometimes _par in classes-successors points out to another class field.
Other memory leaks identified by Valgrind and Inspector are related with:
1) not freed singleton classes that is not interpreted as a real memory leak;
2) with macros DAAL_MKLFN_CALL and DAAL_VSLFN_CALL_NR_WHILE that relate to the layer between DAAL and MKL rather than …
> Patch for #173: Memory Leak for Kmeans example

- cpp/oneapi/dal/backend/primitives/objective_function/BUILD
- cpp/oneapi/dal/backend/primitives/objective_function/logloss.hpp
- cpp/oneapi/dal/backend/primitives/objective_function/logloss_dpc.cpp
- cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
To use logloss objective in newton-cg optimizer it should provide hessian-product callable object.
In this PR I implemented class logloss_hessp<Float> with overloaded operator() to calculate hessian product and implemented a function that calculated raw hessian
> Add hessian product function to logloss primitve

- docs/source/conf.py
With the new Sphinx theme the line is needed to have "oneDAL Documentation" line under the oneAPI logo. 
-
-
-
> [doc]Update conf.py

- cpp/daal/src/algorithms/dtrees/dtrees_model_impl.h
https://github.com/oneapi-src/oneDAL/pull/2345 introduced a new feature (`defaultLeft`) to the `DecisionTreeTable` without requesting space for it in the base `AOSNumericTable`. This results in an `ErrorIncorrectDataRange` thrown here
https://github.com/oneapi-src/oneDAL/blob/c98b1cf9ea7ee6b267c7d8dabafbd2ad60a4be5b/cpp/daal/include/data_management/data/aos_numeric_table.h#L208
when called from the `DecisionTreeTable` constructor here
https://github.com/oneapi-src/oneDAL/blob/c98b1cf9ea7ee6b267c7d8dabafbd2ad60a4be5b/cpp/daal/src/algorithms/dtrees/dtrees_model_impl.h#L68
> fix: nColumns in AOSNumericTable constructor

- cpp/oneapi/dal/backend/primitives/optimizers/newton_cg_dpc.cpp
Replacing of https://github.com/oneapi-src/oneDAL/pull/2449
https://github.com/oneapi-src/oneDAL/pull/2437 can lead to compile error here https://github.com/oneapi-src/oneDAL/blob/199d4a56ab1913d5f39b561212d5952b06e7a844/cpp/oneapi/dal/backend/primitives/optimizers/newton_cg_dpc.cpp#L63
> fix: fix deduction of min template in newton cg

- cpp/daal/src/algorithms/classifier/classifier_predict_fpt.cpp
- cpp/daal/src/algorithms/kmeans/kmeans_result.h
- cpp/daal/src/algorithms/optimization_solver/iterative_solver_types.cpp
- cpp/daal/src/algorithms/optimization_solver/iterative_solver_types_fpt.cpp
- cpp/daal/src/algorithms/service_hash_table.h
- cpp/daal/src/algorithms/svm/svm_model_fpt.cpp
* Change the #include "service_utils.h" to the #include "service_arrays.h" in service_hash_table.h. The change is necessary due to the use of TArray template defined in service_arrays.h
* Fix build errors that appeared after the include change
> Fix the include in service_hash_table.h

- cpp/oneapi/dal/backend/primitives/blas/test/gemv_dpc.cpp
Disabling gemv test as its dependent on MKL fix that is not available until 2024.0 compiler changes are merged
> infra: disabling gemv test

- INSTALL.md
- cpp/daal/include/algorithms/algorithm_container_base_batch.h
- cpp/daal/include/algorithms/algorithm_container_base_common.h
- cpp/daal/include/services/env_detect.h
- cpp/daal/include/services/internal/daal_kernel_defines.h
- cpp/daal/src/algorithms/dtrees/gbt/gbt_train_hist_kernel.i
- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_train_dense_default_impl.i
- cpp/daal/src/algorithms/kernel.h
- cpp/daal/src/algorithms/kernel_function/kernel_function_csr_impl.i
- cpp/daal/src/algorithms/linear_model/linear_model_train_qr_update_impl.i
- cpp/daal/src/algorithms/naivebayes/naivebayes_predict_fast_impl.i
- cpp/daal/src/algorithms/naivebayes/naivebayes_train_impl.i
- cpp/daal/src/algorithms/qr/qr_dense_default_batch_impl.i
- cpp/daal/src/algorithms/qr/qr_dense_default_pcl_impl.i
- cpp/daal/src/algorithms/svd/svd_dense_default_batch_impl.i
- cpp/daal/src/externals/core_threading_win_dll.cpp
- cpp/daal/src/services/service_defines.h
- cpp/oneapi/dal/algo/subgraph_isomorphism/backend/cpu/compiler_adapt.hpp
- cpp/oneapi/dal/backend/dispatcher.cpp
- cpp/oneapi/dal/backend/dispatcher.hpp
- cpp/oneapi/dal/backend/dispatcher_cpu.hpp
- cpp/oneapi/dal/backend/interop/common.hpp
- cpp/oneapi/dal/backend/micromkl/macro.hpp
- cpp/oneapi/dal/backend/primitives/intersection/intersection.hpp
- cpp/oneapi/dal/detail/dispatcher.hpp
- cpp/oneapi/dal/detail/policy.hpp
- docs/source/daal/services/managing-computational-environment.rst
- java/com/intel/daal/services/CpuType.java
- makefile
Cleaning remain of dropped instruction sets
> AVX/SSSE3/AVX512_MIC ISA cleanup

- cpp/daal/include/daal_win.h
- cpp/daal/src/externals/core_threading_win_dll.cpp
- cpp/daal/src/services/dll.rc
- docs/source/onedal/build_app/build-application.rst
- makefile.ver
> infra: update binary version

- cpp/oneapi/dal/detail/chunked_array_impl.cpp
Substitute integral_cast_debug check with integral_cast check in constructor to validate parameter and throw exception if it is incorrect
> Fix remaining coverity hits

- cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_precomputed.cpp
- cpp/oneapi/dal/algo/pca/backend/gpu/train_kernel_cov_impl_dpc.cpp
- cpp/oneapi/dal/algo/pca/backend/gpu/train_kernel_precomputed_impl_dpc.cpp
Fix PCA test failures: 
- Wrong ASSERT(has_mutable_data()) for this kernel no need to have data being mutable.
- set_variances() to result. 
- Wrong order for sycl::event and wait_and_throw() before setting.
> Fix GPU test failures: PCA

- dev/make/cmplr.clang.ref.mk
- makefile
Make some small changes to the makefiles, to support building the reference backend, and for using a custom-built TBB
- Makefile for clang reference backend needs to specify the same defines as the GCC build
- When oneTBB is not in the __deps folder, allow for it to be identified from the TBBROOT environment variable
> Support building reference backend with clang

- cpp/daal/src/data_management/data_conversion_cpu.cpp
- cpp/daal/src/data_management/finiteness_checker.cpp
Some of optimized code branches were disabled by `#if defined(__AVX512F__) && defined(DAAL_INTEL_CPP_COMPILER)` check for `icc` compiler.
This PR removes check for `__AVX512F__` define and changes check from `DAAL_INTEL_CPP_COMPILER` to `__INTEL_COMPILER`.
> Fix for compiler defines

- cpp/daal/include/algorithms/algorithm_types.h
This PR replaces `std::uint32_t` and `std::int64_t` with `uint32_t` and `int64_t` in DAAL's 'algorithm_types.h' header file.
> Fix "no type named 'uint32_t'" failure in ICX build

- cpp/daal/include/algorithms/algorithm_types.h
- cpp/daal/src/algorithms/algorithm_hyperparameter.cpp
- cpp/daal/src/algorithms/covariance/covariance_container.h
- cpp/daal/src/algorithms/covariance/covariance_hyperparameter.cpp
- cpp/daal/src/algorithms/covariance/covariance_hyperparameter_impl.h
- cpp/daal/src/algorithms/covariance/covariance_impl.i
- cpp/daal/src/algorithms/linear_model/linear_model_hyperparameter.cpp
- cpp/daal/src/algorithms/linear_model/linear_model_hyperparameter_impl.h
- cpp/daal/src/algorithms/linear_model/linear_model_train_normeq_update_impl.i
- cpp/daal/src/algorithms/linear_regression/linear_regression_hyperparameter.cpp
- cpp/daal/src/algorithms/linear_regression/linear_regression_hyperparameter_impl.h
Removed unnecessary #include <cstdint> from "algorithm_types.h" file.
By design we are trying not to include additional standard or third-party files into DAAL user-facing headers.
This is done so as not to clutter up end user's code with additional declarations.
Following changes were made in the code of `algorithms::Hyperparameter` and the derived classes to get rid of data types defined in <cstdint>:
- `std::unit32_t` type was changed to `unsigned int` in interface part of the code and to `uint32_t` in kernel part of the code
- `std::int64_t` types was changed to `DAAL_INT64`
> Fix 'no type named 'uint32_t'' failure in ICX build

- cpp/daal/src/algorithms/dtrees/gbt/classification/gbt_classification_model_impl.h
- cpp/daal/src/algorithms/dtrees/gbt/regression/gbt_regression_model_impl.h
Fixing a default value hit for gbt classification and regression
- add default value to gbt classification ModelImpl
- add default value to gbt regression ModelImpl
> coverity fixes 2024.0.1

- cpp/daal/src/algorithms/dtrees/gbt/treeshap.h
#2460 forgot to remove a fn declaration from `treeshap.h` - `getRequestedAlgorithmVersion()` no longer exists.
> chore: remove fn decl from header after it was deleted

- dev/make/cmplr.icc.mkl.mk
Currently the bullseye banner is printed for every single source file, resulting in unnecessarily large log.
> Add --no-banner flag to covc

- cpp/daal/src/algorithms/kernel_inst_x86.h
Remove unused *DISPATCH_CONTAINER* defines that were not removed previously during the neural networks functionality removal.
> Remove outdated kernel-related defines in DAAL

- .github/workflows/docker-validation-nightly.yml
It seems like docker validation is working on personal forks of oneDAL. This seems to be a waste of resources
- Add if statement to .github/workflows/docker-validation-nightly.yml
if statement will cause a skip (https://github.com/icfaust/oneDAL/actions/runs/7654417941). (github.repository == 'oneapi-src/oneDAL')
Here is the if statement if true (https://github.com/icfaust/oneDAL/actions/runs/7654476528). (github.repository == 'icfaust/oneDAL'
Slightly modified version so I could manually trigger it (using workflow_dispatch).
> [CI] disable docker-validation-nightly for forks

- cpp/oneapi/dal/algo/logistic_regression/detail/optimizer.cpp
- cpp/oneapi/dal/backend/primitives/objective_function/logloss_dpc.cpp
- cpp/oneapi/dal/backend/primitives/optimizers/cg_solver.hpp
- cpp/oneapi/dal/backend/primitives/optimizers/cg_solver_dpc.cpp
- cpp/oneapi/dal/backend/primitives/optimizers/common.hpp
- cpp/oneapi/dal/backend/primitives/optimizers/common_dpc.cpp
- cpp/oneapi/dal/backend/primitives/optimizers/line_search.hpp
- cpp/oneapi/dal/backend/primitives/optimizers/line_search_dpc.cpp
- cpp/oneapi/dal/backend/primitives/optimizers/newton_cg.hpp
- cpp/oneapi/dal/backend/primitives/optimizers/newton_cg_dpc.cpp
- cpp/oneapi/dal/backend/primitives/optimizers/test/cg_solver_dpc.cpp
- cpp/oneapi/dal/backend/primitives/optimizers/test/newton_cg_dpc.cpp
Aligning implementation of cg-solver and newton-cg with https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/utils/optimize.py#L148 and https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/utils/optimize.py#L84
- Change newton-cg and cg-solver primitives stopping conditions
- Change the default number of maxinner iterations for newton-cg
- Add profiler kernels
> Align Newton-CG and CG-solver stopping conditions with sklearn.utils

- cpp/oneapi/dal/algo/kmeans_init/backend/gpu/compute_kernel_distr_plus_plus_dense_dpc.cpp
Due to sporadic failures in Kmeans Init in distributed mode, temporary solution is to replace bcast() with allreduce().
> KMeans spmd timeout fix

- cpp/daal/src/algorithms/export_win32e.def
Add missing symbols to mklfpk on Windows.
> Fix exports in FPK on Windows

- cpp/oneapi/dal/backend/primitives/objective_function/test/fixture.hpp
Their was a problem with computation of gth logloss because the probability value was too close to 0 or 1 so log(prob) produced a nan value. I added probability clipping to avoid problems with logloss computation (the same approach is used in original algorithm)
> Fix logloss test failure

- cpp/oneapi/dal/algo/logistic_regression/backend/gpu/train_kernel_dense_batch_dpc.cpp
- cpp/oneapi/dal/algo/logistic_regression/backend/optimizer_impl.hpp
- cpp/oneapi/dal/algo/logistic_regression/common.cpp
- cpp/oneapi/dal/algo/logistic_regression/common.hpp
- cpp/oneapi/dal/algo/logistic_regression/detail/optimizer.cpp
- cpp/oneapi/dal/algo/logistic_regression/train_types.cpp
- cpp/oneapi/dal/algo/logistic_regression/train_types.hpp
- cpp/oneapi/dal/backend/primitives/optimizers/newton_cg.hpp
- cpp/oneapi/dal/backend/primitives/optimizers/newton_cg_dpc.cpp
- cpp/oneapi/dal/backend/primitives/optimizers/test/newton_cg_dpc.cpp
To access the number of iterations done by cg-solver on the python side we need to add a new result_option to oneDAL algorithm
> Add inner_iterations_count result option to LogisticRegression

- .gitignore
- Add MODULE.bazel.lock to gitignore
- remove redundant entry
> MAINT: add MODULE.bazel.lock to .gitignore

- deploy/local/vars_lnx.sh
To support cross-compilation we want to allow the architecture to be specified, rather than being auto-detected in lnx_vars.sh. As such we only check the uname in the case that ARCH_ONEDAL is unset.
- Update auto-generated lnx_vars.sh to use value set for environment variable ARCH_ONEDAL, if se
> Allow overriding of ARCH_ONEDAL in Linux vars.sh

- .ci/scripts/build.sh
The build script for CI is useful to use locally. However, the conda path does not need to be the same on the local system. As such, we only source the conda environment in the case that we request it.
Locally, having conda available in PATH will prevent conda from being sourced again, meaning we can have a different conda environment installed on the system
- Moves the sourcing of an absolute path, available in the CI images, behind and if statement
- Protects the loading of a conda installation, if one has already been found
> Only load conda environment if required

- cpp/oneapi/dal/backend/dispatcher.hpp
- cpp/oneapi/dal/detail/dtype_dispatcher.hpp
dtype dispatcher for Dataframe Intercahnge Protocol in Python
Duplicate from https://github.com/oneapi-src/oneDAL/pull/2555
Since I have some problems with the original fork, moved changes to this branch.
> ENH: dtype dispatcher for Dataframe Intercahnge Protocol in Python

- .ci/pipeline/ci.yml
- .ci/scripts/build.sh
In preparation for adding some more targets, making a few cosmetic adjustments to the top level build script
- Naming of flags consistently uses '-' instead of '_'
- Added help text
- The OS and ARCH variables are sub-fields of the PLAT, so just pass the PLAT
- Set pipefail and exit on failure, which means that failures are not silently ignored. This is only a problem (currently) locally, but it helps a lot in refactoring build scripts.
- Paths are made relative to the oneDAL root directory, rather than the current working directory.
> Minor refactor of the top-level CI build script

- .ci/env/openblas.sh
OpenBLAS recommends using the same options in the make command line for installation, as was used for building. Without the correct options, the installation target may look for non-existent files, and at worst will install the incorrect target.
- Store the options used in the OpenBLAS build command, and re-use these in the install target
> OpenBLAS use make options in install

- cpp/daal/src/algorithms/kmeans/kmeans_plusplus_init_impl.i
- cpp/oneapi/dal/algo/kmeans_init/BUILD
- Update kmeans_init BUILD file so tests are ran from CI bazel test scope (in current main branch tests are NOT ran)
- Fix infinite loop kmeans_init++ that led to timeout in testing
> FIX: kmeans_init bazel test enabling

- cpp/daal/src/algorithms/pca/pca_dense_correlation_online_kernel.h
- cpp/oneapi/dal/algo/pca/backend/cpu/finalize_train_kernel_cov.cpp
- cpp/oneapi/dal/algo/pca/test/fixture.hpp
- cpp/oneapi/dal/algo/pca/test/online.cpp
- Added handling of isDeterministic option to CPP online part of PCA algorithm
- signFlip is now called if isDeterministic is true for CPP online part as well
> [bug] Add signflip to CPU online PCA

- .ci/env/openblas.sh
- .ci/scripts/build.sh
- dev/make/deps.ref.mk
Getting ready to add a clang cross-compile path, we tidy up the OpenBLAS build script a little. LLVM is the preferred compiler toolchain for RISC-V at the moment, but the changes to come start with adding an aarch64 cross-compilation build.
As a bonus, because I recently learned about shellcheck, run this on the openblas.sh and build.sh scripts and tidy up warnings. The shellcheck changes are mostly to do with escaping.
Changes proposed in this pull request for openblas.sh CI build script:
- Add help text. Use the 'column' command to indent this properly
- Make the command-line arguments use a '-' instead of '_' to match build.sh
- Add an option to set the source directory of OpenBLAS. This makes it easier to run this script locally, and build out-of-source
- Make paths relative to the …
> Refactor OpenBLAS build script

- .ci/env/tbb.sh
- .ci/pipeline/ci.yml
- .ci/scripts/build.sh
In the case that a CI pipeline builds OpenBLAS or oneTBB from source, those should be cached and reused. The version of the libraries will be the same from run to run, so that we can leverage the Azure caching capability.
Changes made:
- build.sh will not try to build OpenBLAS or oneTBB in the case that explicit install paths are passed in
- OpenBLAS and oneTBB install scripts explicitly take a version string, so that we can use this as part of CI, and pass it through to the build scripts
- Use a cache task in the Arm and x86 CI builds when OpenBLAS or oneTBB is used as the backend
> Cache BLAS and TBB builds in CI

- cpp/oneapi/dal/backend/primitives/sparse_blas/test/gemm_dpc.cpp
- cpp/oneapi/dal/backend/primitives/sparse_blas/test/gemv_dpc.cpp
Sparse SYCL primitives testing disabled on the architectures that do not have native float64
> Workaround to sparse primitives failures in private CI

- cpp/oneapi/dal/algo/pca/backend/gpu/infer_kernel_dpc.cpp
Dependencies for PCA inference on GPU were not well aligned. It caused wrong answers in some scenarios. In this PR inconsistencies are fixed.
- Fixed dependencies and added wait_and_throw to all conditionally created events.
- Removed unnecessary wait_and_throw
- Made result setting more clear with additional variables
> [bug] Fix event dependencies for PCA infer on GPU

- docs/README.md
Instructions on how to define an explicit target for cross references so that duplicate targets are not created.
Using implicit targets (using the heading as the link you put in your cross reference) introduces the possibility of having two targets with the same name. For example, if you have a section titled "Configuration" in the introduction section, but you have another "Configuration" section in the API section, then the reference will break because the generator (Sphinx) will not know which target to point to. Explicit targets solves this problem.
Some lines you may not see a change because the only change is that a trailing space at the end of the line has been removed. This is the default in my text editor because I work with some repositories that require that no file has a …
> Update doc/readme.md to define how to create cross references

- cpp/oneapi/dal/algo/knn/backend/gpu/infer_kernel_impl_dpc.hpp
- cpp/oneapi/dal/algo/knn/backend/gpu/infer_kernel_impl_dpc_distr.hpp
Removes unnecessary duplicate sqrt of distances
This fixes issues identified during mpi-pytest integration in sklearnex
> FIX: distributed knn double sqrt bug

- .github/workflows/openssf-scorecard.yml
- README.md
This Pull Request adds a new GitHub Actions workflow that runs the OpenSSF Scorecard tool on our repository.
- Added a new workflow file `openssf-scorecard.yml` in the `.github/workflows` directory.
The OpenSSF Scorecard is an automated security tool that performs a series of checks on our codebase and provides a score based on the results. By adding this workflow, we can automate the process of running the Scorecard tool and publishing the results.
The workflow is triggered on the following events:
- On a schedule, every Friday at 21:00 UTC.
- When a push is made to the `main` branch.
> chore: add OpenSSF Scorecard GitHub Action

- .ci/env/apt.sh
- .ci/pipeline/ci.yml
The riscv64 and x86_64 OpenBLAS builds have been failing. For the riscv64 build, the location of the qemu debian package changed. We update the URL to obtain, as well as making sure that failing to obtain the right QEMU will cause an error in CI.
For the x86_64 build, illegal instructions are being reported, which I can't reproduce locally. My intuition is that there is something wrong with the cached build, so we update the key for the build. The naming in the key now matches that of the aarch64 and riscv64 builds.
- Error in CI if QEMU is not installed properly
- Update the QEMU debian package to download for riscv64
- Update the key in the cache for x86_64 OpenBLAS builds
> CI fixes in OpenBLAS builds

- cpp/oneapi/dal/detail/cpu_info_impl.cpp
Added error reporting in case invalid iterator is returned by map::find in cpu_info.
> Fix coverity 'invalid iterator' failure

- cpp/oneapi/dal/backend/primitives/reduction/test/reduction_dpc.cpp
- cpp/oneapi/dal/backend/primitives/reduction/test/reduction_rm_random_dpc.cpp
Corrects issues seen on lower precision GPU bazel testing.
- switch double to float because of underlying dataframe datatype being float
- disable lower precision tests due to issues with cw reductions
> [bug, testing] correct reduction bazel testing for float32-only devices

- .github/workflows/openssf-scorecard.yml
A new github action with a cron job was added to oneDAL (via #2753). As it is currently setup, this will run for all forks every friday at 9PM UTC.  To prevent this, a repository check will be added, and the step will be skipped for everything but the onedal-src/oneDAL repository. This matches changes made to the [docker validation nightly](https://github.com/oneapi-src/oneDAL/blob/main/.github/workflows/docker-validation-nightly.yml#L29)
- Add repository check to openssf-scorecard github action
> [CI] add repository check to openssf-scorecard github action

- .github/workflows/slack-pr-notification.yml
- .github/workflows/slack-pr.yaml
Publish a notification to the onedal channel in the UXL slack space when a PR is labeled RFC. To see a sample, look at rc-test channel. They are some test messages for onednn for the same workflow. This is the same workflow as https://github.com/oneapi-src/oneDNN/pull/1900. Only the channel name and license has changed.
To enable the notification, someone with admin privileges must add a secret called SLACK_BOT_TOKEN to the repo. I can provide the value of the token in a DM. After the secret is added and this PR is merged, then new PR's with the RFC label will trigger the notification.
Addresses part of https://github.com/orgs/uxlfoundation/projects/5?pane=issue&itemId=57348837
@vbm32 @napetrov
> slack notification when PR is labelled RFC

- cpp/daal/include/data_management/features/internal/helpers.h
- examples/daal/cpp/target_excludes.cmake
`daal::data_management::features::internal::getIndexNumType<unsigned long>` is used by other functions that perform type conversions. This function was disabled for non x86_64 devices (when `__x86_64__`  is not defined). This PR modifies adds more conditions in the macro to enable this for aarch64 and riscv64.
This change fixes the following examples that were failing on aarch64, when tested on Graviton3 (openblas,+gcc  build).
1. assoc_rules_apriori_batch
2. cd_dense_batch
3. cor_dense_distr
4. cor_dense_online
5. cov_dense_distr
6. cov_dense_online
7. elastic_net_dense_batch
8. lasso_reg_dense_batch
9. low_order_moms_csr_distr
10. low_order_moms_csr_online
11. low_order_moms_dense_distr
12. low_order_moms_dense_online
13. pivoted_qr_dense_batch
> Bugfix in getIndexNumType function

- cpp/oneapi/dal/backend/primitives/reduction/test/reduction_dpc.cpp
- cpp/oneapi/dal/backend/primitives/reduction/test/reduction_rm_random_dpc.cpp
Contains changes from https://github.com/oneapi-src/oneDAL/pull/2769 proposed to fix issue with GPU reduction primitives.
> Fix reduction failure in Bazel test

- cpp/daal/BUILD
- cpp/daal/src/algorithms/linear_model/linear_model_train_normeq_merge_impl.i
- cpp/daal/src/threading/service_thread_pinner.cpp
- cpp/daal/src/threading/threading.cpp
- makefile
Changes:
- Remove `__DO_TBB_LAYER__` and `__DO_SEQ_LAYER__` usage
- Use part of sequential branches for running with 1 thread to avoid TBB overheads
> Fix usage of sequential execution branches

- .ci/env/apt.sh
- .ci/env/openblas.sh
- .ci/pipeline/ci.yml
- examples/daal/cpp/CMakeLists.txt
- examples/daal/cpp/target_excludes.cmake
OpenBLAS uses 32-bit integers by default . But DAAL_INT is 64-bit integer type. This causes errors during LAPACK calls, where the argument is expected to be a pointer to 32-bit integer, but a pointer to 64-bit integer is given. This causes many examples that use LAPACK to fail.
Build openBLAS with ILP64 interface by adding `BINARY=64` and `INTERFACE64=1` while building. An option to switch ILP64 interface has been added to the openblas build script (by default ILP64 interface is built). 
This change fixes the following examples which have been removed from the exclude list.
1. out_detect_mult_dense_batch
2. pca_cor_dense_batch
3. pca_cor_dense_distr
4. pca_cor_dense_online
5. qr_dense_batch
6. qr_dense_distr
7. qr_dense_online
8. svd_dense_batch
Changes were tested on Graviton3 …
> Changed openblas build to ILP64

- .ci/scripts/build.bat
- .ci/scripts/test.bat
Current Azure Pipelines public CI steps do not properly show errors. This issue is similar to intel/scikit-learn-intelex#1609 , for .bat files, the error code must be set and propagated to the end to properly show a failure in Azure Pipelines.
This PR will first require fixes to a bug introduced into LinearRegression Algos in #2565 (possibly)
- Add errorcodes to .ci/scripts/build.bat
- Extend errorcodes in .ci/scripts/test.bat
> [bug, CI] fix error handling in windows builds

- cpp/daal/src/externals/service_spblas_ref.h
- examples/daal/cpp/CMakeLists.txt
- examples/daal/cpp/target_excludes.cmake
The reference implementation of `csrmv` and `csrmultd`  were missing. These are required by algorithms that compute covariance of data in CSR format.
$C = \hbox{op}(A)B$, where A and B are CSR matrices (3-array format, 1-based indexing) and C is a dense matrix stored in column major format. $op$ is either identity transformation or the transpose. 
`xcsrmultd` calls the two functions `csrmultd` or `csrmultd_transpose`. The function `csrmultd` does $C:=AB$ and the function `csrmultd_transpose` does $C:=A^tB$. Implementation is based on the [MKL specification](https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-c/2024-0/mkl-csrmultd.html)
$y \leftarrow \beta y + \alpha\cdot \hbox{op}(A)x$, where x and y are 1D arrays, alpha and beta are scalars and $op$ is either identity …
> Added `csrmultd` and `csrmv` reference implementation

- cpp/oneapi/dal/detail/hash_map.hpp
Fixes memory leak in hashmap caught in test with valgrind for DBSCAN. 
"delete[] entries_" is not enough to deallocate the individual hash_map_entry objects.
> Fix memory leak in hashmap

- cpp/oneapi/dal/table/backend/csr_kernels.cpp
The warning stared to appear after PR https://github.com/oneapi-src/oneDAL/pull/2794 was merged.
SYCL `parallel_for` in `is_sorted` function was re-written to fix the warning.
> Fix "loop not vectorized" warning when running with newer icpx compiler

- cpp/daal/src/externals/service_stat_ref.h
- examples/daal/cpp/CMakeLists.txt
Reference implementation of the statistics routine `x2c_mom`
These changes enable the example `em_gmm_dense_batch` with reference backend. This has been removed from the exclude list. The changes were tested on AWS Graviton3 with gcc+openblas build.
Data is a matrix $X\in\mathbb{R}^{p\times n}$. Each column is a $p$-dimensional vector sampled independently. The matrix  $X$ is assumed to be stored in column-major fashion.
The variance estimator is a $p$ dimensional vector whose $i$th component is
$$v_i = \frac{1}{n-1}\sum_{j=1}^n (x_{ij} - \mu_i)^2.$$
The implementation first computes the second raw sum ($S^{(2)} := \sum_i x_i^2$) and mean ($\mu$); and then uses 
$$v = \frac{S^{(2)}}{n-1} - \frac{n}{n-1}\mu^2 = \frac{S^{(2)}}{n-1}-\frac{(S^{(1)})^2}{n(n-1)}$$ 
to compute the variance.
> Added 2c_mom reference implementation

- cpp/daal/include/algorithms/pca/pca_types.h
PCA's nComponents parameter description didn't mention it works for batch mode only. This doc string is reused in [daal4py docs](https://intelpython.github.io/daal4py/algorithms.html#daal4py.pca) resulting in confusion that parameter is supported for all modes.
Addresses https://github.com/intel/scikit-learn-intelex/issues/759.
> Correct PCA nComponents description

- .ci/pipeline/ci.yml
Adoption of https://github.com/intel/scikit-learn-intelex/pull/1955.
Changes:
- Remove daal4py references from CI
- Remove separate `setup_sklearnex.py` installation
> Update sklearnex building and testing CI job

- cpp/oneapi/dal/algo/logistic_regression/detail/infer_ops.cpp
- cpp/oneapi/dal/algo/logistic_regression/detail/train_ops.cpp
Add ONEDAL_EXPORT to sparse method for logistic regression algorithm to enable sparse computations on sklearnex side
> Add missing ONEDAL_EXPORT for sparse Logistic Regression

- dev/make/compiler_definitions/icx.mkl.32e.mk
Disable unnecessary linking to Intel libs by `icx` compiler.
Solves https://github.com/intel/scikit-learn-intelex/issues/1981.
> Disable Intel libs link for icx compiler

- .ci/env/editorconfig-checker.sh
- .ci/pipeline/ci.yml
- .ecrc
- .editorconfig
- .github/renovate.json
- CONTRIBUTING.md
This Pull Request adds an [editorconfig-checker](https://github.com/editorconfig-checker/editorconfig-checker) to CI pipeline.
- In [ci.yml](https://github.com/oneapi-src/oneDAL/blob/main/.ci/pipeline/ci.yml) the job previously known as `ClangFormat` has been renamed to `FormattersChecks` to better reflect the expanded scope of formatting checks.
-  `editorconfig-checker` has been added to the list of checks. This tool will verify that all submitted code follows the rules specified in `.editorconfig` file.
- The `.editorconfig` file has been added with the following configurations to maintain code quality and consistency across different file types including Python, Perl, C, C++, Java, and Fortran among others (`max_line_length` temporary disabled):
```ini
root = true …
```
> chore(workflows): add `editorconfig-checker`

- cpp/oneapi/dal/algo/basic_statistics/backend/gpu/finalize_compute_kernel_dense_impl_dpc.cpp
- cpp/oneapi/dal/algo/basic_statistics/test/online_spmd.cpp
- cpp/oneapi/dal/algo/covariance/backend/gpu/finalize_compute_kernel_dense_impl_dpc.cpp
- cpp/oneapi/dal/algo/covariance/test/online_spmd.cpp
- cpp/oneapi/dal/algo/linear_regression/backend/gpu/finalize_train_kernel_norm_eq_impl_dpc.cpp
- cpp/oneapi/dal/algo/linear_regression/test/online_spmd.cpp
- cpp/oneapi/dal/algo/pca/backend/gpu/finalize_train_kernel_cov_impl_dpc.cpp
- cpp/oneapi/dal/algo/pca/test/online_spmd.cpp
- Fix finalize method for all four online SPMD algorithms, now the call does not affect partial results since all necessary tables are copied. It allows to call finalize between calls of partial_fit to obtain intermediate results
- Add ONEDAL_DATA_PARALLEL to finalize implementations where they were forgotten
> [fix] Fix online SPMD algorithms finalize call

- cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
Disables ensemble level parallelism in classifier inference to avoid excessive memory and CPU usage on machines with higher number of cores.
> Perf. fix for decision forest classifier inference

- .github/workflows/label-enforcement.yml
- .github/workflows/label_enforcement.yml
PR rules related to labeling are currently not enforced. Labels are required by the development guideline for oneDAL. This adds a GitHub Action to PRs to verify that at least some label has been set to guide reviewers.
- Add a Github Action check for pull requests which checks the labels.
> [enhancement] Add a label checker to GitHub Actions

- .github/workflows/nightly-build.yml
```__release_*_icx``` was changed to ```__release_*``` in #2712 this broke the artifact upload step in the GitHub Actions nightly build.  This PR solves the issue by now pointing the Linux release upload directory at ```___release_lnx``` instead of ```__release_lnx_icx```
- Change nightly-build.yml linux artifact upload directory
> [bug] fix nightly-build regression caused by #2712

- cpp/daal/include/algorithms/decision_forest/decision_forest_classification_model_builder.h
- cpp/daal/include/algorithms/gradient_boosted_trees/gbt_classification_model_builder.h
- cpp/daal/include/algorithms/gradient_boosted_trees/gbt_regression_model_builder.h
- examples/daal/cpp/source/decision_forest/df_cls_dense_batch_model_builder.cpp
- examples/daal/cpp/source/decision_forest/df_cls_traversed_model_builder.cpp
- examples/daal/cpp/source/gradient_boosted_trees/gbt_cls_traversed_model_builder.cpp
- examples/daal/cpp/source/gradient_boosted_trees/gbt_reg_traversed_model_builder.cpp
There are a few functions in Random Forest and Gradient Boosted tree in DAAL that have been deprecated and replaced by newer definitions which expects one or two parameters more. Because of the deprecation flags CI throws warnings on windows. The deprecated functions are being used from examples and some tests on ci. This PR modifies the examples to use newer definitions. Public CI failure will be addressed on https://github.com/oneapi-src/oneDAL/pull/2891
> Update deprecated functions in RF and GBT Examples

- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_train_dense_default_impl.i
Make coverity fixes for 2025.0
-  Remove bad bounds check from KNN classification using kdtrees
> [bug] Coverity fixes 2025.0

- dev/make/function_definitions/32e.mk
Change default COMPILER from `icc` to `icx` in makefile 32e helper.
> Change default COMPILER to icx in makefile

- cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_csr_impl.hpp
Migration to the new icx compiler from icc caused timeouts for Kmeans sparse GPU inputs.
Issue was in the kernel https://github.com/oneapi-src/oneDAL/blob/b6b6a65a59b46d6770198abfc11cfa476c1338a2/cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_csr_impl.hpp#L374 where iterator wrongly gets id.
> FIX: `Kmeans` timeouts issue on GPU for sparse inputs

- .github/ISSUE_TEMPLATE/RFC.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
This PR adds issue templates to make external contribution and communication simpler and easier.  Users of oneDAL will be able to submit issues for a range of problems outside of bug reports.  These files follow the standard set by oneDAL's bug_report.md, and are based off of oneapi-src/oneMKL#10 and oneapi-src/oneTBB#1400 .  This addresses uxlfoundation/open-source-working-group#40
- add documentation.md
- add RFC.md
- add feature_request.md
- add question.md
> [enhancement] Add new issue templates

- .ci/env/apt.sh
- .ci/env/environment.yml
- dev/docker/README.md
- dev/docker/onedal-dev.Dockerfile
This PR makes some adjustments to the Docker file provided under `/dev`:
* Downloads `Miniforge` (hosted on GitHub) instead of `Miniconda` (hosted on Anaconda).
* ~Replaces usage of `conda` with the newer `mamba`.~ Did not work in the CI.
* Pulls everything from `mamba` from the `conda-forge` repository.
* Uses the [latest version of the instructions](https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=linux&linux-install-type=apt) for adding the intel APT repository, which requires some additional packages.
* Changes the fixed version of `dpcpp` towards the last version instead, as it comes from a non-ubuntu repository which is subject to changes and might at some point no longer host the specific version that was added here.
* Adds …
> Update Docker file

- dev/bazel/toolchains/cc_toolchain_lnx.bzl
There is a step in the bazel test pipeline for `//cpp/oneapi/dal:tests` in which it probes the compiler for include paths of headers to add to the toolchain config:
https://github.com/oneapi-src/oneDAL/blob/b6b6a65a59b46d6770198abfc11cfa476c1338a2/dev/bazel/toolchains/cc_toolchain_lnx.bzl#L103
It does so by requesting the default paths from the compiler with this command:
```shell
<compiler> -E -xc++ - -v
```
In the case of DPCPP, this resolves to:
```shell
icx -E -xc++ - -v
```
By default, `icx` doesn't include sycl linkage, thus the command above does not return the paths of SYCL headers. Under the default `icx` factory settings, that leads to observing an error:
```
the source file 'cpp/oneapi/dal/algo/pca/test/serialization.cpp' includes the following non-builtin files with absolute …
```
> Add sycl headers to bazel toolchain config for DPCPP through icx

- .github/workflows/pr-checklist.yml
Fixes setting of DESCRIPTION variable when description of PR contains ` or ``` breaking variable setting in bash.
Blocks of code to test it in current PR:
`print("Hello, world!")`
```print("Hello, world!")```
```python
print("Hello, world!")
```
---
**Testing**
> Fix for getting of description for PR Checklist job

- .github/CODEOWNERS
- MAINTAINERS.md
This is initial version of MAINTAINERS.md that define roles and list certain individuals in those roles. 
Feedback and recommendations are welcome
> Introducing oneDAL roles for contributors and maintainers

- cpp/oneapi/dal/algo/knn/detail/distance.hpp
- cpp/oneapi/dal/algo/objective_function/detail/objective.hpp
- cpp/oneapi/dal/algo/svm/detail/kernel_function.hpp
- dev/docker/onedal-dev.Dockerfile
Currently there is a failure due to the 22.04 sha256 seems invalid.  This upgrades the ubuntu version of the dockerfile to 24.04 (falls in line with #2918)
Solves errors raised by gcc bazel build in 24.04 associated with ```error: possibly dangling reference to a temporary [-Werror=dangling-reference]```
> [maint] Update docker ubuntu version to 24.04

- cpp/daal/src/algorithms/svm/svm_train_common_impl.i
- cpp/daal/src/algorithms/svm/svm_train_common_sve_impl.i
This PR introduces performance optimizations for the WSSJ Float using SVE intrinsics, resulting in significant improvements for the SVM algorithms on ARM.
**Key Improvements:**
Boser Method: 22% performance gain, leading to faster computation and better resource utilization.
Thunder Method: 5% performance gain, enhancing efficiency in scenarios where this method is used.
**Changes:**
Code Updates: New SVE intrinsics based WSSJ Float kernel.
**Impact:**
Performance: Faster processing times and improved efficiency for SVM algorithms observed and documented on single core.
Performance on single core (aws instance: c7g.8xl graviton3):
> SVE optimised float WSSJ kernel

- .github/workflows/nightly-build.yml
changes introduced in actions/upload-artifact#625 remove symlink preservation.  This locks to the last symlink-preserving version until an update to the repos can be made in tandem.
Valid run can be found here with the pinned version: https://github.com/icfaust/oneDAL/actions/runs/11230234430/job/31217199566
---
**Testing**
> [fix] pin github actions upload-artifact to v4.4.0 to preserve linux symlinks

- dev/bazel/deps/mkl.tpl.BUILD
Adding linking flag to improve linking of onedal_sycl lib in oneDAL(bazel)
**Testing**
> feature: adding -fsycl-max-parallel-link-jobs in bazel

- .github/workflows/nightly-build.yml
actions/upload-artifact#625 included in 4.4.1 fixes an issue to not preserve symlinks (since fixed in later versions). The Windows Intel oneAPI BaseKit installer uses absolute paths in symlinks rather than relative ones for the ```latest``` folders of various oneAPI components.  This makes a maintenance burden on sklearnex-side since they are unusable. Therefore the fully path must be known and maintained to the compiler and tbb version```vars.bat``` files. A rather long and complicated batch script line was added to force these to be relative.  This removed the maintenance burden by fixing the ```latest``` symlink to work in sklearnex out-of-the-box.  Since it is only one line and fixes what hopefully will only be a temporary issue  I don't think necessitates its own script.  Because of …
> [enhancement] Store windows basekit with symlink-preserving compression for nightly-build

- .github/workflows/nightly-build.yml
Mistakes in #2947 did not correct the issue about the naming scheme of the nightly, this is the correct solution.
I apologize for the mistakes.
> [fix] nightly-build.yml to look at the correct directory, and name proper artifact for sklearnex

- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_train_dense_default_impl.i
The pull request introduces a workaround for the K-Nearest Neighbors (KNN) algorithm. This fix addresses issues related to the algorithm's execution in threading part of KNN KD-tree. Additionally, the memory usage has improved. With these fix we will observe temporary performance degradations. The fix will be done in https://github.com/oneapi-src/oneDAL/pull/2925
---
**Testing**
> fix: workaround for Knn KD tree 

- .ci/env/apt.sh
- .ci/env/tbb.sh
- .ci/pipeline/ci.yml
- .ci/scripts/build.sh
Changes:
- Update and pin DPC++ compiler and oneAPI runtime libs to 2025
- MKL-based jobs: update oneMKL to 2025, change oneTBB installation from github to apt and pin compatible version to 2022 
---
Checklist to comply with **before …
> Update oneAPI components versions in CI

- .github/workflows/nightly-build.yml
Windows uploads the basekit to provide and pin the compiler and oneAPI components to sklearnex GitHub Actions CI for building and testing.  Linux was using either a local version to sklearnex or referencing the dpcpp version in oneDAL main, this breaks CI on upgrades. Sklearnex should actually reference what was used for the build itself. To do this on linux, store the install scripts from ```.ci/env``` in an artifact which can be downloaded and used in sklearnex to pin the oneAPI component versions.
---
You can remove a checkbox as not applicable only if it doesn't relate …
> [CI] store .ci/env as environment for sklearnex GitHub Actions CI

- WORKSPACE
- dev/bazel/deps/tbb.bzl
PR introduces updated versions of dependencies in Bazel WORKSPACE file. All deps have been updated to  oneAPI 2025.0 release.
---
**Testing**
> dev: update bazel oneMKL deps

- .ci/pipeline/ci.yml
- dev/bazel/deps/mkl.tpl.BUILD
PR introduces cycle linking for mkl_core library in bazel. It helps to avoid issues in tests.
---
**Testing**
> fix: add cycle linking for mkl_core(bazel)

- .ci/env/apt.sh
- .github/workflows/nightly-build.yml
- dev/make/compiler_definitions/dpcpp.mk
- dev/make/compiler_definitions/icx.mkl.32e.mk
With the merge of intel/scikit-learn-intelex#2147, runs of Nightly-build are only taken from scheduled or workflow dispatches.  This allows for testing the nightly without disrupting sklearnex CI when changes to CI, make system, or the nightly are made in PRs. This will make it less blind, and verification by reviewers easier/less by faith.  If changes are made to CI, then nightly-build will run on the PR.  This will not be run on main push.
NOTE: This PR fixes two CI issues which have shown up:
1) A qemu install from deb package issue, which the version and dependencies have changed
2) An issue in building the nightly on windows with a VS/DPCPP hybrid build caused by changes introduced in #2946 
---
PR should start as a draft, then move to ready for review state after CI is passed and …
> [CI] make Nightly-build CI run on changes to CI

- docs/source/daal/algorithms/logistic_regression/logistic-regression.rst
This PR fixes a broken link in the docs to an example file from the sklearnex repository that was moved to a different folder:
https://github.com/intel/scikit-learn-intelex/blob/main/examples/mb/log_reg_model_builder.py
The move from the previous path which broke the link in the docs happened as part of this PR:
https://github.com/intel/scikit-learn-intelex/pull/1399
---
For example, PR with docs update doesn't require checkboxes for performance while PR with any change in actual …
> DOC: Fix link to example that was moved

- deploy/local/vars_lnx.sh
- deploy/local/vars_win.bat
Revert of https://github.com/oneapi-src/oneDAL/pull/2777
---
**Testing**
> fix: Set the correct CPATH for oneAPI toolkit

- .gitignore
This PR adds VScode workspace files to the gitignore list of VScode-related files.
---
**Testing**
Not …
> MAINT: Add vscode workspace files to gitignore

- cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_helpers.hpp
This PR fixes an issue in the GPU implementations of decision trees in which inputs that are smaller than the task size of the device queue fail their histogram calculations due to divisions by zeros, as the number of spawned tasks is always the same and in such cases some tasks get empty inputs.
Note: while this PR is not adding any tests in oneDAL, there are currently some deselected tests in scikit-learn-intelex which should be able to test these cases after merging it.
---
For …
> FIX: Fix histogram reduction when number of tasks is larger than input data

- cpp/oneapi/dal/algo/kmeans/detail/infer_ops_dpc.cpp
- cpp/oneapi/dal/algo/kmeans/detail/train_ops_dpc.cpp
The changes in SPMD K-means instantiation were reverted to fix the bug in #2959.
**Testing**
> Revert SPMD K-means instantiation to fix #2959

- INSTALL.md
- cpp/daal/src/externals/service_profiler.cpp
- cpp/daal/src/externals/service_profiler.h
- makefile
Add ability of oneDAL kernels profiling on CPU using <ittnotify.h>.
To enable the kernel profiling in oneDAL build use `REQPROFILE=yes` option of the makefile.
After that run VTune profiling as usual to get performance profiling data.
Example of the hotspot analysis run on Linear Regression example binary:
---
**Testing**
> Add ability of vtune profiling

- cpp/daal/include/algorithms/algorithm_container_base.h
- cpp/daal/include/algorithms/algorithm_container_base_batch.h
Default constructors are set to 'default' implementations;
Copy constructors and copy assignment operators are deleted in base algorithm container classes.
--- …
> Fix rule of three violations in AlgorithmContainer classes

- .github/workflows/nightly-build.yml
This PR updates hardcoded values from oneapi-src to uxlfoundation as shown by the change in organization. Performance benchmarks are not necessary.
--- …
> [CI] prepare for ownership change for Nightly-build

- cpp/oneapi/dal/detail/profiler.hpp
This PR deletes the copy and copy-assignment operators for the profiler class, in order to clear warnings from static code analyzers.
--- …
> MAINT: Delete unused operators for profiler class

- cpp/oneapi/dal/detail/threading.hpp
This PR deletes the copy-assignment and move-assignment operators for the scoped lock class, in order to clear warnings from static code analyzers.
--- …
> MAINT: Delete unused operators for scoped lock class

- cpp/oneapi/dal/detail/global_context.hpp
This PR adds a default destructor for the global policy context class.
It shouldn't make any kind of difference, since this class doesn't hold any members in need of destruction and it's used as a global variable, but it should decrease the number of false-positive findings from static code analyzers.
---
For example, PR with docs update doesn't require checkboxes for performance while PR with any change in actual code should have checkboxes and justify how this code change is …
> MAINT: Add default constructor for global policy context

- cpp/daal/include/algorithms/boosting/adaboost_predict_types.h
- cpp/daal/include/algorithms/boosting/brownboost_predict_types.h
- cpp/daal/include/algorithms/boosting/logitboost_predict_types.h
Default assignment operator was added in `prediction::Input` classes in AdaBoost, BrownBoost and LogitBoost algorithms to fix rule of three violations.
**Testing**
> Fix coverity hits in boosting algorithms

- .ci/env/tbb.bat
- .ci/env/tbb.sh
- .ci/pipeline/ci.yml
- .github/CODEOWNERS
- .github/pull_request_template.md
- .github/workflows/docker-validation-nightly.yml
- .github/workflows/label-enforcement.yml
- .github/workflows/openssf-scorecard.yml
- CONTRIBUTING.md
- INSTALL.md
- MAINTAINERS.md
- README.md
- SECURITY.md
- cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_train_dense_default_impl.i
- cpp/daal/src/threading/threading.h
- deploy/nuget/inteldal.nuspec.tpl
- dev/download_tbb.sh
- docs/README.md
- docs/source/404.rst
- docs/source/conf.py
- docs/source/contribution/coding_guide.rst
- docs/source/contribution/cpu_features.rst
- docs/source/contribution/threading.rst
- docs/source/daal-interfaces.rst
- docs/source/daal/algorithms/logistic_regression/logistic-regression.rst
- docs/source/examples.rst
- docs/source/installation.rst
- docs/source/substitutions_specific.txt
Similar to https://github.com/uxlfoundation/scikit-learn-intelex/pull/2203
After this repository got transferred to uxlfoundation, the doc links for github do not work anymore as they do not redirect to the new URL.
This PR changes all the instances of string "intel.github.io" to "uxlfoundation.github.io" which should be the new URL for these docs.
It also modifies internal links to files within the repository to point to `uxlfoundation/scikit-learn-intelex` instead.
---
For example, …
> DOC: Update doc and internal links after uxl transfer

- cpp/oneapi/dal/detail/sparse_matrix_handle_impl.hpp
This PR deletes the copy and copy-assignment operators for the sparse matrix handle class, in order to clear warnings from static code analyzers.
--- …
> MAINT: Delete unused operators for spmatrix handle class

- dev/make/compiler_definitions/dpcpp.mk
- dev/make/compiler_definitions/icx.mkl.32e.mk
- makefile
Add support for  `Gcov` code coverage for `icx/icpx` builds
---
> feat: add `gcov` code coverage support

- .github/workflows/docker-validation-ci.yml
- .github/workflows/docker-validation-nightly.yml
- .github/workflows/nightly-build.yml
- .github/workflows/pr-checklist.yml
- .github/workflows/renovate-validation.yml
Pin GitHub Actions to specific commit hashes to ensure consistent builds and improve security.
> chore(workflows): pin GitHub Actions by hash

- INSTALL.md
This PR adds instructions for building oneDAL from source using packages from `conda` to satisfy dependencies instead of using system installs. Packages from `conda` don't come with activation scripts, so this adds the necessary instructions for getting them to work with the oneDAL make file.
_Disclaimer: I haven't fully tested the windows instructions._
---
For example, PR with docs update doesn't require checkboxes for performance while PR with any change in actual code should have …
> DOC: Instructions for installing with dependencies from `conda`

- cpp/oneapi/dal/algo/kmeans/test/batch.cpp
- cpp/oneapi/dal/backend/primitives/blas/test/gemv_dpc.cpp
- cpp/oneapi/dal/backend/primitives/selection/test/select_flagged_dpc.cpp
- cpp/oneapi/dal/backend/primitives/selection/test/select_indexed_rows_dpc.cpp
Removes some TODOs in various parts of oneDAL testing as the issues are no longer leading to failed tests locally or in CI
---
**Testing**
> test: remove outdated todos in tests

- cpp/daal/include/algorithms/covariance/covariance_batch.h
- cpp/daal/include/algorithms/covariance/covariance_online.h
- cpp/daal/include/algorithms/covariance/covariance_types.h
- cpp/daal/include/algorithms/distance/correlation_distance.h
- cpp/daal/include/algorithms/distance/cosine_distance.h
- cpp/daal/src/algorithms/covariance/covariance_input.cpp
- cpp/daal/src/algorithms/covariance/covariance_online_parameter.cpp
- cpp/daal/src/algorithms/covariance/covariance_step2_distr_input.cpp
Fix the violation of "Rule of three" for covariance, correlation and cosine distances algorithms
---
**Testing**
> Fix Coverity hits for covariance, correlation and cosine distances

- INSTALL.md
This PR fixes an incorrect syntax order issue in the bash commands presented in the instructions for building with conda dependencies.
--- …
> DOC: Fix incorrect bash syntax in conda build instructions

- .gitignore
This PR updates the `.gitignore` file to ignore custom configurations from file explorers which are left in the directories where they apply.
**Testing**
> MAINT: Ignore config files from file explorers

- cpp/daal/include/algorithms/algorithm_types.h
- cpp/daal/include/data_management/data/data_dictionary.h
- cpp/daal/src/algorithms/algorithm_base_impl.cpp
Add missing copy constructor or assignment operators to fix GCC "implicitly-declared `operator=` is deprecated" and similar errors in `pca_cor_dense_batch` example.
---
**PR …
> Fix GCC build errors in PCA example

- INSTALL.md
This PR expands the conda instructions to cover compilation with GCC and OpenBLAS.
---
**Testing**
> DOC: Conda instructions for other platforms

- docs/source/get-started/build-and-run-examples.rst
Fixes a small typo that was left unmerged from this PR: https://github.com/uxlfoundation/oneDAL/pull/3009
---
**Testing** …
> DOC: Fix typo in documentation

- cpp/daal/src/algorithms/low_order_moments/low_order_moments_impl.i
Adjust number of iterations in a loop to fix "min", "max" and "sum_squares" computations.
---
**Testing**
- All CI jobs are green or I have …
> Fix min, max and sum_squares computations in low order moments

- cpp/daal/src/threading/threading.cpp
We have an issue when calling functions that use the static thread for function being passed `tid` (=thread ID) numbers that can be beyond the number of threads being used, even if the actual computations happen on a lower number of threads.
I _think_ this PR fixes it but I'm not 100% sure yet that it won't break anything else.
---
For example, PR with docs update doesn't require checkboxes for performance while PR with any change in actual code should have checkboxes and justify how …
> FIX: Fix incorrect mapping of thread IDs

- cpp/daal/include/algorithms/optimization_solver/adagrad/adagrad_types.h
- cpp/daal/include/algorithms/optimization_solver/coordinate_descent/coordinate_descent_types.h
- cpp/daal/include/algorithms/optimization_solver/iterative_solver/iterative_solver_types.h
- cpp/daal/include/algorithms/optimization_solver/lbfgs/lbfgs_types.h
- cpp/daal/include/algorithms/optimization_solver/objective_function/cross_entropy_loss_types.h
- cpp/daal/include/algorithms/optimization_solver/objective_function/logistic_loss_types.h
- cpp/daal/include/algorithms/optimization_solver/objective_function/mse_types.h
- cpp/daal/include/algorithms/optimization_solver/objective_function/objective_function_types.h
- cpp/daal/include/algorithms/optimization_solver/objective_function/sum_of_functions_types.h
- cpp/daal/include/algorithms/optimization_solver/saga/saga_types.h
- cpp/daal/src/algorithms/objective_function/cross_entropy_loss/cross_entropy_loss_types.cpp
- cpp/daal/src/algorithms/objective_function/logistic_loss/logistic_loss_types.cpp
- cpp/daal/src/algorithms/objective_function/mse/mse_types.cpp
- cpp/daal/src/algorithms/objective_function/objective_function_types.cpp
- cpp/daal/src/algorithms/objective_function/sum_of_functions_types.cpp
- cpp/daal/src/algorithms/optimization_solver/adagrad/adagrad_types.cpp
- cpp/daal/src/algorithms/optimization_solver/coordinate_descent/coordinate_descent_types.cpp
- cpp/daal/src/algorithms/optimization_solver/iterative_solver_types.cpp
- cpp/daal/src/algorithms/optimization_solver/lbfgs/lbfgs_types.cpp
- cpp/daal/src/algorithms/optimization_solver/saga/saga_types.cpp
Should solve issues with static analyzers pointing out that there are copy constructors without assignment operators for many of the `Input` and `Parameter` class used in optimization routines and which are exported.
---
Checklist to …
> MAINT: Add assignment operators for Input and Parameter classes of solvers

- dev/make/common.mk
- dev/make/deps.mkl.mk
- dev/make/deps.ref.mk
This PR addresses symbol conflicts between oneMKL and oneDAL that emerged after the oneMKL migration. These conflicts occur when both libraries define identical symbols, leading to linker errors or runtime issues.  
To resolve this, we introduced the `--exclude-libs` linker flag to explicitly exclude specific oneMKL libraries from linking, ensuring no overlap with oneDAL symbols.  
- Added `--exclude-libs` to exclude the following oneMKL libraries:  
- `libmkl_intel_ilp64.a`  
- `libmkl_core.a`  
- `libmkl_sycl.a`  
- `libmkl_tbb_thread.a`  
This ensures that oneMKL symbols do not conflict with oneDAL symbols during linking.  
- Added `--exclude-libs` list for OpenBLAS libraries
- Used `foreach` to dynamically generate the `EXCLUDE_LIBS` variable, making it easy to extend the exclusion …
> Resolve Symbol Conflicts Between oneMKL and oneDAL

- cpp/daal/include/algorithms/ridge_regression/ridge_regression_predict_types.h
- cpp/daal/include/algorithms/ridge_regression/ridge_regression_training_types.h
- cpp/daal/src/algorithms/ridge_regression/ridge_regression_prediction_batch.cpp
- cpp/daal/src/algorithms/ridge_regression/ridge_regression_training_input.cpp
This PR addresses Coverity hits on Ridge such as `rule of 3` and `copy without assign`.
---
**Testing**
> FIX: addressing Coverity hits on Ridge

- cpp/oneapi/dal/backend/primitives/objective_function/logloss_functors.hpp
- cpp/oneapi/dal/backend/primitives/objective_function/logloss_functors_dpc.cpp
- cpp/oneapi/dal/backend/primitives/objective_function/test/fixture.hpp
- cpp/oneapi/dal/backend/primitives/objective_function/test/spmd_fixture.hpp
- cpp/oneapi/dal/backend/primitives/optimizers/common.hpp
- cpp/oneapi/dal/backend/primitives/optimizers/line_search_dpc.cpp
- cpp/oneapi/dal/backend/primitives/optimizers/newton_cg_dpc.cpp
- cpp/oneapi/dal/backend/primitives/optimizers/test/fixture.hpp
- cpp/oneapi/dal/backend/primitives/optimizers/test/newton_cg_dpc.cpp
DPC++ newton-cg solver relies on backtracking algorithm to find an optimal step length. In backtracking algorithm we only need to check if Armijo is satisfied at a given point. To do that we only need to know function value, the gradient is not need though in current implementation it is computed. 
In this PR we introduce new parameter need_grad for update_x method to avoid gradient computations when it's not needed. Also update_x function was modified for logloss function.
---
**Testing**
> Remove redundant gradient computation in backtracking algorithm

- cpp/daal/src/algorithms/linear_model/linear_model_hyperparameter_impl.h
- cpp/daal/src/algorithms/linear_model/linear_model_train_normeq_update_impl.i
- cpp/daal/src/algorithms/linear_regression/linear_regression_hyperparameter.cpp
- cpp/daal/src/algorithms/linear_regression/linear_regression_hyperparameter_impl.h
- cpp/daal/src/externals/service_blas.h
- cpp/daal/src/externals/service_blas_declar_ref.h
- cpp/daal/src/externals/service_blas_mkl.h
- cpp/daal/src/externals/service_blas_ref.h
- cpp/oneapi/dal/algo/linear_regression/backend/cpu/finalize_train_kernel_norm_eq.cpp
- cpp/oneapi/dal/algo/linear_regression/backend/cpu/partial_train_kernel_norm_eq.cpp
- cpp/oneapi/dal/algo/linear_regression/backend/cpu/train_kernel_common.hpp
- cpp/oneapi/dal/algo/linear_regression/backend/cpu/train_kernel_norm_eq.cpp
- cpp/oneapi/dal/algo/linear_regression/parameters/cpu/train_parameters.cpp
- cpp/oneapi/dal/algo/linear_regression/test/batch.cpp
- cpp/oneapi/dal/algo/linear_regression/test/fixture.hpp
- cpp/oneapi/dal/algo/linear_regression/test/online.cpp
- cpp/oneapi/dal/algo/linear_regression/test/train_parameters.cpp
- cpp/oneapi/dal/algo/linear_regression/train_types.cpp
- cpp/oneapi/dal/algo/linear_regression/train_types.hpp
- cpp/oneapi/dal/test/engine/fixtures.hpp
This PR adds a preliminary version of a non-batched version of the linear regression normal regression algorithm for high-dimensional problems, which calculates the aggregates $\mathbf{X}^T \mathbf{X}$ and $\mathbf{X}^T \mathbf{y}$ separately through corresponding calls to BLAS functions.
The code route here is only meant for high-dimensional problems where the current approach does not lead to better performance. The idea is to make these thresholds configurable through the same parameters system used for e.g. the batch size in the regular route, but adding new configurable parameters appears to be a much trickier job so I'm starting with this PR with hard-coded thresholds in the meantime.
A few notes:
* ~The function that computes the aggregates takes a flag `initializeResult`, but if …
> ENH: Non-batched linear regression for high-dimensional problems

- cpp/daal/src/algorithms/dtrees/dtrees_model.cpp
- cpp/daal/src/algorithms/dtrees/dtrees_model_impl.h
Adds a check for valid buffer allocations in the copy and copy assignment constructors to address null pointer dereference coverity hits.
--- …
> fix: add isValid() method for dtrees ModelImpl

- .ci/env/apt.sh
- .github/workflows/ci.yml
1. **Update Miniforge Installation Script**:
- Enhanced the `install_miniforge` function in `.ci/env/apt.sh` to dynamically fetch the latest Miniforge version and verify the SHA256 checksum before installation. This ensures that the latest and verified version of Miniforge is installed.
2. **Update GitHub Actions Workflow**:
- Modified the `ci.yml` workflow to use a specific commit hash for the `actions/setup-python` action instead of the latest version. This change ensures consistency and reproducibility in the CI pipeline.
---
You can remove a checkbox as not applicable …
> ci: pin some dependencies by hash

- cpp/daal/src/services/compiler/generic/env_detect_features.cpp
- cpp/daal/src/services/service_defines.h
- cpp/oneapi/dal/detail/cpu.cpp
This makes it possible to use the sse42, avx2 code paths on AMD processors
_Add a comprehensive description of proposed changes_
- Adds proper CPUID extension support checking which was previously done by guarding with a check for Intel CPUs. This allows AMD processors to use the sse42, avx2 code paths instead of the default sse2.
_List associated issue number(s) if exist(s): #6 (for example)_
_Documentation PR (if needed): #1340 (for example)_
_Benchmarks PR (if needed): https://github.com/IntelPython/scikit-learn_bench/pull/155 (for example)_
---
You can remove a checkbox …
> Add proper CPUID eax checking

- dev/bazel/deps/opencl.tpl.BUILD
This pull request updates the Bazel build file for OpenCL dependency to allow the use of different versions of the library.
---
**Testing**
> [backport: rls/2025.4.0-rls] chore(dev): allow bazel to use different versions of OpenCL lib (#3089)

- cpp/oneapi/dal/backend/primitives/distance/BUILD
- cpp/oneapi/dal/backend/primitives/distance/correlation_distance_dpc.cpp
- cpp/oneapi/dal/backend/primitives/distance/correlation_distance_misc.hpp
- cpp/oneapi/dal/backend/primitives/distance/correlation_distance_misc_dpc.cpp
- cpp/oneapi/dal/backend/primitives/distance/distance.hpp
- cpp/oneapi/dal/backend/primitives/distance/metrics.hpp
- cpp/oneapi/dal/backend/primitives/distance/test/correlation_distance_dpc.cpp
> Adding correlation distance metric in oneDAL primitives

- cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_csr_impl.hpp
- cpp/oneapi/dal/algo/kmeans/backend/gpu/train_kernel_lloyd_csr_dpc.cpp
- cpp/oneapi/dal/algo/kmeans/test/batch.cpp
SYCL dependencies flow was fixed in sparse K-means;
Additional .wait() statements were added in `assign_clusters` kernel to workaround the issue.
Testcase that reproduces the failure on PVC was added.
The output of the test before the fix in source files:
```
Abort was called at 80 line in file:
./shared/source/command_stream/linear_stream.h
-------------------------------------------------------------------------------
KMmeans sparse cases on large number of rows - kmeans_types - 1
-------------------------------------------------------------------------------
cpp/oneapi/dal/algo/kmeans/test/batch.cpp:325
...............................................................................
cpp/oneapi/dal/algo/kmeans/test/batch.cpp:325: FAILED:
due to a fatal error condition:
SIGABRT - Abort …
```
> Fix sparse K-means failure on PVC when the number of rows in large

- cpp/oneapi/dal/algo/kmeans/test/batch.cpp
The test that tests SYCL implementation of sparse K-means on the large number of rows was modified:
* It was switched off on CPUs;
* On all GPUs except Intel(R) Data Center GPU Max series, the number of rows in the testing data set was reduced 100 times to prevent out of memory crashes.
---
> Reduce memory requirements of sparse K-means test

- INSTALL.md
~This PR removes the suggestion to install `dos2unix` from conda on windows, since it's not available in that platform:~
https://anaconda.org/conda-forge/dos2unix
This PR removes the current instructions for building with conda-installed tools on windows.
Reason for removal: (a) not all of the necessary software is offered through conda; (b) instructions do not work - e.g. setting `%TBBROOT%` the way it is suggested here would not result in the Makefile finding TBB (paths on windows are different, as they then have `lib`, `bin`, etc.).
---
You can remove a checkbox as not …
> DOC: Remove broken instructions for building with conda environments on windows

- cpp/daal/include/algorithms/outlier_detection/outlier_detection_bacon_types.h
- cpp/daal/include/algorithms/outlier_detection/outlier_detection_multivariate_types.h
- cpp/daal/include/algorithms/outlier_detection/outlier_detection_univariate_types.h
- cpp/daal/src/algorithms/outlierdetection_bacon/outlierdetection_bacon.cpp
- cpp/daal/src/algorithms/outlierdetection_multivariate/outlierdetection_multivariate.cpp
- cpp/daal/src/algorithms/outlierdetection_univariate/outlier_detection_univariate.cpp
This solves a rule-of-three violation in the DAAL outlier detection algorithms, which do not have assignment operators. This adds them to Bacon, univariate and multivariate outlier detectors.
Benchmarking unnecessary.
---
Checklist to …
> Fix outlier detection assignment operators (rule of three violation, Coverity)

- cpp/daal/include/algorithms/regression/regression_predict_types.h
- cpp/daal/include/algorithms/regression/regression_training_types.h
- cpp/daal/src/algorithms/regression/regression_prediction_batch.cpp
- cpp/daal/src/algorithms/regression/regression_training_input.cpp
Adds copy assignment operator to Regression Algorithm.
---
**Testing**
> Regression algorithm Coverity fixes (rule-of-three violation)

- makefile
- makefile.ver
Not always, but often the following error will occur:
```mv: cannot stat './__release_lnx/daal/latest/include/services/library_version_info.h.tmp': No such file or directory```
Which signifies that the ```makefile.ver``` command ```update_headers_version``` is not completing correctly, specifically the commands of ```sed``` or ```cp``` are not completing before ```mv``` is called, causing the failure. New logic is added which will avoid the ```mv``` entirely by only writing to a temporary file if the release file exists, which will then trigger the logic introduced in  #2949.  The copy is removed for this case as the ```sed``` call will accomplish this task.
--- …
> [bug] fix intermittent failures in LinuxMakeDPCPP(AVX512) github action

- INSTALL.md
Currently, the instructions for building with conda-installed toolkits mention to modify env. variable `$PATH` to point to the `/bin` path of the conda environment, but this path is already added to the necessary environment variable when running `conda activate`, so it's not needeed.
This PR removes the line and adds a small note about it.
---
For example, PR with docs update doesn't require checkboxes for performance while PR with any change in actual code should have checkboxes …
> DOC: Remove redundant instruction for `conda`

- .ci/scripts/abi_check.sh
I didn't read the docs well enough in order to avoid abidiff failures for when ABI symbols are added. An additional logic check for this condition is added and avoids raising an error code.
---
Checklist to comply with **before moving PR …
> [bug] fix abi check to not fail for all changes in ABI, just breaking ones

- .github/workflows/ci.yml
These settings are recommended with more recent Intel GPU drivers for memory usage and GPU stability. This may help improve the self_hosted GPU runner stability used in the LinuxMakeDPCPP(AVX512) github actions CI job.  It is only applied in the step which utilizes the GPU, the dpc example operation.  Note that this step currently doesn't fail, but it may be impacting the release of memory, which over multiple jobs may lead to a crash in the runner.  This is not a "causational" fix, but a more "best practices" one.
No performance benchmarks necessary
---
You can remove a …
> [CI, enhancement] set compute runtime GPU settings to improve GPU runner stability

- cpp/daal/include/algorithms/quantiles/quantiles_types.h
- cpp/daal/src/algorithms/quantiles/quantiles.cpp
This adds a missing copy assignment operator to the quantiles Input class for the quantiles algorithm. This solves coverity issues associated with the quantiles algorithm.
---
**PR …
> [fix] add copy assignment operator to quantiles (coverity fix)

- INSTALL.md
- makefile
This adds the ```REQSAN``` flag to the make build which can trigger dynamic linking of an available sanitizer into oneDAL.  This will allow for enhanced memory leak and race condition checking among other possibilities. These are determined from the compiler, and is expected to be the responsibilty of the developer to chose a sanitizer which is available. The most standard practice should be to use ```REQDBG=yes REQSAN=address```
The only special case is value ```static``` which will integrate ASan and link its static version, which requires a special linker flag ```-static-libasan```
No performance benchmarks necessary.
---
This approach ensures that reviewers …
> [enhancement] Add ability to integrate sanitizers in oneDAL Make builds

- makefile.ver
This failure comes from the /bin/sh not understanding the syntax of what was recently implemented in makefile.ver.  This adds quotation marks as per @david-cortes-intel 's suggestion.
Error case can be found here: https://github.com/uxlfoundation/oneDAL/actions/runs/14181809300/job/39729447102
another: https://github.com/uxlfoundation/oneDAL/actions/runs/14194610762/job/39766744941
---
For example, PR with docs update doesn't require checkboxes for performance while PR with any …
> [bugfix] make makefile.ver work with POSIX shells

- examples/daal/cpp/CMakeLists.txt
- examples/oneapi/cpp/CMakeLists.txt
- examples/oneapi/dpc/CMakeLists.txt
Minimal supported CMake version was updated to 3.5 in examples.
Because CMake dropped compatibility with the previous versions.
---
**Testing**
The failure in [CI (LinuxSklearnex Python311)](https://github.com/uxlfoundation/oneDAL/pull/3156/checks?check_run_id=39911039202) step exists in the main branch and is not related to my changes.
Internal CI failed due to infrastructure reasons, also not related to my changes.
> Update CMake version in examples to 3.5

- cpp/daal/src/algorithms/optimization_solver/lbfgs/lbfgs_dense_default_impl.i
Currently, the L-BFGS code has a logic that discards correction pairs if their curvature is exactly equal to zero.
The approximation requires strict positiveness up to numerical precision, so this condition is insufficient:
* If there's no check for Wolfe conditions, the inner product might be negative, which would still make it pass this check.
* The product can be something very small, like 1e-100, in which case it would lead to issues like numbers turning to infinite.
This PR fixes it by hard-coding a more reasonable threshold, with >= condition.
---
You can remove a …
> FIX: Fix potential non-definitiness of BFGS approximation

- README.md
This PR removes the suggestion to use deprecated daal4py from the readme.
---
**Testing**
> DOC: Remove suggestion to use to daal4py in readme (v2)

- INSTALL.md
This PR adds instructions for installing oneDPL through conda. Somehow they were lost on an earlier PR.
CC @Alexandr-Solovev 
---
**Testing** …
> DOC: Add instructions for DPL on conda

- .ci/pipeline/ci.yml
- .ci/scripts/collect_opencl_rt.ps1
New public compiler dropped on March 20th. This can be updated in CI. Unfortunately changes in apt are not yet available meaning Linux must stay temporarily at 2025.0
---
**PR …
> [CI] Update Windows BaseKit, Windows OpenCL Runtime installs to 2025.1

- makefile
To mirror the special value of ```REQSAN=static```, the default linking for ```REQSAN=address``` will be shared because of how the tracing in AddressSanitizer works, it needs the various shared libraries to have a centralized libasan to inspect into the other shared objects of onedal.  By default, gnu vs clang act differently by default at linking, this will make it a standard interface for simpler compiler-to-compiler use.
---
For example, PR with docs update doesn't require …
> [bugfix] make shared-libasan default option for ```REQSAN=address```

- docs/Makefile
Same as https://github.com/uxlfoundation/scikit-learn-intelex/pull/2423
This PR makes the script that builds the docs run in parallel by default.
--- …
> ENH: Parallelize doc build by default

- docs/source/daal/algorithms/logistic_regression/logistic-regression.rst
This PR fixes an incorrect link to the python example for logistic regression model builder.
---
**Testing**
> DOC: Fix broken link to logreg builder

- cpp/daal/include/services/daal_defines.h
- cpp/daal/src/externals/service_memory.cpp
- cpp/daal/src/externals/service_memory.h
- dev/bazel/daal.bzl
* `service_memset_seq`, `service_calloc` and `service_scalable_calloc` functions were modified to use aligned memory loads and stores for aligned data.
* C++ standard version was increased from C++11 to C++17 in `daal_module` in bazel build. This was done to simplify the implementations of `service_calloc` and `service_scalable_calloc` by the use of C++17 features like `if constexpr`.
---
**Testing**
Total geomean speedup across the algorithms is **1.02** on 112-core SPR system. No significant performance changes.
The quality metrics had not changed because the computations logic is not affected.
> Use aligned loads and stores where possible in DAAL memory management

- .github/workflows/ci.yml
This PR moves the UXL foundation self-hosted runners to github hosted runners (ideally on a temporary basis).
The following changes are made:
- ISA is set from AVX512 to AVX2 due to runner limitations
- A matrix value ```ISA``` is defined to control the ISA of the runners, which modifies the displayed job names. Unfortunately it must be lower case because of restrictions set by ```REQCPU```.
- The GPU testing step is disabled by checking the runner name rather than being removed (in the hope that the GPU step removal is temporary).
This does not require performance benchmarking
---
This approach ensures that reviewers don't spend extra time asking for regular …
> [CI] swap uxl self-hosted runners to github hosted

- .ci/pipeline/docs.yml
- docs/Makefile
Create a `venv` for the python packages in the install step. Also add `set -euo pipefail` to fail the correct step if a problem occurs.
Building docs sometimes fails at the `Install requirements` step, preventing the installation of the requirements. The subsequent `Build documentation` will fail with `sphinx-build: not found`.
Example: https://dev.azure.com/daal/DAAL/_build/results?buildId=45831&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86
> fix(docs): Install dependencies fails over debian-installed packages

- .github/workflows/ci.yml
Reverts uxlfoundation/oneDAL#3176
changes made to the runners are complete. ABI check is disabled, see #3176 as to why.
> Revert "[CI] swap uxl self-hosted runners to github hosted"

- deploy/local/vars_lnx.sh
Fix for the CPLUS_INCLUDE_PATH variable
---
**Testing**
> fix: CPLUS_INCLUDE_PATH lnx hotfix

- .github/workflows/docs-release.yml
Similarly to intelex, now we are using github action instead of gh-pages. It is simpler setup as onedal does not need to track all versions
--- …
> fix: use github action instead of gh-pages

- cpp/daal/src/algorithms/covariance/covariance_hyperparameter_impl.h
A typo in indexing was fixed.
---
**Testing**
not applicable.
> Fix hyperparameterIdCount in Covariance

- cpp/daal/src/externals/service_spblas_mkl.h
Fix the `xcsrmv` function for correct covariance algorithm computation.
The issue was in incorrectly provided of beginnings and endings of rows in CSR
---
**Testing**
> Fix: xcsrmv computation wrong arguments

- .ci/scripts/clang-format.sh
This PR fixes the clang-format script to accurately print the version that gets used when linting the files.
---
**Testing**
> CI: Print correct version of clang-format being executed

- .github/workflows/nightly-build.yml
- .github/workflows/nightly-test.yml
Since being integrated in #3204, the nightly has failed.  To improve stability and properly follow the naming schemes the test aspect added is now added in a separate yaml file which is run after completion of a successful build.  This should allow for th sklearnex dependence on Nightly-build to be more stable, while still allowing testing using this cve analysis tool.
No benchmarks or internal CI runs necessary
---
For example, PR with docs update doesn't require checkboxes for …
> [bugfix] separate stability issues of ```intel/cve-bin-tool-action``` from nightly-build

- cpp/daal/src/services/service_topo.cpp
- cpp/daal/src/services/service_topo.h
This PR initializes a pointer to null in the topology object, as otherwise it might get initialized to a random value which would trigger an unnecessary chain of frees and potentially bad memory accesses here:
https://github.com/uxlfoundation/oneDAL/blob/01f2d3c6fff7faa03dcc6a8feac65b3f3d4f6cdd/cpp/daal/src/services/service_topo.cpp#L2017
---
For example, PR with docs update doesn't require checkboxes for performance while PR with any change in actual code should have checkboxes and …
> FIX: Initialize pointer to null in topology struct

- .github/workflows/ci.yml
Due to infrastructure issues, we need to swap back to using github hosted runners (previous PRs: #3176 and #3188).
This is a copy of that original PR, as some changes were made to the yaml file since this was last done.
---
Checklist to …
> [CI] swap uxl self-hosted runners to github hosted 

- cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_cw_atomic_dpc.cpp
Add an exception and a note in `reduction_rm_cw_atomic` primitive that contains a bug.
---
**Testing**
not applicable
> Add error handling in cw_atomic to prevent erroneous method usage 

- cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_cw_wrapper_dpc.cpp
- cpp/oneapi/dal/backend/primitives/reduction/test/reduction_rm_random_dpc.cpp
- cpp/oneapi/dal/backend/primitives/reduction/test/reduction_rm_uniform_dpc.cpp
Fix failures after [#3283](https://github.com/uxlfoundation/oneDAL/pull/3283) merging.
cw_atomic reduction  was marked as unimplemented in the #3283 because of a bug in the implementation.
Some tests started to fail due to that added exception.
This PR removes those failing testcases.
And also fixes the reduction method dispatcher in order not to choose the cw_atomic kernel.
---
For example, PR with docs update doesn't require checkboxes for performance while PR with any change in …
> Fix: Nightly CI failures

- cpp/oneapi/dal/detail/cpu.hpp
This PR fixes a potentially invalid syntax issue that would prevent compilation of the cpu-related files when disabling features or when compiling for other platforms.
---
**PR …
> FIX: Fix extra comma resulting in syntax error depending on defined macros

- cpp/daal/src/algorithms/linear_model/linear_model_train_normeq_update_impl.i
Fixes incorrect direction of the comparison about the small rows threshold for linear regression, which changes what the threshold on number of columns should be for switching between the batched and the non-batched route.
---
Checklist to …
> FIX: Fix incorrect comparison for small rows threshold of linear regression

- cpp/oneapi/dal/algo/knn/backend/model_conversion.hpp
This PR improve the perf for knn prediction by using convert_to_daal_table 
---
**Testing**
> fix: fix the perf for knn preidction

- cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_classification_train_container.h
Small fix to not proceed with a further op if an error has occurred already.
---
**Testing**
> FIX: Check status code after every call

- cpp/daal/src/externals/service_rng_mkl.h
Functions call a macro that checks the error code and makes it return from the function if an error is detected. The error code is then checked again after invocation of the macro, but it cannot signal an error as otherwise a return would have been forced from the macro.
---
<details>
**Testing**
</details>
> MAINT: Avoid redundant check of error codes

- dev/make/compiler_definitions/clang.32e.mk
- dev/make/compiler_definitions/gnu.32e.mk
- dev/make/compiler_definitions/icc.mkl.32e.mk
- dev/make/compiler_definitions/icx.mkl.32e.mk
- dev/make/compiler_definitions/vc.mkl.32e.mk
Currently, setting environment variables such as `${CXXFLAGS}` doesn't have any effect when building oneDAL, because those are ignored as oneDAL sets its own compiler and similar.
This PR makes it forcibly add `${CXXFLAGS}` and `${LDFLAGS}` if they are set. Note that it still ignores other variables like `${CPPFLAGS}` and related, but I cannot think of a good solution to include them all.
Flags are purposefully not set for the DPC++ compiler as it takes other kinds of flags from the usual compilers.
---
You can remove a checkbox as not applicable only if it doesn't relate to …
> MAINT: Don't ignore `$CXXFLAGS` and `$LDFLAGS`

- cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_dense_default_impl.i
Adds some short comments that help in understanding what this function `subtractImpurity` is meant to do.
---
<details>
</details>
> MAINT: Add comments about what `subtractImpurity` does

- cpp/oneapi/dal/algo/basic_statistics/test/batch.cpp
- cpp/oneapi/dal/algo/basic_statistics/test/fixture.hpp
- cpp/oneapi/dal/algo/kmeans/test/batch.cpp
- cpp/oneapi/dal/algo/kmeans/test/fixture.hpp
- cpp/oneapi/dal/table/backend/interop/host_csr_table_adapter.cpp
- cpp/oneapi/dal/test/engine/csr_table_builder.hpp
Fix insufficient memory allocation in case 0-based oneDAL csr_table to 1-based DAAL CSRNumericTable conversion.
---
<details>
**Testing**
New test configurations are failing on GPU. Investigation is in progress.
not applicable.
</details>
> Fix insufficient memory allocation in csr_table conversion

- cpp/oneapi/dal/backend/interop/table_conversion.hpp
Fix the logic in `convert_to_daal_table(const csr_table & table, bool need_copy)`:
Always do copy the table if `need_copy == true`. Because otherwise it can lead to crash on GPU.
---
<details>
**Testing**
The failures are not related to the changes in this PR.
not applicable.
</details>
> Fix failures in kmeans::test_batch_dpc

- cpp/daal/include/data_management/data/data_archive.h
If RF Regressor model is serialized we cause serialization of empty table https://github.com/uxlfoundation/oneDAL/blob/8ef5a1fb16de947fa9ee80803f0daab28599835a/cpp/daal/src/algorithms/dtrees/dtrees_model_impl.h#L535 from here.
If asserts are enable this assert is failing https://github.com/uxlfoundation/oneDAL/blob/773af9612efe34b5eabf1b7492c44981fabc9c17/cpp/oneapi/dal/detail/serialization.hpp#L193
void oneapi::dal::detail::output_archive::range(const T *, const T *) [T = unsigned char]: Assertion `begin' failed.
To fix the issue we only need to write/read bytes if size is not zero
---
**Testing**
</details>
> Fix ONEDAL_ASSERT failure triggered by empty table serialization

- makefile
There exist two python calls in the makefile, one of which generates the pkg-config, and the other references a windows-specific makefile which no longer exists after #2356 . This removes code that should have been removed in that PR. It changes the code to match other similar definitions located later in the makefile.
---
<details>
**Testing**
</details>
> [maintenance] remove makefile reference to deleted code
